In [1]:
# takes 10m
# warning: Requires LOTS of memory and pagefile space. I use 64GB of memory and 32GB+ pagefile.
# warning: Be sure all other apps and windows are closed. You've been warned!
# Data clean acbl board results and write df to file. 

# next steps:
# perform experiments on board results.

# previous steps:
# acbl-sql-to-board-results.ipynb

# todo:
# todo: why are there 24m board_ids not found. Why is that?
# change some dtypes from string to category. Most dytpe of category should be changed to ordered.

In [2]:
# requirements
# Requires LOTS of memory and pagefile space. I use 64GB of memory and 32GB+ pagefile.
# Be sure all other apps and windows are closed. You've been warned!
# If browser/system misbehaves, its probably due to lack of memory and/or pagefile space.
# Jupyter's output console may/may-not output a message about lack of memory/pagefile space.
# Instructions at: https://www.windowscentral.com/how-change-virtual-memory-size-windows-10

In [3]:
import pandas as pd
import pathlib
import mlBridgeLib

In [4]:
# override pandas display options
mlBridgeLib.pd_options_display()

In [5]:
rootPath = pathlib.Path('e:/bridge/data')
acblPath = rootPath.joinpath('acbl')

In [6]:
# takes 1m15s
acbl_board_results_filename = 'acbl-board-results.pkl'
acbl_board_results_file = acblPath.joinpath(acbl_board_results_filename)
df = pd.read_pickle(acbl_board_results_file)
df

          board_result_id  board_id  round_number  table_number  ns_pair  ew_pair ns_score ew_score contract declarer  ew_match_points  ns_match_points opening_lead result  tricks_taken  section_id  board_number  session_id section_name  event_id hand_record_id                 game_date  club_id_number event_type board_scoring_method  tb_count         club_session          player_id_ns                                                                      player_number_ns                                    player_name_ns         mp_total_ns          player_id_ew                                                                      player_number_ew                                  player_name_ew         mp_total_ew
0                29145890   4065740          <NA>          <NA>        1        1     -140      140       2S        W             4.50             1.50          NaN   None           NaN      155573             1      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832775, 4832776]  [tmp:995300bb-6081-4285-a93a-9342d2e7bc1b, tmp:a659aa2e-1428-4ea4-87d3-581db1c2dfad]                        ["sunfeather", "jakspade"]          [nan, nan]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
1                29145897   4065741          <NA>          <NA>        1        1      650     -650       5H        N             2.50             3.50          NaN   None           NaN      155573             2      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832775, 4832776]  [tmp:995300bb-6081-4285-a93a-9342d2e7bc1b, tmp:a659aa2e-1428-4ea4-87d3-581db1c2dfad]                        ["sunfeather", "jakspade"]          [nan, nan]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
2                29145904   4065742          <NA>          <NA>        1        1      100     -100       3N        W             2.00             4.00          NaN   None           NaN      155573             3      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832775, 4832776]  [tmp:995300bb-6081-4285-a93a-9342d2e7bc1b, tmp:a659aa2e-1428-4ea4-87d3-581db1c2dfad]                        ["sunfeather", "jakspade"]          [nan, nan]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
3                29145956   4065749          <NA>          <NA>        4        1     -140      140       2H        W             3.50             2.50          NaN   None           NaN      155573            10      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832788, 4832787]  [tmp:05fb8b01-1366-4fc8-9bb4-13c7f6f012a7, tmp:abf67235-1e01-4f8e-a927-95be148ea12f]               ["valqtown", "whqtown(swap names)"]          [nan, nan]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
4                29145963   4065750          <NA>          <NA>        4        1      480     -480       4S        S             0.50             5.50          NaN   None           NaN      155573            11      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832788, 4832787]  [tmp:05fb8b01-1366-4fc8-9bb4-13c7f6f012a7, tmp:abf67235-1e01-4f8e-a927-95be148ea12f]               ["valqtown", "whqtown(swap names)"]          [nan, nan]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
5                29145970   4065751          <NA>          <NA>        4        1      -90       90       1N        E             1.00             5.00          NaN   None           NaN      155573            12      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832788, 4832787]  [tmp:05fb8b01-1366-4fc8-9bb4-13c7f6f012a7, tmp:abf67235-1e01-4f8e-a927-95be148ea12f]               ["valqtown", "whqtown(swap names)"]          [nan, nan]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
6                29146000   4065755          <NA>          <NA>        6        1     -620      620       4S        W             5.00             1.00          NaN   None           NaN      155573            16      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832795, 4832796]                                                                    [1015699, 6996043]                  ["Maureen Larson", "Ben Levine"]    [1078.3, 309.88]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
7                29146007   4065756          <NA>          <NA>        6        1     -150      150       2D        N             4.50             1.50          NaN   None           NaN      155573            17      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832795, 4832796]                                                                    [1015699, 6996043]                  ["Maureen Larson", "Ben Levine"]    [1078.3, 309.88]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
8                29146014   4065757          <NA>          <NA>        6        1      100     -100      5DX        W             0.00             6.00          NaN   None           NaN      155573            18      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832795, 4832796]                                                                    [1015699, 6996043]                  ["Maureen Larson", "Ben Levine"]    [1078.3, 309.88]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
9                29145978   4065752          <NA>          <NA>        5        1     -110      110       2S        W             3.50             2.50          NaN   None           NaN      155573            13      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832792, 4832791]                                                                    [5231051, 9311599]  ["Jeff Rowland", "Shirley Campbell(swap names)"]       [56.6, 128.2]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
10               29145985   4065753          <NA>          <NA>        5        1      -50       50       3S        S             3.00             3.00          NaN   None           NaN      155573            14      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832792, 4832791]                                                                    [5231051, 9311599]  ["Jeff Rowland", "Shirley Campbell(swap names)"]       [56.6, 128.2]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
11               29145992   4065754          <NA>          <NA>        5        1     -100      100       4H        S             3.50             2.50          NaN   None           NaN      155573            15      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832792, 4832791]                                                                    [5231051, 9311599]  ["Jeff Rowland", "Shirley Campbell(swap names)"]       [56.6, 128.2]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
12               29145912   4065743          <NA>          <NA>        2        1      660     -660       3N        N             0.00             6.00          NaN   None           NaN      155573             4      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832779, 4832780]                                                                    [4029062, 6694985]                     ["John Perry", "Julie Perry"]  [1161.82, 1034.52]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
13               29145919   4065744          <NA>          <NA>        2        1      170     -170       2S        S             0.00             6.00          NaN   None           NaN      155573             5      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832779, 4832780]                                                                    [4029062, 6694985]                     ["John Perry", "Julie Perry"]  [1161.82, 1034.52]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
14               29145926   4065745          <NA>          <NA>        2        1      140     -140       2H        N             2.50             2.50          NaN   None           NaN      155573             6      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832779, 4832780]                                                                    [4029062, 6694985]                     ["John Perry", "Julie Perry"]  [1161.82, 1034.52]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
15               29145934   4065746          <NA>          <NA>        3        1     -200      200       5C        S             6.00             0.00          NaN   None           NaN      155573             7      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832783, 4832784]                                                                    [2745771, 2745771]                    ["Sandy Pyatt", "Sandy Pyatt"]        [2.41, 2.41]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
16               29145941   4065747          <NA>          <NA>        3        1      170     -170       3H        N             1.50             4.50          NaN   None           NaN      155573             8      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832783, 4832784]                                                                    [2745771, 2745771]                    ["Sandy Pyatt", "Sandy Pyatt"]        [2.41, 2.41]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
17               29145948   4065748          <NA>          <NA>        3        1     -130      130       3D        E             6.00             0.00          NaN   None           NaN      155573             9      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832783, 4832784]                                                                    [2745771, 2745771]                    ["Sandy Pyatt", "Sandy Pyatt"]        [2.41, 2.41]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
18               29145911   4065743          <NA>          <NA>        1        7      620     -620       4H        S             1.00             5.00          NaN   None           NaN      155573             4      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832775, 4832776]  [tmp:995300bb-6081-4285-a93a-9342d2e7bc1b, tmp:a659aa2e-1428-4ea4-87d3-581db1c2dfad]                        ["sunfeather", "jakspade"]          [nan, nan]    [4832802, 4832801]  [tmp:45d2e796-3ff4-4227-a227-0263a650615c, tmp:72d12c14-20e3-4fa8-9e78-2808beeaf9f9]           ["dixie_j", "driverbrya(swap names)"]          [nan, nan]
19               29145918   4065744          <NA>          <NA>        1        7     -200      200       4H        N             5.00             1.00          NaN   None           NaN      155573             5      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832775, 4832776]  [tmp:995300bb-6081-4285-a93a-9342d2e7bc1b, tmp:a659aa2e-1428-4ea4-87d3-581db1c2dfad]                        ["sunfeather", "jakspade"]          [nan, nan]    [4832802, 4832801]  [tmp:45d2e796-3ff4-4227-a227-0263a650615c, tmp:72d12c14-20e3-4fa8-9e78-2808beeaf9f9]           ["dixie_j", "driverbrya(swap names)"]          [nan, nan]
20               29145925   4065745          <NA>          <NA>        1        7      400     -400       2S        W             0.00             5.00          NaN   None           NaN      155573             6      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832775, 4832776]  [tmp:995300bb-6081-4285-a93a-9342d2e7bc1b, tmp:a659aa2e-1428-4ea4-87d3-581db1c2dfad]                        ["sunfeather", "jakspade"]          [nan, nan]    [4832802, 4832801]  [tmp:45d2e796-3ff4-4227-a227-0263a650615c, tmp:72d12c14-20e3-4fa8-9e78-2808beeaf9f9]           ["dixie_j", "driverbrya(swap names)"]          [nan, nan]
21               29145977   4065752          <NA>          <NA>        4        7     -110      110       1S        W             3.50             2.50          NaN   None           NaN      155573            13      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832788, 4832787]  [tmp:05fb8b01-1366-4fc8-9bb4-13c7f6f012a7, tmp:abf67235-1e01-4f8e-a927-95be148ea12f]               ["valqtown", "whqtown(swap names)"]          [nan, nan]    [4832802, 4832801]  [tmp:45d2e796-3ff4-4227-a227-0263a650615c, tmp:72d12c14-20e3-4fa8-9e78-2808beeaf9f9]           ["dixie_j", "driverbrya(swap names)"]          [nan, nan]
22               29145984   4065753          <NA>          <NA>        4        7     -100      100       1D        N             6.00             0.00          NaN   None           NaN      155573            14      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832788, 4832787]  [tmp:05fb8b01-1366-4fc8-9bb4-13c7f6f012a7, tmp:abf67235-1e01-4f8e-a927-95be148ea12f]               ["valqtown", "whqtown(swap names)"]          [nan, nan]    [4832802, 4832801]  [tmp:45d2e796-3ff4-4227-a227-0263a650615c, tmp:72d12c14-20e3-4fa8-9e78-2808beeaf9f9]           ["dixie_j", "driverbrya(swap names)"]          [nan, nan]
23               29145991   4065754          <NA>          <NA>        4        7      620     -620       4H        S             0.50             5.50          NaN   None           NaN      155573            15      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832788, 4832787]  [tmp:05fb8b01-1366-4fc8-9bb4-13c7f6f012a7, tmp:abf67235-1e01-4f8e-a927-95be148ea12f]               ["valqtown", "whqtown(swap names)"]          [nan, nan]    [4832802, 4832801]  [tmp:45d2e796-3ff4-4227-a227-0263a650615c, tmp:72d12c14-20e3-4fa8-9e78-2808beeaf9f9]           ["dixie_j", "driverbrya(swap names)"]          [nan, nan]
24               29145999   4065755          <NA>          <NA>        5        7     -140      140       2S        W             1.00             5.00          NaN   None           NaN      155573            16      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832792, 4832791]                                                                    [5231051, 9311599]  ["Jeff Rowland", "Shirley Campbell(swap names)"]       [56.6, 128.2]    [4832802, 4832801]  [tmp:45d2e796-3ff4-4227-a227-0263a650615c, tmp:72d12c14-20e3-4fa8-9e78-2808beeaf9f9]           ["dixie_j", "driverbrya(swap names)"]          [nan, nan]
...                   ...       ...           ...           ...      ...      ...      ...      ...      ...      ...              ...              ...          ...    ...           ...         ...           ...         ...          ...       ...            ...                       ...             ...        ...                  ...       ...                  ...                   ...                                                                                   ...                                               ...                 ...                   ...                                                                                   ...                                             ...                 ...

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 52788535 entries, 0 to 52788534
Data columns (total 35 columns):
 #   Column                Dtype
---  ------                -----
 0   board_result_id       UInt64
 1   board_id              UInt64
 2   round_number          UInt8
 3   table_number          UInt8
 4   ns_pair               UInt8
 5   ew_pair               UInt8
 6   ns_score              object
 7   ew_score              object
 8   contract              category
 9   declarer              category
 10  ew_match_points       float32
 11  ns_match_points       float32
 12  opening_lead          category
 13  result                object
 14  tricks_taken          float32
 15  section_id            UInt64
 16  board_number          UInt8
 17  session_id            UInt64
 18  section_name          category
 19  event_id              UInt64
 20  hand_record_id        object
 21  game_date             datetime64[ns, US/Central]
 22  club_id_number        UInt64
 23  event_type            category
 24  board_scoring_method  category
 25  tb_count              float32
 26  club_session          category
 27  player_id_ns          object
 28  player_number_ns      object
 29  player_name_ns        object
 30  mp_total_ns           object
 31  player_id_ew          object
 32  player_number_ew      object
 33  player_name_ew        object
 34  mp_total_ew           object
dtypes: UInt64(6), UInt8(5), category(7), datetime64[ns, US/Central](1), float32(4), object(12)
memory usage: 9.8+ GB

In [8]:
# takes 30s
# drop rows where important columns are nulls.
columns_which_must_not_have_nulls = ['contract','declarer','ew_match_points','ns_match_points']
isnulldf = df.isnull()
columns_containing_nulls = isnulldf.columns[isnulldf.any()]
columns_containing_nulls = columns_containing_nulls.intersection(columns_which_must_not_have_nulls) # intersection of null columns and disallowed columns
rows_containing_nulls = df[isnulldf[columns_containing_nulls].any(axis='columns')].index
only_nulls_df = df.loc[rows_containing_nulls][columns_containing_nulls]
only_nulls_df

         contract declarer  ew_match_points  ns_match_points
33           PASS      NaN             1.00             5.00
53            A==      NaN             3.00             3.00
69           PASS      NaN             5.00             1.00
315          PASS      NaN             1.00             7.00
356           A==      NaN             4.00             4.00
457          PASS      NaN             2.50             5.50
526          PASS      NaN             2.50             5.50
534          PASS      NaN             7.00             1.00
542          PASS      NaN             7.00             1.00
564           A-=      NaN             4.00             3.20
668           A==      NaN             4.00             4.00
974           A==      NaN             4.00             4.00
1039         PASS      NaN             4.00             4.00
1062           4C        N              NaN              NaN
1063           4S        E              NaN              NaN
1064           1N        N              NaN              NaN
1065           3C        N              NaN              NaN
1066           3N        N              NaN              NaN
1067           2S        N              NaN              NaN
1068         PASS      NaN              NaN              NaN
1069           5C        E              NaN              NaN
1070           4H        N              NaN              NaN
1071           4S        N              NaN              NaN
1072           5D        S              NaN              NaN
1073           2N        E              NaN              NaN
...           ...      ...              ...              ...
52788486      NaN      NaN             1.50             1.50
52788487      NaN      NaN             0.00             3.00
52788488      NaN      NaN             2.50             0.50
52788489      NaN      NaN             2.50             0.50
52788490      NaN      NaN             0.50             2.50
52788491      NaN      NaN             2.00             1.00
52788492      NaN      NaN             0.50             2.50
52788493      NaN      NaN             0.00             3.00
52788494      NaN      NaN             2.00             1.00
52788495      NaN      NaN             1.50             1.50
52788496      NaN      NaN             1.50             1.50
52788497      NaN      NaN             2.00             1.00
52788498      NaN      NaN             1.00             2.00
52788499      NaN      NaN             2.00             1.00
52788500      NaN      NaN             1.00             2.00
52788501      NaN      NaN             3.00             0.00
52788502      NaN      NaN             2.00             1.00
52788503      NaN      NaN             2.00             1.00
52788504      NaN      NaN             3.00             0.00
52788505      NaN      NaN             0.00             3.00
52788506      NaN      NaN             1.00             2.00
52788507      NaN      NaN             2.00             1.00
52788508      NaN      NaN             3.00             0.00
52788509      NaN      NaN             0.50             2.50
52788510      NaN      NaN             0.50             2.50

[3962822 rows x 4 columns]

In [9]:
# takes 20s
# drop rows containing nulls
df.drop(rows_containing_nulls,inplace=True)

In [10]:
# takes 10s
# todo: earlier in the pipeline, make HandRecord with None into NA so they will be filtered out by NA drop above.
# drop rows, currently 11M, containing non-numeric HandRecords. They're mostly SHUFFLE.
drop_handrecords = ~df['hand_record_id'].str.isnumeric()
df[drop_handrecords]

          board_result_id  board_id  round_number  table_number  ns_pair  ew_pair ns_score ew_score contract declarer  ew_match_points  ns_match_points opening_lead result  tricks_taken  section_id  board_number  session_id section_name  event_id hand_record_id                 game_date  club_id_number event_type board_scoring_method  tb_count       club_session        player_id_ns                                                                      player_number_ns                                    player_name_ns         mp_total_ns        player_id_ew                                                                      player_number_ew                                player_name_ew         mp_total_ew
0                29145890   4065740          <NA>          <NA>        1        1     -140      140       2S        W             4.50             1.50          NaN   None           NaN      155573             1      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832775, 4832776]  [tmp:995300bb-6081-4285-a93a-9342d2e7bc1b, tmp:a659aa2e-1428-4ea4-87d3-581db1c2dfad]                        ["sunfeather", "jakspade"]          [nan, nan]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
1                29145897   4065741          <NA>          <NA>        1        1      650     -650       5H        N             2.50             3.50          NaN   None           NaN      155573             2      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832775, 4832776]  [tmp:995300bb-6081-4285-a93a-9342d2e7bc1b, tmp:a659aa2e-1428-4ea4-87d3-581db1c2dfad]                        ["sunfeather", "jakspade"]          [nan, nan]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
2                29145904   4065742          <NA>          <NA>        1        1      100     -100       3N        W             2.00             4.00          NaN   None           NaN      155573             3      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832775, 4832776]  [tmp:995300bb-6081-4285-a93a-9342d2e7bc1b, tmp:a659aa2e-1428-4ea4-87d3-581db1c2dfad]                        ["sunfeather", "jakspade"]          [nan, nan]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
3                29145956   4065749          <NA>          <NA>        4        1     -140      140       2H        W             3.50             2.50          NaN   None           NaN      155573            10      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832788, 4832787]  [tmp:05fb8b01-1366-4fc8-9bb4-13c7f6f012a7, tmp:abf67235-1e01-4f8e-a927-95be148ea12f]               ["valqtown", "whqtown(swap names)"]          [nan, nan]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
4                29145963   4065750          <NA>          <NA>        4        1      480     -480       4S        S             0.50             5.50          NaN   None           NaN      155573            11      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832788, 4832787]  [tmp:05fb8b01-1366-4fc8-9bb4-13c7f6f012a7, tmp:abf67235-1e01-4f8e-a927-95be148ea12f]               ["valqtown", "whqtown(swap names)"]          [nan, nan]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
5                29145970   4065751          <NA>          <NA>        4        1      -90       90       1N        E             1.00             5.00          NaN   None           NaN      155573            12      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832788, 4832787]  [tmp:05fb8b01-1366-4fc8-9bb4-13c7f6f012a7, tmp:abf67235-1e01-4f8e-a927-95be148ea12f]               ["valqtown", "whqtown(swap names)"]          [nan, nan]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
6                29146000   4065755          <NA>          <NA>        6        1     -620      620       4S        W             5.00             1.00          NaN   None           NaN      155573            16      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832795, 4832796]                                                                    [1015699, 6996043]                  ["Maureen Larson", "Ben Levine"]    [1078.3, 309.88]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
7                29146007   4065756          <NA>          <NA>        6        1     -150      150       2D        N             4.50             1.50          NaN   None           NaN      155573            17      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832795, 4832796]                                                                    [1015699, 6996043]                  ["Maureen Larson", "Ben Levine"]    [1078.3, 309.88]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
8                29146014   4065757          <NA>          <NA>        6        1      100     -100      5DX        W             0.00             6.00          NaN   None           NaN      155573            18      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832795, 4832796]                                                                    [1015699, 6996043]                  ["Maureen Larson", "Ben Levine"]    [1078.3, 309.88]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
9                29145978   4065752          <NA>          <NA>        5        1     -110      110       2S        W             3.50             2.50          NaN   None           NaN      155573            13      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832792, 4832791]                                                                    [5231051, 9311599]  ["Jeff Rowland", "Shirley Campbell(swap names)"]       [56.6, 128.2]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
10               29145985   4065753          <NA>          <NA>        5        1      -50       50       3S        S             3.00             3.00          NaN   None           NaN      155573            14      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832792, 4832791]                                                                    [5231051, 9311599]  ["Jeff Rowland", "Shirley Campbell(swap names)"]       [56.6, 128.2]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
11               29145992   4065754          <NA>          <NA>        5        1     -100      100       4H        S             3.50             2.50          NaN   None           NaN      155573            15      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832792, 4832791]                                                                    [5231051, 9311599]  ["Jeff Rowland", "Shirley Campbell(swap names)"]       [56.6, 128.2]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
12               29145912   4065743          <NA>          <NA>        2        1      660     -660       3N        N             0.00             6.00          NaN   None           NaN      155573             4      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832779, 4832780]                                                                    [4029062, 6694985]                     ["John Perry", "Julie Perry"]  [1161.82, 1034.52]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
13               29145919   4065744          <NA>          <NA>        2        1      170     -170       2S        S             0.00             6.00          NaN   None           NaN      155573             5      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832779, 4832780]                                                                    [4029062, 6694985]                     ["John Perry", "Julie Perry"]  [1161.82, 1034.52]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
14               29145926   4065745          <NA>          <NA>        2        1      140     -140       2H        N             2.50             2.50          NaN   None           NaN      155573             6      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832779, 4832780]                                                                    [4029062, 6694985]                     ["John Perry", "Julie Perry"]  [1161.82, 1034.52]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
15               29145934   4065746          <NA>          <NA>        3        1     -200      200       5C        S             6.00             0.00          NaN   None           NaN      155573             7      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832783, 4832784]                                                                    [2745771, 2745771]                    ["Sandy Pyatt", "Sandy Pyatt"]        [2.41, 2.41]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
16               29145941   4065747          <NA>          <NA>        3        1      170     -170       3H        N             1.50             4.50          NaN   None           NaN      155573             8      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832783, 4832784]                                                                    [2745771, 2745771]                    ["Sandy Pyatt", "Sandy Pyatt"]        [2.41, 2.41]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
17               29145948   4065748          <NA>          <NA>        3        1     -130      130       3D        E             6.00             0.00          NaN   None           NaN      155573             9      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832783, 4832784]                                                                    [2745771, 2745771]                    ["Sandy Pyatt", "Sandy Pyatt"]        [2.41, 2.41]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
18               29145911   4065743          <NA>          <NA>        1        7      620     -620       4H        S             1.00             5.00          NaN   None           NaN      155573             4      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832775, 4832776]  [tmp:995300bb-6081-4285-a93a-9342d2e7bc1b, tmp:a659aa2e-1428-4ea4-87d3-581db1c2dfad]                        ["sunfeather", "jakspade"]          [nan, nan]  [4832802, 4832801]  [tmp:45d2e796-3ff4-4227-a227-0263a650615c, tmp:72d12c14-20e3-4fa8-9e78-2808beeaf9f9]         ["dixie_j", "driverbrya(swap names)"]          [nan, nan]
19               29145918   4065744          <NA>          <NA>        1        7     -200      200       4H        N             5.00             1.00          NaN   None           NaN      155573             5      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832775, 4832776]  [tmp:995300bb-6081-4285-a93a-9342d2e7bc1b, tmp:a659aa2e-1428-4ea4-87d3-581db1c2dfad]                        ["sunfeather", "jakspade"]          [nan, nan]  [4832802, 4832801]  [tmp:45d2e796-3ff4-4227-a227-0263a650615c, tmp:72d12c14-20e3-4fa8-9e78-2808beeaf9f9]         ["dixie_j", "driverbrya(swap names)"]          [nan, nan]
20               29145925   4065745          <NA>          <NA>        1        7      400     -400       2S        W             0.00             5.00          NaN   None           NaN      155573             6      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832775, 4832776]  [tmp:995300bb-6081-4285-a93a-9342d2e7bc1b, tmp:a659aa2e-1428-4ea4-87d3-581db1c2dfad]                        ["sunfeather", "jakspade"]          [nan, nan]  [4832802, 4832801]  [tmp:45d2e796-3ff4-4227-a227-0263a650615c, tmp:72d12c14-20e3-4fa8-9e78-2808beeaf9f9]         ["dixie_j", "driverbrya(swap names)"]          [nan, nan]
21               29145977   4065752          <NA>          <NA>        4        7     -110      110       1S        W             3.50             2.50          NaN   None           NaN      155573            13      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832788, 4832787]  [tmp:05fb8b01-1366-4fc8-9bb4-13c7f6f012a7, tmp:abf67235-1e01-4f8e-a927-95be148ea12f]               ["valqtown", "whqtown(swap names)"]          [nan, nan]  [4832802, 4832801]  [tmp:45d2e796-3ff4-4227-a227-0263a650615c, tmp:72d12c14-20e3-4fa8-9e78-2808beeaf9f9]         ["dixie_j", "driverbrya(swap names)"]          [nan, nan]
22               29145984   4065753          <NA>          <NA>        4        7     -100      100       1D        N             6.00             0.00          NaN   None           NaN      155573            14      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832788, 4832787]  [tmp:05fb8b01-1366-4fc8-9bb4-13c7f6f012a7, tmp:abf67235-1e01-4f8e-a927-95be148ea12f]               ["valqtown", "whqtown(swap names)"]          [nan, nan]  [4832802, 4832801]  [tmp:45d2e796-3ff4-4227-a227-0263a650615c, tmp:72d12c14-20e3-4fa8-9e78-2808beeaf9f9]         ["dixie_j", "driverbrya(swap names)"]          [nan, nan]
23               29145991   4065754          <NA>          <NA>        4        7      620     -620       4H        S             0.50             5.50          NaN   None           NaN      155573            15      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832788, 4832787]  [tmp:05fb8b01-1366-4fc8-9bb4-13c7f6f012a7, tmp:abf67235-1e01-4f8e-a927-95be148ea12f]               ["valqtown", "whqtown(swap names)"]          [nan, nan]  [4832802, 4832801]  [tmp:45d2e796-3ff4-4227-a227-0263a650615c, tmp:72d12c14-20e3-4fa8-9e78-2808beeaf9f9]         ["dixie_j", "driverbrya(swap names)"]          [nan, nan]
24               29145999   4065755          <NA>          <NA>        5        7     -140      140       2S        W             1.00             5.00          NaN   None           NaN      155573            16      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832792, 4832791]                                                                    [5231051, 9311599]  ["Jeff Rowland", "Shirley Campbell(swap names)"]       [56.6, 128.2]  [4832802, 4832801]  [tmp:45d2e796-3ff4-4227-a227-0263a650615c, tmp:72d12c14-20e3-4fa8-9e78-2808beeaf9f9]         ["dixie_j", "driverbrya(swap names)"]          [nan, nan]
...                   ...       ...           ...           ...      ...      ...      ...      ...      ...      ...              ...              ...          ...    ...           ...         ...           ...         ...          ...       ...            ...                       ...             ...        ...                  ...       ...                ...                 ...                                                                                   ...                                               ...                 ...                 ...                                                                                   ...                                           ...                 ...
52788438         18003486   2534565             3             4        4        2    -1010     1010      6 S        E             6.00             0.00                  +1         13.00       95017            18       77730            A     77723        SHUFFLE 2020-01-18 00:00:00-06:00          905513      PAIRS         MATCH_POINTS      7.50   Saturday Morning  [2928198, 2928199]                                                                    [1367110, 3105105]            ["Viola III, Joseph", "Elghamry, Amr"]  [6046.95, 5116.12]  [2928208, 2928209]                                                                    [5564697, 9269347]          ["Osmundson, Avice", "Kumar, Kiran"]  [1960.84, 1487.48]

In [11]:
df['hand_record_id'][drop_handrecords].value_counts()

None       8428255
SHUFFLE    2821128
              1540
Name: hand_record_id, dtype: int64

In [12]:
df['board_number'][drop_handrecords].value_counts()

1     592669
2     590463
3     575148
4     566186
5     551589
6     546848
7     539309
8     538218
9     534645
10    534531
11    532295
17    529430
12    528319
18    526545
13    522996
14    522200
16    522186
15    521247
19    224274
20    223650
21    199906
22    151065
23    135705
24    135299
25     86329
26     82606
27     68237
28     46893
29     31227
30     31196
31     17130
32     17110
33     11688
34      5061
35      3882
36      3874
38       207
37       207
39       183
40        67
41        66
42        66
43        44
44        44
45        44
46        13
47        13
48        13
Name: board_number, dtype: Int64

In [13]:
# takes 22s
df.drop(df[drop_handrecords].index,inplace=True)

In [14]:
# takes 6s
assert df['hand_record_id'].str.isnumeric().all()
# already int - assert df['board_number'].str.isnumeric().all()
# already int - assert df['board_id'].str.isnumeric().all()

In [15]:
# takes 17s
acbl_hand_records_cleaned_filename = 'acbl_hand_records_cleaned.pkl'
acbl_hand_records_cleaned_file = acblPath.joinpath(acbl_hand_records_cleaned_filename)
acbl_hrdf = pd.read_pickle(acbl_hand_records_cleaned_file)
acbl_hrdf

                     ref hand_record_id  event_id Board  EventBoard Dealer   Vul                                                   board_record_string                                                                                         Hands                                                                Par                                                                         DDmakes
0        (acbl, 2620401)          77908    100961    09  200217A_09      N   E_W  ST6HK32DJ2CAJ9874SQJ942H765DT874CQSA853HQDKQ963CK52SK7HAJT984DA5CT63  ((T6, K32, J2, AJ9874), (A853, Q, KQ963, K52), (K7, AJT984, A5, T63), (QJ942, 765, T874, Q))                                         (200, [(4, S, *, EW, -1)])        ((10, 4, 10, 4, 8), (2, 9, 3, 9, 2), (10, 4, 10, 4, 8), (2, 9, 3, 9, 2))
1        (acbl, 2620412)          77908    100961    20  200217A_20      W  Both  ST85HKJDJ43CKJ873SQ32HA643DK96CT94SAJ64HT98DT75CA52SK97HQ752DAQ82CQ6  ((T85, KJ, J43, KJ873), (AJ64, T98, T75, A52), (K97, Q752, AQ82, Q6), (Q32, A643, K96, T94))          (90, [(1, D, , NS, 1), (1, C, , NS, 1), (1, N, , NS, 0)])            ((8, 8, 7, 7, 7), (4, 5, 6, 6, 6), (8, 8, 7, 7, 7), (4, 5, 6, 6, 6))
2        (acbl, 2620411)          77908    100961    19  200217A_19      S   E_W  STH764DAQ92CQJ653SQJ763HKJTD65CAKTSK984H5DT8743C987SA52HAQ9832DKJC42  ((T, 764, AQ92, QJ653), (K984, 5, T8743, 987), (A52, AQ9832, KJ, 42), (QJ763, KJT, 65, AKT))                                           (140, [(3, H, , NS, 0)])            ((9, 7, 9, 4, 6), (4, 6, 3, 8, 6), (9, 7, 9, 5, 6), (4, 6, 3, 8, 6))
3        (acbl, 2620420)          77908    100961    28  200217A_28      W   N_S  STHQJ9632DJ9CJ932SKQH8DQT86542CT76SJ76HATDAK3CAKQ84SA985432HK754D7C5  ((T, QJ9632, J9, J932), (J76, AT, AK3, AKQ84), (A985432, K754, 7, 5), (KQ, 8, QT86542, T76))                                          (-460, [(5, N, , EW, 0)])    ((1, 0, 10, 8, 1), (11, 11, 3, 5, 11), (0, 0, 10, 8, 0), (11, 11, 3, 5, 11))
4        (acbl, 2620399)          77908    100961    07  200217A_07      S  Both  S2HQT762D92CAKT92SAKJ7HA8DKJ4C8643SQT854HK43DA765CQS963HJ95DQT83CJ75  ((2, QT762, 92, AKT92), (QT854, K43, A765, Q), (963, J95, QT83, J75), (AKJ7, A8, KJ4, 8643))                                         (-1430, [(6, S, , EW, 0)])        ((6, 2, 6, 1, 3), (7, 11, 6, 12, 8), (6, 2, 6, 1, 3), (7, 11, 6, 12, 8))
5        (acbl, 2620396)          77908    100961    04  200217A_04      W  Both  S84HAKJ83D4CQT743SA65HQ62DQ8732CK8SJ972HT5DAKJ96C95SKQT3H974DT5CAJ62  ((84, AKJ83, 4, QT743), (J972, T5, AKJ96, 95), (KQT3, 974, T5, AJ62), (A65, Q62, Q8732, K8))                                           (620, [(4, H, , NS, 0)])        ((10, 5, 10, 6, 6), (3, 8, 3, 6, 6), (10, 5, 10, 6, 6), (3, 8, 3, 6, 6))
6        (acbl, 2620410)          77908    100961    18  200217A_18      E   N_S  S872HJ8753DQ873CASAJ65HQ4DAKJ4C874S93HAK6D962CQT963SKQT4HT92DT5CKJ52  ((872, J8753, Q873, A), (93, AK6, 962, QT963), (KQT4, T92, T5, KJ52), (AJ65, Q4, AKJ4, 874))                                          (-120, [(1, N, , EW, 1)])            ((4, 4, 5, 5, 5), (9, 8, 7, 7, 8), (4, 5, 5, 5, 5), (9, 8, 7, 7, 8))
7        (acbl, 2620400)          77908    100961    08  200217A_08      W  None  S953H98642DJ9CKJ5SAJT6HAJ3DT2CAT96S742HKQ7DK764CQ43SKQ8HT5DAQ853C872  ((953, 98642, J9, KJ5), (742, KQ7, K764, Q43), (KQ8, T5, AQ853, 872), (AJT6, AJ3, T2, AT96))                                           (-140, [(1, S, , E, 2)])            ((4, 6, 6, 4, 5), (8, 7, 7, 9, 8), (4, 6, 6, 4, 5), (8, 7, 7, 8, 8))
8        (acbl, 2620397)          77908    100961    05  200217A_05      N   N_S  S98HAKT83D84CAQ82SQJHQJ65DT2CJ7653SAK752H72DAK96CKTST643H94DQJ753C94  ((98, AKT83, 84, AQ82), (AK752, 72, AK96, KT), (T643, 94, QJ753, 94), (QJ, QJ65, T2, J7653))                                          (-120, [(2, N, , EW, 0)])            ((5, 6, 7, 4, 5), (7, 7, 6, 8, 8), (5, 6, 7, 4, 5), (7, 7, 6, 8, 8))
9        (acbl, 2620398)          77908    100961    06  200217A_06      E   E_W  SA53HJT8DQ8743CQ9SKQJT87H954DJCA62S94HAQ62DAT965C54S62HK73DK2CKJT873  ((A53, JT8, Q8743, Q9), (94, AQ62, AT965, 54), (62, K73, K2, KJT873), (KQJT87, 954, J, A62))                                          (-140, [(2, S, , EW, 1)])            ((7, 6, 5, 4, 5), (5, 7, 8, 9, 5), (7, 6, 5, 4, 5), (5, 7, 8, 9, 5))
10       (acbl, 2620418)          77908    100961    26  200217A_26      E  Both  SA53HQ652DAKT4CJ3SQT6H9743DQ632CATSK98HAJT8D875C985SJ742HKDJ9CKQ7642  ((A53, Q652, AKT4, J3), (K98, AJT8, 875, 985), (J742, K, J9, KQ7642), (QT6, 9743, Q632, AT))                                           (140, [(1, S, , NS, 2)])            ((9, 7, 6, 9, 7), (3, 6, 6, 4, 5), (9, 7, 6, 9, 7), (3, 6, 6, 4, 5))
11       (acbl, 2620415)          77908    100961    23  200217A_23      S  Both  SA62H53DAJ93C8653SK983HAK94DT6CQT4SJT4HJ62DQ52CAJ72SQ75HQT87DK874CK9  ((A62, 53, AJ93, 8653), (JT4, J62, Q52, AJ72), (Q75, QT87, K874, K9), (K983, AK94, T6, QT4))                                             (90, [(2, D, , S, 0)])            ((5, 7, 6, 5, 6), (8, 5, 7, 7, 7), (6, 8, 6, 6, 6), (7, 5, 7, 7, 7))
12       (acbl, 2620414)          77908    100961    22  200217A_22      E   E_W  SA953HQTDAK652CQJSJ876HJ632D8CKT86SQHA9875DJ43CA974SKT42HK4DQT97C532  ((A953, QT, AK652, QJ), (Q, A9875, J43, A974), (KT42, K4, QT97, 532), (J876, J632, 8, KT86))  (-300, [(5, D, *, NS, -2), (4, S, *, NS, -2), (4, N, *, NS, -2)])          ((3, 9, 3, 8, 8), (9, 4, 10, 4, 5), (3, 9, 3, 8, 8), (9, 4, 10, 4, 5))
13       (acbl, 2620404)          77908    100961    12  200217A_12      W   N_S  SAJ63HJ8DAK2CQ765SK54H43DQJ97CAT32S87HK9765D84CKJ94SQT92HAQT2DT653C8  ((AJ63, J8, AK2, Q765), (87, K9765, 84, KJ94), (QT92, AQT2, T653, 8), (K54, 43, QJ97, AT32))                                           (650, [(4, S, , NS, 1)])        ((7, 10, 8, 11, 9), (6, 3, 5, 2, 4), (7, 10, 8, 11, 9), (6, 3, 5, 2, 4))
14       (acbl, 2620408)          77908    100961    16  200217A_16      W   E_W  SAKT9754H842D5CA2S63H763DA8742CQ76S2HAQJTDJ963CKT54SQJ8HK95DKQTCJ983  ((AKT9754, 842, 5, A2), (2, AQJT, J963, KT54), (QJ8, K95, KQT, J983), (63, 763, A8742, Q76))                                           (420, [(4, S, , NS, 0)])          ((7, 5, 7, 10, 9), (6, 8, 6, 2, 3), (7, 5, 7, 10, 9), (6, 8, 6, 2, 3))
15       (acbl, 2620393)          77908    100961    01  200217A_01      N  None  SAK73HQ93DT53CA32S2HA2DKQJ872CQJ64SQ5HKJ84D964CKT85SJT9864HT765DAC97  ((AK73, Q93, T53, A32), (Q5, KJ84, 964, KT85), (JT9864, T765, A, 97), (2, A2, KQJ872, QJ64))                                        (-100, [(4, S, *, NS, -1)])          ((4, 2, 6, 9, 8), (9, 10, 6, 4, 5), (4, 2, 6, 9, 8), (9, 10, 6, 4, 5))
16       (acbl, 2620413)          77908    100961    21  200217A_21      N   N_S  SJ3H642DAK83CAJ75SAQ4HKQJ8DJ54CKT8ST652H9DT962CQ964SK987HAT753DQ7C32  ((J3, 642, AK83, AJ75), (T652, 9, T962, Q964), (K987, AT753, Q7, 32), (AQ4, KQJ8, J54, KT8))                                         (100, [(2, N, *, EW, -1)])            ((5, 6, 7, 7, 6), (7, 7, 5, 6, 7), (6, 6, 8, 7, 6), (7, 7, 5, 6, 7))
17       (acbl, 2620402)          77908    100961    10  200217A_10      E  Both  SJ854HA87DKT7CK72S2HK963DAQ6CAJ653S973HQT54DJ532CT9SAKQT6HJ2D984CQ84  ((J854, A87, KT7, K72), (973, QT54, J532, T9), (AKQT6, J2, 984, Q84), (2, K963, AQ6, AJ653))                                          (-140, [(3, H, , EW, 0)])            ((5, 5, 4, 8, 8), (7, 7, 9, 5, 5), (5, 6, 4, 8, 8), (7, 7, 9, 5, 5))
18       (acbl, 2620407)          77908    100961    15  200217A_15      S   N_S  SKT5HQ73DAT96CQ62SAQ83HA96DK4CKT97S9762HKJ42DQ8CJ83SJ4HT85DJ7532CA54  ((KT5, Q73, AT96, Q62), (9762, KJ42, Q8, J83), (J4, T85, J7532, A54), (AQ83, A96, K4, KT97))                         (-110, [(2, S, , EW, 0), (2, H, , EW, 0)])            ((5, 7, 5, 5, 6), (8, 6, 8, 8, 7), (5, 7, 5, 5, 6), (8, 6, 8, 8, 7))
19       (acbl, 2620416)          77908    100961    24  200217A_24      W  None  SK732H95DAK54CQJ6SA54HKQ7DJ96CKT85SQ96HAJ432DQT72C4SJT8HT86D83CA9732  ((K732, 95, AK54, QJ6), (Q96, AJ432, QT72, 4), (JT8, T86, 83, A9732), (A54, KQ7, J96, KT85))                                          (-120, [(2, N, , EW, 0)])            ((7, 4, 4, 6, 4), (6, 8, 8, 7, 8), (7, 4, 4, 6, 4), (6, 8, 8, 7, 8))
20       (acbl, 2620403)          77908    100961    11  200217A_11      S  None  SK73HAK2DJ95CKT94S542HJT85D7432C83S6HQ963DKQT86CQJ7SAQJT98H74DACA652  ((K73, AK2, J95, KT94), (6, Q963, KQT86, QJ7), (AQJT98, 74, A, A652), (542, JT85, 7432, 83))                                           (990, [(6, N, , NS, 0)])      ((12, 6, 7, 12, 12), (1, 7, 5, 1, 1), (12, 6, 7, 12, 12), (1, 7, 5, 1, 1))
21       (acbl, 2620395)          77908    100961    03  200217A_03      S   E_W  SK75HK3DKQT852C52SJT63HAT2DJ64CKQTS98HJ9875DA7CA964SAQ42HQ64D93CJ873  ((K75, K3, KQT852, 52), (98, J9875, A7, A964), (AQ42, Q64, 93, J873), (JT63, AT2, J64, KQT))                                           (110, [(3, D, , NS, 0)])            ((5, 9, 4, 7, 5), (7, 4, 8, 6, 5), (5, 9, 4, 7, 5), (7, 4, 8, 6, 5))
22       (acbl, 2620419)          77908    100961    27  200217A_27      S  None  SKHAQ7653DKQ54CKQSJT97HJ42DJ63C653SQ32HKT8DT97CT842SA8654H9DA82CAJ97  ((K, AQ7653, KQ54, KQ), (Q32, KT8, T97, T842), (A8654, 9, A82, AJ97), (JT97, J42, J63, 653))                                          (1440, [(7, D, , NS, 0)])  ((11, 13, 11, 11, 11), (1, 0, 2, 2, 2), (11, 13, 11, 11, 11), (1, 0, 2, 2, 2))
23       (acbl, 2620406)          77908    100961    14  200217A_14      E  None  SQT93HJ73DJ87CQ53S872H5DAKQ92CJT74SA4HKQ864D543CAK9SKJ65HAT92DT6C862  ((QT93, J73, J87, Q53), (A4, KQ864, 543, AK9), (KJ65, AT92, T6, 862), (872, 5, AKQ92, JT74))                                          (-430, [(3, N, , EW, 1)])      ((1, 2, 4, 5, 2), (10, 11, 9, 7, 10), (1, 2, 4, 5, 2), (10, 11, 9, 7, 10))
24       (acbl, 2620409)          77908    100961    17  200217A_17      N  None  SQ6HJT852DA96CA87SA5HQ97DKJ82CKJ42SJ84H63DQT54CQT93SKT9732HAK4D73C65  ((Q6, JT852, A96, A87), (J84, 63, QT54, QT93), (KT9732, AK4, 73, 65), (A5, Q97, KJ82, KJ42))                                           (400, [(3, N, , NS, 0)])            ((5, 5, 9, 9, 9), (7, 7, 3, 3, 4), (5, 5, 9, 9, 9), (7, 7, 3, 3, 4))
...                  ...            ...       ...   ...         ...    ...   ...                                                                   ...                                                                                           ...                                                                ...                                                                             ...
3361142  (acbl, 1651709)          49239     60806    09  191220A_09      N   E_W  S65HQDK432CA98642SAJT2HAT93DT6CT73SK973HK87654DQ85CSQ84HJ2DAJ97CKQJ5  ((65, Q, K432, A98642), (K973, K87654, Q85, ), (Q84, J2, AJ97, KQJ5), (AJT2, AT93, T6, T73))                                        (-300, [(6, C, *, NS, -2)])      ((10, 7, 2, 1, 3), (3, 2, 11, 11, 3), (10, 7, 2, 1, 3), (3, 2, 11, 11, 3))
3361143  (acbl, 1651716)          49239     60806    16  191220A_16      W   E_W  SA853HK82DK53C983SKQT4H7D9762CQJT7SJ7HQJ4DAQJT8CA42S962HAT9653D4CK65  ((A853, K82, K53, 983), (J7, QJ4, AQJT8, A42), (962, AT9653, 4, K65), (KQT4, 7, 9762, QJT7))                                          (-130, [(3, D, , EW, 1)])          ((4, 3, 7, 5, 4), (9, 10, 6, 7, 7), (4, 3, 7, 5, 4), (9, 10, 6, 7, 7))
3361144  (acbl, 1651719)          49239     60806    19  191220A_19      S   E_W  SA9HA43DT54CKJ943SKJ865HJ7DAK63CQ7SQ32HQT98652D92CAST74HKDQJ87CT8652  ((A9, A43, T54, KJ943), (Q32, QT98652, 92, A), (T74, K, QJ87, T8652), (KJ865, J7, AK63, Q7))                                        (-100, [(4, C, *, NS, -1)])            ((9, 7, 3, 4, 6), (4, 6, 9, 8, 6), (9, 7, 3, 4, 6), (4, 6, 9, 8, 6))
3361145  (acbl, 1651722)          49239     60806    22  191220A_22      E   E_W  S763HA982D975CA52SQ92HKQJ4DAKJ2CKTSAT5HT7DT84CJ8743SKJ84H653DQ63CQ96  ((763, A982, 975, A52), (AT5, T7, T84, J8743), (KJ84, 653, Q63, Q96), (Q92, KQJ4, AKJ2, KT))                                          (-600, [(3, N, , EW, 0)])          ((3, 3, 4, 4, 4), (9, 10, 9, 8, 9), (3, 3, 4, 4, 4), (9, 10, 9, 8, 9))
3361146  (acbl, 1651725)          49239     60806    25  191220A_25      N   E_W  S7HKQ73DAJ654C532SJT862HA865DKCT98S54HT4D83CAKQJ764SAKQ93HJ92DQT972C  ((7, KQ73, AJ654, 532), (54, T4, 83, AKQJ764), (AKQ93, J92, QT972, ), (JT862, A865, K, T98))                                           (920, [(6, D, , NS, 0)])        ((4, 12, 10, 9, 5), (9, 1, 2, 4, 5), (4, 12, 10, 9, 5), (9, 1, 2, 4, 5))
3361147  (acbl, 1651732)          49239     60806    32  191220A_32      W   E_W  S9843HJ4DQ65CQT94SJ5HKT95D9872CJ63SAQT72H87DKTCAK82SK6HAQ632DAJ43C75  ((9843, J4, Q65, QT94), (AQT72, 87, KT, AK82), (K6, AQ632, AJ43, 75), (J5, KT95, 9872, J63))                                        (-100, [(3, H, *, NS, -1)])            ((5, 7, 8, 5, 6), (7, 6, 5, 8, 6), (5, 7, 8, 5, 6), (7, 6, 5, 8, 6))
3361148  (acbl, 1651735)          49239     60806    35  191220A_35      S   E_W  SAHT732DJ54CK7642SJ852HKDAQT96CAT5SKQ43HA8654DK87C3ST976HQJ9D32CQJ98  ((A, T732, J54, K7642), (KQ43, A8654, K87, 3), (T976, QJ9, 32, QJ98), (J852, K, AQT96, AT5))                                       (-1400, [(7, C, *, NS, -6)])        ((7, 1, 3, 1, 2), (6, 12, 9, 12, 9), (7, 1, 3, 1, 2), (6, 12, 9, 12, 9))
3361149  (acbl, 1651701)          49239     60806    01  191220A_01      N  None  SAQJ74HJ5DKJT2CQJSK9862HQ862DA9C75STHK943DQ853CK983S53HAT7D764CAT642  ((AQJ74, J5, KJT2, QJ), (T, K943, Q853, K983), (53, AT7, 764, AT642), (K9862, Q862, A9, 75))                                           (120, [(2, N, , NS, 0)])            ((9, 8, 6, 8, 8), (4, 5, 6, 4, 4), (9, 8, 6, 8, 8), (4, 5, 7, 5, 5))
3361150  (acbl, 1651708)          49239     60806    08  191220A_08      W  None  SAJT95HADJ5CQT654SK732HQT9DAQ72CJ3S86HK653DKT93CK82SQ4HJ8742D864CA97  ((AJT95, A, J5, QT654), (86, K653, KT93, K82), (Q4, J8742, 864, A97), (K732, QT9, AQ72, J3))                                           (140, [(3, S, , NS, 0)])          ((10, 4, 6, 9, 5), (3, 8, 7, 4, 5), (10, 4, 6, 9, 5), (3, 8, 7, 4, 5))
3361151  (acbl, 1651711)          49239     60806    11  191220A_11      S  None  S52H3DA643CAT9643SQT987HK64DQ95CQ7SJ4HT72DKT872CJ82SAK63HAQJ985DJCK5  ((52, 3, A643, AT9643), (J4, T72, KT872, J82), (AK63, AQJ985, J, K5), (QT987, K64, Q95, Q7))                                           (920, [(6, C, , NS, 0)])    ((12, 8, 10, 10, 10), (1, 5, 3, 3, 3), (12, 8, 10, 10, 10), (1, 5, 3, 3, 3))
3361152  (acbl, 1651714)          49239     60806    14  191220A_14      E  None  SA73H983DA94CAT52SJ5HA64DKQ752C876SK94HQJT75D8CKQ93SQT862HK2DJT63CJ4  ((A73, 983, A94, AT52), (K94, QJT75, 8, KQ93), (QT862, K2, JT63, J4), (J5, A64, KQ752, 876))                                          (-140, [(3, H, , EW, 0)])            ((5, 5, 4, 7, 5), (8, 7, 9, 5, 8), (4, 5, 4, 7, 5), (8, 7, 9, 5, 8))
3361153  (acbl, 1651717)          49239     60806    17  191220A_17      N  None  SA5HQ5DKQJT6CQ987ST874HAKT8DACJ543S9632H643D9753CK2SKQJHJ972D842CAT6  ((A5, Q5, KQJT6, Q987), (9632, 643, 9753, K2), (KQJ, J972, 842, AT6), (T874, AKT8, A, J543))                                           (400, [(3, N, , NS, 0)])            ((8, 9, 8, 7, 9), (4, 3, 5, 6, 4), (8, 9, 8, 7, 9), (4, 3, 5, 6, 4))
3361154  (acbl, 1651724)          49239     60806    24  191220A_24      W  None  S82H4DT73CKQJ7432SQJT9HQT6DAJ982CTSA543HK98DKQ65C86SK76HAJ7532D4CA95  ((82, 4, T73, KQJ7432), (A543, K98, KQ65, 86), (K76, AJ7532, 4, A95), (QJT9, QT6, AJ982, T))                                           (400, [(5, C, , NS, 0)])          ((11, 3, 7, 3, 7), (1, 8, 5, 8, 5), (11, 3, 7, 3, 7), (1, 8, 5, 8, 5))
3361155  (acbl, 1651727)          49239     60806    27  191220A_27      S  None  SKJT743HKDT862CAJS986HQ962DAJ9CT76S5HJT743D7543CK42SAQ2HA85DKQCQ9853  ((KJT743, K, T862, AJ), (5, JT743, 7543, K42), (AQ2, A85, KQ, Q9853), (986, Q962, AJ9, T76))                                           (980, [(6, S, , NS, 0)])      ((10, 8, 7, 12, 10), (2, 3, 6, 1, 2), (10, 8, 7, 12, 10), (2, 3, 6, 1, 2))
3361156  (acbl, 1651730)          49239     60806    30  191220A_30      E  None  S874HAJ5DQJ9843C4SKQ953HQT86DA62C7SAT62H42DK5CKQT65SJHK973DT7CAJ9832  ((874, AJ5, QJ9843, 4), (AT62, 42, K5, KQT65), (J, K973, T7, AJ9832), (KQ953, QT86, A62, 7))                                          (-140, [(3, S, , EW, 0)])            ((6, 8, 6, 3, 5), (6, 5, 6, 9, 8), (6, 8, 6, 4, 5), (6, 5, 6, 9, 8))
3361157  (acbl, 1651733)          49239     60806    33  191220A_33      N  None  ST85HJ92DQ7CQJT87SAK6HK75DKJ84CK32SQ97432H43DATCA96SJHAQT86D96532C54  ((T85, J92, Q7, QJT87), (Q97432, 43, AT, A96), (J, AQT86, 96532, 54), (AK6, K75, KJ84, K32))                                          (-990, [(6, N, , EW, 0)])        ((4, 2, 4, 1, 1), (9, 9, 7, 12, 12), (4, 2, 5, 1, 1), (9, 9, 7, 12, 12))
3361158  (acbl, 1651702)          49239     60806    02  191220A_02      E   N_S  SKQJ6HAKJ7DA872C7ST82H963DKT6CT954SA97543HTD4CAQJ63SHQ8542DQJ953CK82  ((KQJ6, AKJ7, A872, 7), (A97543, T, 4, AQJ63), (, Q8542, QJ953, K82), (T82, 963, KT6, T954))                                           (650, [(5, H, , NS, 0)])        ((6, 11, 11, 6, 8), (7, 2, 2, 7, 3), (6, 11, 11, 6, 8), (7, 2, 2, 7, 3))
3361159  (acbl, 1651705)          49239     60806    05  191220A_05      N   N_S  SJ8HT3DQT984CJT63SKT7HKQ5DKJCAK852S9532HA9862D72CQ4SAQ64HJ74DA653C97  ((J8, T3, QT984, JT63), (9532, A9862, 72, Q4), (AQ64, J74, A653, 97), (KT7, KQ5, KJ, AK852))                                          (-420, [(4, H, , EW, 0)])          ((3, 7, 2, 4, 3), (9, 6, 10, 9, 9), (3, 7, 2, 4, 3), (9, 6, 10, 9, 9))
3361160  (acbl, 1651712)          49239     60806    12  191220A_12      W   N_S  ST6HKT5DAQJT8CJ53S9432HA432D64CA96S5HQ9876DK932CT87SAKQJ87HJD75CKQ42  ((T6, KT5, AQJT8, J53), (5, Q9876, K932, T87), (AKQJ87, J, 75, KQ42), (9432, A432, 64, A96))                                           (620, [(4, S, , NS, 0)])         ((10, 9, 6, 10, 8), (3, 3, 7, 2, 3), (9, 9, 5, 10, 8), (3, 3, 7, 2, 3))
3361161  (acbl, 1651715)          49239     60806    15  191220A_15      S   N_S  SJ4H9875DJ752C862SAQ5HQT432DAK3CAJS98632HAKD84CQT93SKT7HJ6DQT96CK754  ((J4, 9875, J752, 862), (98632, AK, 84, QT93), (KT7, J6, QT96, K754), (AQ5, QT432, AK3, AJ))                                          (-990, [(6, N, , EW, 0)])    ((1, 4, 1, 1, 1), (12, 9, 11, 12, 12), (1, 4, 2, 1, 1), (12, 9, 11, 12, 12))
3361162  (acbl, 1651718)          49239     60806    18  191220A_18      E   N_S  SA5432H93D743C873SK87HQJT764DK98CJSJT9H852DAJTCA962SQ6HAKDQ652CKQT54  ((A5432, 93, 743, 873), (JT9, 852, AJT, A962), (Q6, AK, Q652, KQT54), (K87, QJT764, K98, J))                                          (-420, [(4, H, , EW, 0)])          ((7, 6, 3, 6, 5), (5, 6, 10, 7, 6), (7, 7, 3, 6, 5), (5, 6, 10, 7, 6))
3361163  (acbl, 1651721)          49239     60806    21  191220A_21      N   N_S  SJT9643HKJ2D54CQ5SAHA984DAQ973CT43S72HQT5DKJT8CAJ72SKQ85H763D62CK986  ((JT9643, KJ2, 54, Q5), (72, QT5, KJT8, AJ72), (KQ85, 763, 62, K986), (A, A984, AQ973, T43))                                          (-420, [(4, H, , EW, 0)])        ((4, 2, 2, 7, 3), (9, 11, 10, 6, 8), (4, 2, 2, 7, 3), (9, 11, 10, 6, 8))
3361164  (acbl, 1651728)          49239     60806    28  191220A_28      W   N_S  SKJ5HA97DK432CQ43SA763H4DT76CAKJ52SQT98H53DA98CT976S42HKQJT862DQJ5C8  ((KJ5, A97, K432, Q43), (QT98, 53, A98, T976), (42, KQJT862, QJ5, 8), (A763, 4, T76, AKJ52))                                         (300, [(4, S, *, EW, -2)])          ((5, 8, 10, 5, 8), (8, 4, 3, 8, 4), (5, 8, 10, 5, 8), (8, 4, 3, 8, 4))
3361165  (acbl, 1651731)          49239     60806    31  191220A_31      S   N_S  S3HQT764DKT74CK92S2HA92DQJ985CJT54SAKQ4HJ53DA32CA63SJT98765HK8D6CQ87  ((3, QT764, KT74, K92), (AKQ4, J53, A32, A63), (JT98765, K8, 6, Q87), (2, A92, QJ985, JT54))                                          (-120, [(1, N, , EW, 1)])            ((4, 4, 6, 6, 5), (9, 9, 7, 7, 8), (4, 4, 6, 6, 4), (8, 9, 7, 7, 8))

In [16]:
# takes 2s
assert acbl_hrdf['hand_record_id'].str.isnumeric().all()
assert acbl_hrdf['Board'].str.isnumeric().all()
assert all([type(t) is tuple and len(t) == 2 for t in acbl_hrdf['Par']])
assert all([type(t[0]) is int for t in acbl_hrdf['Par']])

In [17]:
acbl_hrdf[(acbl_hrdf['hand_record_id'] == '1') & (acbl_hrdf['Board'] == '01')]

               ref hand_record_id  event_id Board  EventBoard Dealer   Vul                                                   board_record_string                                                                                         Hands                        Par                                                                   DDmakes
1872111  (acbl, 1)              1         3    01  181001A_01      N  None  S94H765DAJ762CK94SA5HAKQT3DQ43CQ76SK72H942DT9CAT832SQJT863HJ8DK85CJ5  ((94, 765, AJ762, K94), (K72, 942, T9, AT832), (QJT863, J8, K85, J5), (A5, AKQT3, Q43, Q76))  (-420, [(4, H, , EW, 0)])  ((3, 6, 3, 6, 5), (10, 6, 10, 5, 8), (3, 6, 3, 6, 5), (10, 6, 10, 5, 8))

In [18]:
1518827 in acbl_hrdf.index

True

In [19]:
# takes 10s
# todo: 24m board_ids not found in hand records table. Why is that? SHUFFLE?
missing_board_ids = ~df['board_id'].isin(acbl_hrdf.index)
df[missing_board_ids]

          board_result_id  board_id  round_number  table_number  ns_pair  ew_pair ns_score ew_score contract declarer  ew_match_points  ns_match_points opening_lead result  tricks_taken  section_id  board_number  session_id section_name  event_id hand_record_id                 game_date  club_id_number event_type board_scoring_method  tb_count       club_session          player_id_ns    player_number_ns                                        player_name_ns         mp_total_ns          player_id_ew    player_number_ew                                  player_name_ew       mp_total_ew
2255             37205244   5024242          <NA>          <NA>        6        6      100     -100       3H        E             1.00             5.00          NaN   None           NaN      205576             1      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening    [6520104, 6520105]  [1407953, 2536919]                      ["Cheryl Smith", "Ruth Whitney"]       [8.01, 21.11]    [6520106, 6520107]  [7593422, 8880387]                   ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2256             37205251   5024243          <NA>          <NA>        6        6      140     -140       2H        S             2.00             4.00          NaN   None           NaN      205576             2      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening    [6520104, 6520105]  [1407953, 2536919]                      ["Cheryl Smith", "Ruth Whitney"]       [8.01, 21.11]    [6520106, 6520107]  [7593422, 8880387]                   ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2257             37205258   5024244          <NA>          <NA>        6        6     -150      150       3D        E             3.50             2.50          NaN   None           NaN      205576             3      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening    [6520104, 6520105]  [1407953, 2536919]                      ["Cheryl Smith", "Ruth Whitney"]       [8.01, 21.11]    [6520106, 6520107]  [7593422, 8880387]                   ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2258             37205303   5024251          <NA>          <NA>        2        6      130     -130       4C        N             2.00             4.00          NaN   None           NaN      205576            10      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening    [6520088, 6520089]  [2168774, 7629435]                 ["Kathy Luxemburger", "Sue Langevin"]         [8.51, 5.0]    [6520106, 6520107]  [7593422, 8880387]                   ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2259             37205310   5024252          <NA>          <NA>        2        6     -130      130       3C        E             1.50             4.50          NaN   None           NaN      205576            11      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening    [6520088, 6520089]  [2168774, 7629435]                 ["Kathy Luxemburger", "Sue Langevin"]         [8.51, 5.0]    [6520106, 6520107]  [7593422, 8880387]                   ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2260             37205317   5024253          <NA>          <NA>        2        6      680     -680       4H        N             2.50             2.50          NaN   None           NaN      205576            12      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening    [6520088, 6520089]  [2168774, 7629435]                 ["Kathy Luxemburger", "Sue Langevin"]         [8.51, 5.0]    [6520106, 6520107]  [7593422, 8880387]                   ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2261             37205281   5024248          <NA>          <NA>        1        6     -100      100       3N        S             2.00             4.00          NaN   None           NaN      205576             7      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening    [6520084, 6520085]  [7846509, 9059474]                    ["Vickie Roche", "Stan Marinoske"]        [7.1, 41.76]    [6520106, 6520107]  [7593422, 8880387]                   ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2262             37205288   5024249          <NA>          <NA>        1        6     -170      170       2S        E             4.50             1.50          NaN   None           NaN      205576             8      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening    [6520084, 6520085]  [7846509, 9059474]                    ["Vickie Roche", "Stan Marinoske"]        [7.1, 41.76]    [6520106, 6520107]  [7593422, 8880387]                   ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2263             37205295   5024250          <NA>          <NA>        1        6     -600      600       3N        E             1.00             5.00          NaN   None           NaN      205576             9      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening    [6520084, 6520085]  [7846509, 9059474]                    ["Vickie Roche", "Stan Marinoske"]        [7.1, 41.76]    [6520106, 6520107]  [7593422, 8880387]                   ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2264             37205325   5024254          <NA>          <NA>        3        6     -620      620       4S        W             3.00             3.00          NaN   None           NaN      205576            13      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening    [6520092, 6520093]  [3449335, 6451748]                       ["James Scarfe", "Kirk Rustad"]    [861.47, 637.28]    [6520106, 6520107]  [7593422, 8880387]                   ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2265             37205332   5024255          <NA>          <NA>        3        6      -50       50       2S        S             3.50             2.50          NaN   None           NaN      205576            14      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening    [6520092, 6520093]  [3449335, 6451748]                       ["James Scarfe", "Kirk Rustad"]    [861.47, 637.28]    [6520106, 6520107]  [7593422, 8880387]                   ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2266             37205339   5024256          <NA>          <NA>        3        6     -100      100       5D        S             4.00             2.00          NaN   None           NaN      205576            15      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening    [6520092, 6520093]  [3449335, 6451748]                       ["James Scarfe", "Kirk Rustad"]    [861.47, 637.28]    [6520106, 6520107]  [7593422, 8880387]                   ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2267             37205347   5024257          <NA>          <NA>        4        6      800     -800      3HX        W             0.00             6.00          NaN   None           NaN      205576            16      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening    [6520097, 6520096]  [1015699, 8160996]         ["Maureen Larson", "Mike Landry(swap names)"]   [1084.76, 339.78]    [6520106, 6520107]  [7593422, 8880387]                   ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2268             37205354   5024258          <NA>          <NA>        4        6       50      -50       2S        E             2.00             4.00          NaN   None           NaN      205576            17      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening    [6520097, 6520096]  [1015699, 8160996]         ["Maureen Larson", "Mike Landry(swap names)"]   [1084.76, 339.78]    [6520106, 6520107]  [7593422, 8880387]                   ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2269             37205361   5024259          <NA>          <NA>        4        6     -150      150       3C        E             2.00             4.00          NaN   None           NaN      205576            18      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening    [6520097, 6520096]  [1015699, 8160996]         ["Maureen Larson", "Mike Landry(swap names)"]   [1084.76, 339.78]    [6520106, 6520107]  [7593422, 8880387]                   ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2270             37205266   5024245          <NA>          <NA>        7        6      100     -100       3H        W             6.00             0.00          NaN   None           NaN      205576             4      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening    [6520108, 6520109]  [2324555, 9124993]                   ["Lorraine Hoyt", "Noreen McGowan"]      [14.06, 34.31]    [6520106, 6520107]  [7593422, 8880387]                   ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2271             37205273   5024246          <NA>          <NA>        7        6      650     -650       4S        S             2.50             3.50          NaN   None           NaN      205576             5      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening    [6520108, 6520109]  [2324555, 9124993]                   ["Lorraine Hoyt", "Noreen McGowan"]      [14.06, 34.31]    [6520106, 6520107]  [7593422, 8880387]                   ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2272             37205280   5024247          <NA>          <NA>        7        6      460     -460       3N        S             2.00             4.00          NaN   None           NaN      205576             6      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening    [6520108, 6520109]  [2324555, 9124993]                   ["Lorraine Hoyt", "Noreen McGowan"]      [14.06, 34.31]    [6520106, 6520107]  [7593422, 8880387]                   ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2273             37205369   5024260          <NA>          <NA>        5        6     -620      620       4S        E             4.00             2.00          NaN   None           NaN      205576            19      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening    [6520101, 6520100]  [4029062, 6694985]             ["John Perry", "Julie Perry(swap names)"]  [1170.85, 1043.55]    [6520106, 6520107]  [7593422, 8880387]                   ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2274             37205376   5024261          <NA>          <NA>        5        6      300     -300       3N        W             2.00             4.00          NaN   None           NaN      205576            20      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening    [6520101, 6520100]  [4029062, 6694985]             ["John Perry", "Julie Perry(swap names)"]  [1170.85, 1043.55]    [6520106, 6520107]  [7593422, 8880387]                   ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2275             37205383   5024262          <NA>          <NA>        5        6      620     -620       4H        S             0.50             5.50          NaN   None           NaN      205576            21      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening    [6520101, 6520100]  [4029062, 6694985]             ["John Perry", "Julie Perry(swap names)"]  [1170.85, 1043.55]    [6520106, 6520107]  [7593422, 8880387]                   ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2276             37205265   5024245          <NA>          <NA>        6        5      140     -140       2S        N             2.00             4.00          NaN   None           NaN      205576             4      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening    [6520104, 6520105]  [1407953, 2536919]                      ["Cheryl Smith", "Ruth Whitney"]       [8.01, 21.11]    [6520102, 6520103]  [3109100, 9311599]           ["Colleen Kelly", "Shirley Campbell"]  [428.84, 172.31]
2277             37205272   5024246          <NA>          <NA>        6        5      650     -650       4S        S             2.50             3.50          NaN   None           NaN      205576             5      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening    [6520104, 6520105]  [1407953, 2536919]                      ["Cheryl Smith", "Ruth Whitney"]       [8.01, 21.11]    [6520102, 6520103]  [3109100, 9311599]           ["Colleen Kelly", "Shirley Campbell"]  [428.84, 172.31]
2278             37205279   5024247          <NA>          <NA>        6        5      230     -230       3S        N             6.00             0.00          NaN   None           NaN      205576             6      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening    [6520104, 6520105]  [1407953, 2536919]                      ["Cheryl Smith", "Ruth Whitney"]       [8.01, 21.11]    [6520102, 6520103]  [3109100, 9311599]           ["Colleen Kelly", "Shirley Campbell"]  [428.84, 172.31]
2279             37205324   5024254          <NA>          <NA>        2        5     -620      620       4S        W             3.00             3.00          NaN   None           NaN      205576            13      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening    [6520088, 6520089]  [2168774, 7629435]                 ["Kathy Luxemburger", "Sue Langevin"]         [8.51, 5.0]    [6520102, 6520103]  [3109100, 9311599]           ["Colleen Kelly", "Shirley Campbell"]  [428.84, 172.31]
...                   ...       ...           ...           ...      ...      ...      ...      ...      ...      ...              ...              ...          ...    ...           ...         ...           ...         ...          ...       ...            ...                       ...             ...        ...                  ...       ...                ...                   ...                 ...                                                   ...                 ...                   ...                 ...                                             ...               ...
52780715         71914950   9659817             1             2        2        2      300     -300      4 H        E             1.50             6.50                  -3          7.00      431485             6      392390            B    392390         284681 2021-09-18 00:00:00-05:00          905349      PAIRS         MATCH_POINTS      9.00   Saturday Morning  [13455672, 13455671]  [4536762, 7219938]  ["Putman, Elaine", "Boomgaarden, Arden(swap names)"]      [589.0, 693.0]  [13455690, 13455689]  [1497170, 7788614]     ["Fuller, Carol", "Reddy, Sam(swap names)"]    [171.0, 346.0]
52788511         57289070   7468320          <NA>          <NA>        3        7      140     -140       2S        N             1.00             2.00           C9     +1           NaN      330825             1      294636            A    294636         205971 2021-04-10 00:00:00-05:00          909994      PAIRS         MATCH_POINTS      4.00   Saturday Evening  [10656508, 10656509]  [5331978, 9106588]                        ["Yunhan Wu", "Shengding Sun"]    [179.49, 235.14]  [10656510, 10656511]  [7515324, 7684029]                 ["Hongmo Li", "Sriram Ganesan"]   [45.52, 120.54]
52788512         57289074   7468321          <NA>          <NA>        3        7      600     -600       5C        S             0.50             2.50           S7      =           NaN      330825             2      294636            A    294636         205971 2021-04-10 00:00:00-05:00          909994      PAIRS         MATCH_POINTS      4.00   Saturday Evening  [10656508, 10656509]  [5331978, 9106588]                        ["Yunhan Wu", "Shengding Sun"]    [179.49, 235.14]  [10656510, 10656511]  [7515324, 7684029]                 ["Hongmo Li", "Sriram Ganesan"]   [45.52, 120.54]
52788513         57289078   7468322          <NA>          <NA>        3        7     -660      660       3N        W             3.00             0.00           D8     +2           NaN      330825             3      294636            A    294636         205971 2021-04-10 00:00:00-05:00          909994      PAIRS         MATCH_POINTS      4.00   Saturday Evening  [10656508, 10656509]  [5331978, 9106588]                        ["Yunhan Wu", "Shengding Sun"]    [179.49, 235.14]  [10656510, 10656511]  [7515324, 7684029]                 ["Hongmo Li", "Sriram Ganesan"]   [45.52, 120.54]
52788514         57289092   7468326          <NA>          <NA>        1        7     -620      620       4H        E             2.50             0.50           SK      =           NaN      330825             7      294636            A    294636         205971 2021-04-10 00:00:00-05:00          909994      PAIRS         MATCH_POINTS      4.00   Saturday Evening  [10656500, 10656501]  [2992833, 7584393]                   ["Charles Holmes", "Steven Creech"]      [86.88, 24.59]  [10656510, 10656511]  [7515324, 7684029]                 ["Hongmo Li", "Sriram Ganesan"]   [45.52, 120.54]
52788515         57289096   7468327          <NA>          <NA>        1        7      -50       50       2N        N             1.50             1.50           DA     -1           NaN      330825             8      294636            A    294636         205971 2021-04-10 00:00:00-05:00          909994      PAIRS         MATCH_POINTS      4.00   Saturday Evening  [10656500, 10656501]  [2992833, 7584393]                   ["Charles Holmes", "Steven Creech"]      [86.88, 24.59]  [10656510, 10656511]  [7515324, 7684029]                 ["Hongmo Li", "Sriram Ganesan"]   [45.52, 120.54]

In [20]:
#acbl_hrdf['board_number'] = acbl_hrdf['Board'].astype('int8')

In [21]:
#dfd = dict(zip(zip(df['hand_record_id'],df['board_number']),df.index))
#len(df),len(dfd),dfd

In [22]:
#hrd =  dict(zip(zip(acbl_hrdf['hand_record_id'],acbl_hrdf['board_number']),acbl_hrdf.index))
#len(acbl_hrdf),len(hrd),hrd

In [23]:
#drop_boards_d = [k for k,v in dfd.items() if k not in hrd]
#len(df),len(dfd),len(acbl_hrdf),len(hrd),len(drop_boards_d),drop_boards_d

In [24]:
# Using a df for isin() seems to hang system.
#drop_boards_isin = ~df[['hand_record_id','board_number']].isin(acbl_hrdf[['hand_record_id','board_number']])
#df[drop_boards_isin]

In [25]:
#df['hand_board'] = df['hand_record_id'].astype('string')+'_'+df['board_number'].astype('string')
#df

In [26]:
#acbl_hrdf['hand_board'] = acbl_hrdf['hand_record_id'].astype('string')+'_'+acbl_hrdf['Board'].astype('int8').astype('string')
#acbl_hrdf

In [27]:
#'96309_1' in acbl_hrdf['hand_board']

In [28]:
#drop_hand_boards = ~df['hand_board'].isin(acbl_hrdf['hand_board'])
#df[drop_hand_boards]

In [29]:
#len(missing_board_ids), len(drop_boards_d)#, set(missing_board_ids.index) - set(drop_boards_d.index)

In [30]:
#len(missing_board_ids), len(drop_hand_boards), set(missing_board_ids.index) - set(drop_hand_boards.index)

In [31]:
# takes 20s
df.drop(df[missing_board_ids].index,inplace=True)

In [32]:
# takes 3m30s
# create dict with key of board_id and value of par. Makes par retrival faster.
# todo: move this into create dicts?
# todo: must be a faster way?
pard = {b:p[0] for b,p in zip(df['board_id'],df['board_id'].map(lambda x: acbl_hrdf['Par'].loc[x]))}
pard

{324858: -130,
 324859: -450,
 324860: 110,
 324861: 140,
 324862: 650,
 324863: 200,
 324876: -100,
 324877: 130,
 324878: -120,
 324864: 140,
 324865: 660,
 324866: 140,
 324879: -420,
 324880: 980,
 324881: 980,
 324873: -500,
 324874: 430,
 324875: 420,
 324870: 980,
 324871: 420,
 324872: 450,
 324867: -130,
 324868: 140,
 324869: 140,
 3189583: -430,
 3189584: 1700,
 3189585: 140,
 3189586: 110,
 3189603: -430,
 3189604: -130,
 3189605: 1100,
 3189606: -660,
 3189587: 420,
 3189588: 400,
 3189589: -620,
 3189590: -600,
 3189591: -100,
 3189592: 300,
 3189593: 650,
 3189594: -620,
 3189595: -420,
 3189596: 450,
 3189597: 130,
 3189598: 450,
 3189599: -430,
 3189600: -420,
 3189601: 500,
 3189602: 620,
 3232257: 500,
 3232258: 90,
 3232259: -630,
 3232260: -630,
 3232265: 630,
 3232266: -140,
 3232267: -130,
 3232268: -500,
 3232269: -130,
 3232270: 140,
 3232271: 420,
 3232272: 90,
 3232261: -620,
 3232262: 110,
 3232263: 600,
 3232264: -650,
 3232277: 430,
 3232278: 450,
 3232279: -420,
 3232280: 420,
 3232273: 460,
 3232274: 140,
 3232275: 140,
 3232276: 420,
 3232281: 100,
 3232282: -90,
 3232283: 450,
 3232284: 100,
 3232465: -420,
 3232466: -420,
 3232467: 650,
 3232468: -110,
 3232473: 630,
 3232474: -420,
 3232475: 100,
 3232476: 140,
 3232481: -100,
 3232482: -100,
 3232483: -100,
 3232484: -140,
 3232489: 140,
 3232490: -110,
 3232491: 500,
 3232492: -430,
 3232485: 100,
 3232486: -400,
 3232487: -420,
 3232488: 140,
 3232477: -120,
 3232478: -620,
 3232479: 200,
 3232480: -600,
 3232469: 140,
 3232470: -140,
 3232471: 600,
 3232472: -920,
 324882: 130,
 324883: 460,
 324884: -100,
 324885: -100,
 324902: -630,
 324903: 140,
 324904: 110,
 324906: 90,
 324907: 450,
 324909: 450,
 324890: 300,
 324891: 120,
 324892: 100,
 324893: -140,
 324886: 100,
 324887: 140,
 324888: -430,
 324889: -460,
 324898: 620,
 324899: 600,
 324900: -1440,
 324901: 630,
 324894: -110,
 324895: -140,
 324896: -130,
 324897: 140,
 326563: 110,
 326564: -980,
 326565: 630,
 326566: 1440,
 326567: 420,
 326568: 140,
 326569: 140,
 326570: -110,
 326583: 1440,
 326584: -100,
 326585: -130,
 326586: -500,
 326575: -650,
 326576: -630,
 326577: -420,
 326578: 630,
 326579: 630,
 326580: 400,
 326581: -120,
 326582: -140,
 326571: -100,
 326572: -120,
 326573: -400,
 326574: -140,
 362114: -660,
 362115: -120,
 362116: -620,
 362117: -120,
 362134: -100,
 362135: 400,
 362136: 300,
 362137: 110,
 362126: -650,
 362127: 90,
 362128: 990,
 362129: 500,
 362130: -420,
 362131: -300,
 362132: 120,
 362133: -100,
 362122: 120,
 362123: -100,
 362124: 460,
 362125: 430,
 362118: -1440,
 362119: 130,
 362120: -300,
 362121: -110,
 362138: -400,
 362139: -140,
 362140: -420,
 362141: 500,
 368973: 630,
 368974: 620,
 368975: -600,
 368976: 430,
 368993: 2220,
 368994: -630,
 368995: 650,
 368996: 130,
 368981: -420,
 368982: -450,
 368983: -460,
 368984: -420,
 368985: -300,
 368986: 420,
 368987: 630,
 368988: 140,
 368997: 110,
 368998: 130,
 368999: -100,
 369000: 460,
 368989: 100,
 368990: 100,
 368991: 630,
 368992: 140,
 369001: -1430,
 369002: 140,
 369003: -600,
 369004: 450,
 368977: -1430,
 368978: -1100,
 368979: 420,
 368980: 420,
 371268: 110,
 371269: -100,
 371270: 110,
 371271: 450,
 371272: -130,
 371273: -1100,
 371277: -920,
 371278: -430,
 371279: 100,
 371289: 500,
 371290: -420,
 371291: -100,
 371292: 90,
 371293: -120,
 371294: -140,
 371286: 1440,
 371287: -450,
 371288: -400,
 371283: -140,
 371284: 100,
 371285: -420,
 371274: -420,
 371275: -140,
 371276: -990,
 371280: 140,
 371281: -110,
 371282: -430,
 388147: -300,
 388148: 110,
 388149: -420,
 388150: -980,
 388151: -400,
 388152: -430,
 388153: -110,
 388154: 1400,
 388159: -100,
 388160: -420,
 388161: 140,
 388162: 400,
 388163: 650,
 388164: -630,
 388165: -500,
 388166: 110,
 388155: 600,
 388156: -110,
 388157: 140,
 388158: 650,
 388167: 420,
 388168: -650,
 388169: 110,
 388170: 1400,
 394811: -400,
 394812: -110,
 394813: -980,
 394814: -460,
 394823: 460,
 394824: -500,
 394825: 90,
 394826: -500,
 394835: 460,
 394836: 120,
 394837: 100,
 394838: -200,
 394827: -130,
 394828: -300,
 394829: -120,
 394830: -120,
 394815: -450,
 394816: -620,
 394817: 630,
 394818: 140,
 394819: 620,
 394820: -650,
 394821: 140,
 394822: -110,
 394831: -120,
 394832: -420,
 394833: 400,
 394834: -100,
 402360: 650,
 402361: -1430,
 402362: 1440,
 402375: 450,
 402376: 450,
 402377: -140,
 402369: 460,
 402370: 140,
 402371: 980,
 402384: -90,
 402385: 110,
 402386: -450,
 402378: -130,
 402379: 100,
 402380: 100,
 402372: -620,
 402373: -140,
 402374: -500,
 402366: -600,
 402367: 630,
 402368: -600,
 402381: 140,
 402382: 120,
 402383: 450,
 402363: -110,
 402364: 620,
 402365: 140,
 410689: 600,
 410690: -420,
 410691: -400,
 410692: -980,
 410693: 650,
 410709: 90,
 410710: 110,
 410711: -620,
 410712: 460,
 410713: 140,
 410699: 140,
 410700: -630,
 410701: 600,
 410702: 630,
 410703: 660,
 410704: 500,
 410705: -620,
 410706: -130,
 410707: -620,
 410708: 400,
 410714: -100,
 410715: -140,
 410716: 120,
 410717: 460,
 410718: 140,
 410694: -400,
 410695: 630,
 410696: 100,
 410697: -400,
 410698: -140,
 426328: -100,
 426329: -620,
 426330: -650,
 426331: -500,
 426340: 400,
 426341: 1520,
 426342: 620,
 426343: 100,
 426348: -400,
 426349: -450,
 426350: 120,
 426351: 2210,
 426332: -650,
 426333: 110,
 426334: 430,
 426335: 990,
 426352: 110,
 426353: 130,
 426354: 500,
 426355: 1440,
 426344: 630,
 426345: -110,
 426346: -1510,
 426347: 130,
 426336: -140,
 426337: 300,
 426338: 100,
 426339: -140,
 428606: 130,
 428607: -2000,
 428608: 420,
 428609: -600,
 428610: -130,
 428611: -140,
 428627: -110,
 428628: 650,
 428629: -450,
 428618: 990,
 428619: -90,
 428620: 100,
 428624: 100,
 428625: 100,
 428626: 650,
 428615: -120,
 428616: 140,
 428617: 500,
 428612: 140,
 428613: 460,
 428614: 420,
 428621: -1520,
 428622: -300,
 428623: 420,
 449431: -100,
 449432: 140,
 449433: -140,
 449434: 100,
 449451: -1440,
 449452: -500,
 449453: 110,
 449454: -140,
 449443: -120,
 449444: -1440,
 449445: 600,
 449446: -650,
 449435: -110,
 449436: -920,
 449437: 1100,
 449438: -140,
 449455: 120,
 449456: 420,
 449457: -140,
 449458: -120,
 449447: -110,
 449448: -620,
 449449: 140,
 449450: 90,
 449439: -130,
 449440: -990,
 449441: -140,
 449442: -980,
 450618: -110,
 450619: -140,
 450620: -140,
 450633: -130,
 450634: 120,
 450635: -100,
 450648: -630,
 450649: 650,
 450650: -600,
 450627: -2140,
 450628: 140,
 450629: -990,
 450621: 450,
 450622: -140,
 450623: -2220,
 450642: 650,
 450643: 630,
 450644: 2210,
 450636: -90,
 450637: -110,
 450638: 130,
 450639: 1430,
 450640: -110,
 450641: 620,
 450645: 500,
 450646: -1430,
 450647: -110,
 450624: -120,
 450625: -140,
 450626: 130,
 450630: 140,
 450631: -460,
 450632: 450,
 450588: -620,
 450589: 1370,
 450590: 1370,
 450597: -110,
 450598: -430,
 450599: -120,
 450606: -110,
 450607: -130,
 450608: 2220,
 450594: -650,
 450595: -100,
 450596: -1440,
 450612: -660,
 450613: -110,
 450614: -90,
 450603: 90,
 450604: -130,
 450605: 140,
 450591: -630,
 450592: -140,
 450593: 430,
 450615: 500,
 450616: -120,
 450617: -1440,
 450600: -100,
 450601: 430,
 450602: 430,
 450609: 100,
 450610: 650,
 450611: 620,
 458556: -430,
 458557: -430,
 458558: -130,
 458559: -110,
 458576: -300,
 458577: 400,
 458578: -660,
 458579: 90,
 458572: 650,
 458573: -1400,
 458574: 430,
 458575: -110,
 458580: -600,
 458581: 200,
 458582: -300,
 458583: 100,
 458564: -120,
 458565: -420,
 458566: -620,
 458567: 120,
 458568: 120,
 458569: -500,
 458570: -1400,
 458571: -110,
 458560: 1430,
 458561: 500,
 458562: 500,
 458563: -120,
 460432: -620,
 460433: 100,
 460434: -400,
 460450: 130,
 460451: 980,
 460452: -300,
 460453: -600,
 460454: 450,
 460455: 420,
 460444: 1430,
 460445: 140,
 460446: 130,
 460438: -460,
 460439: -630,
 460440: 630,
 460447: 630,
 460448: 90,
 460449: -130,
 460441: -90,
 460442: -620,
 460443: 140,
 460435: 450,
 460436: 110,
 460437: 500,
 473181: 100,
 473182: 100,
 473183: -140,
 473196: 110,
 473197: 140,
 473198: -650,
 473190: -450,
 473191: 620,
 473192: 300,
 473184: -450,
 473185: 1510,
 473186: 100,
 473199: 620,
 473200: -200,
 473201: 120,
 473193: 110,
 473194: -420,
 473195: 600,
 473187: -400,
 473188: -420,
 473189: 1430,
 473202: 1370,
 473203: 2210,
 473204: 130,
 473205: 460,
 473206: 110,
 473207: -660,
 491610: 100,
 491611: -920,
 491612: 110,
 491613: 100,
 491622: -400,
 491623: -450,
 491624: -460,
 491625: 140,
 491634: -650,
 491635: 120,
 491636: -140,
 491637: -630,
 491626: 500,
 491627: -620,
 491628: -650,
 491629: -660,
 491618: 1440,
 491619: 620,
 491620: 90,
 491621: 620,
 491630: 130,
 491631: -660,
 491632: -500,
 491633: -130,
 491614: 400,
 491615: 140,
 491616: -400,
 491617: 100,
 497799: 1520,
 497800: 430,
 497801: 100,
 497805: -120,
 497806: 1430,
 497807: 1430,
 497808: 630,
 497809: 100,
 497810: 90,
 497802: -200,
 497803: 600,
 497804: 660,
 497814: 110,
 497815: 110,
 497816: 110,
 497817: 140,
 497818: 140,
 497819: 420,
 497811: -200,
 497812: -660,
 497813: 620,
 512029: 130,
 512030: 110,
 512031: 120,
 512050: -100,
 512051: -100,
 512052: -450,
 512044: -140,
 512045: -920,
 512046: -920,
 512053: 1100,
 512054: -400,
 512055: -130,
 512038: -300,
 512039: -90,
 512040: 420,
 512032: -110,
 512033: -650,
 512034: -130,
 512035: -140,
 512036: -300,
 512037: 130,
 512047: -980,
 512048: -450,
 512049: 80,
 512041: 90,
 512042: -130,
 512043: 450,
 533333: 100,
 533334: -400,
 533335: -200,
 533336: -110,
 533357: -620,
 533358: 140,
 533359: -420,
 533360: -420,
 533341: -430,
 533342: 130,
 533343: 620,
 533344: 660,
 533337: -400,
 533338: 100,
 533339: -140,
 533340: 140,
 533349: 600,
 533350: 110,
 533351: -650,
 533352: -300,
 533345: 650,
 533346: 140,
 533347: -120,
 533348: -650,
 533353: 980,
 533354: 420,
 533355: -660,
 533356: -1440,
 538413: 660,
 538414: -90,
 538415: 140,
 538431: 420,
 538432: 450,
 538433: -400,
 538425: 420,
 538426: -980,
 538427: 460,
 538428: 120,
 538429: -450,
 538430: -420,
 538422: 140,
 538423: 400,
 538424: -100,
 538434: 140,
 538435: -120,
 538436: 2220,
 538419: -660,
 538420: -1440,
 538421: -100,
 538416: 140,
 538417: -630,
 538418: -620,
 538437: 500,
 538438: -140,
 538439: -450,
 538440: 140,
 538441: 630,
 538442: -600,
 590325: 100,
 590326: -500,
 590327: -200,
 590328: 100,
 590337: 120,
 590338: 650,
 590339: 130,
 590340: -140,
 590341: -1100,
 590342: -130,
 590343: -1430,
 590344: 140,
 590345: 140,
 590346: 430,
 590347: 90,
 590348: -650,
 590329: -140,
 590330: -400,
 590331: 300,
 590332: 140,
 590349: -140,
 590350: -980,
 590351: 100,
 590352: -420,
 590333: 110,
 590334: -650,
 590335: 110,
 590336: -620,
 590353: 100,
 590354: -100,
 590355: 100,
 590356: -300,
 565426: -140,
 565427: -500,
 565428: -620,
 565447: -140,
 565448: -430,
 565449: -400,
 565441: -100,
 565442: -420,
 565443: -990,
 565435: -630,
 565436: -630,
 565437: 430,
 565429: -110,
 565430: -600,
 565431: -300,
 565438: 420,
 565439: 450,
 565440: -140,
 565432: 140,
 565433: -110,
 565434: 110,
 565450: 660,
 565451: -420,
 565452: 1430,
 565444: -430,
 565445: -430,
 565446: 460,
 595653: -430,
 595654: -2220,
 595655: -100,
 595656: -420,
 595673: -660,
 595674: -140,
 595675: -400,
 595676: -120,
 595669: 600,
 595670: -1430,
 595671: 630,
 595672: 650,
 595661: 1370,
 595662: 420,
 595663: 1520,
 595664: -920,
 595665: 420,
 595666: 420,
 595667: 140,
 595668: -110,
 595657: -430,
 595658: 300,
 595659: -110,
 595660: -100,
 613478: 600,
 613479: 650,
 613480: -620,
 613481: 650,
 613494: 660,
 613495: -430,
 613496: 100,
 613497: -140,
 613506: 120,
 613507: -650,
 613508: -650,
 613509: -110,
 613486: 400,
 613487: 600,
 613488: 110,
 613489: 1400,
 613502: 110,
 613503: 140,
 613504: 650,
 613505: 130,
 613482: 420,
 613483: 1430,
 613484: -420,
 613485: 980,
 613498: 460,
 613499: 120,
 613500: -400,
 613501: -100,
 613490: 140,
 613491: 110,
 613492: 450,
 613493: 980,
 703092: 130,
 703093: 130,
 703094: 500,
 703095: -200,
 703096: -920,
 703097: -460,
 703098: -430,
 703099: -600,
 703108: 300,
 703109: 650,
 703110: 100,
 703111: 630,
 703100: -980,
 703101: -450,
 703102: -200,
 703103: -300,
 703104: -450,
 703105: -140,
 703106: -120,
 703107: 630,
 703116: 140,
 703117: 110,
 703118: 420,
 703119: -660,
 703112: -400,
 703113: 990,
 703114: 120,
 703115: 660,
 703362: -630,
 703363: 200,
 703364: -660,
 703365: 110,
 703366: -1440,
 703367: -650,
 703368: -980,
 703369: -100,
 703378: 800,
 703379: -420,
 703380: 630,
 703381: 100,
 703370: -110,
 703371: 100,
 703372: -140,
 703373: -400,
 703374: 100,
 703375: -110,
 703376: -100,
 703377: 110,
 703386: 130,
 703387: 620,
 703388: -140,
 703389: -620,
 703382: -430,
 703383: -450,
 703384: -450,
 703385: -130,
 739983: -110,
 739984: -990,
 739999: 400,
 740000: 140,
 739993: 600,
 739994: 600,
 739989: -420,
 739990: 2220,
 739985: -920,
 739986: 140,
 740003: 140,
 740004: -130,
 739995: -120,
 739996: -600,
 739987: -430,
 739988: 140,
 740005: -600,
 740006: 1510,
 739997: -1370,
 739998: 650,
 740007: -100,
 740008: 450,
 739991: 620,
 739992: -660,
 740001: -1430,
 740002: 140,
 741314: 980,
 741315: -980,
 741316: 90,
 741332: 140,
 741333: -100,
 741334: -120,
 741323: 110,
 741324: 1430,
 741325: 110,
 741317: 430,
 741318: 140,
 741319: -300,
 741329: -500,
 741330: 500,
 741331: 130,
 741326: -90,
 741327: 140,
 741328: 140,
 741320: 100,
 741321: -500,
 741322: -120,
 783133: 100,
 783134: 420,
 783135: -430,
 783136: -800,
 783145: -420,
 783146: 1440,
 783147: 300,
 783148: 110,
 783137: -990,
 783138: -990,
 783139: -300,
 783140: -100,
 783157: -120,
 783158: -800,
 783159: 420,
 783160: 620,
 783149: -140,
 783150: 800,
 783151: 800,
 783152: -420,
 783153: 140,
 783154: 500,
 783155: 300,
 783156: -430,
 783141: 100,
 783142: 140,
 783143: 300,
 783144: 500,
 873858: 400,
 873859: -450,
 873860: 300,
 873861: -420,
 873878: 140,
 873879: -620,
 873880: -140,
 873881: -1440,
 873870: 1430,
 873871: 100,
 873872: -140,
 873873: 620,
 873862: -100,
 873863: -450,
 873864: 130,
 873865: 130,
 873882: -600,
 873883: 110,
 873884: -620,
 873885: 110,
 873874: 500,
 873875: -200,
 873876: 620,
 873877: -630,
 873866: 800,
 873867: -400,
 873868: 620,
 873869: 120,
 906514: -100,
 906515: 1430,
 906516: 140,
 906517: -420,
 906530: -620,
 906531: -1440,
 906532: -110,
 906533: -2210,
 906534: 110,
 906535: 130,
 906536: -100,
 906537: 450,
 906526: 500,
 906527: 1440,
 906528: 120,
 906529: 140,
 906518: -110,
 906519: -450,
 906520: -420,
 906521: 1370,
 ...}

In [33]:
assert df['board_id'].isin(pard).all()

In [34]:
del acbl_hrdf

In [35]:
# takes 2s
df.loc[df['ns_score'] == 'PASS','ns_score'] = '0'
assert df['ns_score'].ne('PASS').all()
df.loc[df['ew_score'] == 'PASS','ew_score'] = '0'
assert df['ew_score'].ne('PASS').all()

In [36]:
# takes 5s
# drop non-numeric scores. Around 18,000.
drop_scores = ~df['ns_score'].map(lambda c: c[c[0] == '-':].isnumeric()) | ~df['ew_score'].map(lambda c: c[c[0] == '-':].isnumeric())
df[drop_scores]

          board_result_id  board_id  round_number  table_number  ns_pair  ew_pair ns_score ew_score contract declarer  ew_match_points  ns_match_points opening_lead result  tricks_taken  section_id  board_number  session_id section_name  event_id hand_record_id                 game_date  club_id_number event_type board_scoring_method  tb_count         club_session        player_id_ns                                     player_number_ns                                            player_name_ns          mp_total_ns        player_id_ew                                                                      player_number_ew                                          player_name_ew           mp_total_ew
9513             22747459   3189590             2             1        1        6       NP       NP                 N             0.00             0.00                               NaN      119566             8      101264            D    101264          78107 2020-02-18 00:00:00-06:00          100222      PAIRS         MATCH_POINTS      6.00      Tuesday Morning  [3705673, 3705672]                                   [4680839, 4681355]        ["Pempsell, Linda", "Redden, Cynthia(swap names)"]        [5.39, 81.94]  [3705695, 3705694]                                                                    [3763137, 3763145]             ["Layton, Mike", "Layton, Dee(swap names)"]      [103.75, 103.75]
9539             22747448   3189588             2             6        6        5       NP       NP                 N             0.00             0.00                               NaN      119566             6      101264            D    101264          78107 2020-02-18 00:00:00-06:00          100222      PAIRS         MATCH_POINTS      6.00      Tuesday Morning  [3705682, 3705683]                                   [3572056, 8458596]                 ["Anderson, Joyce", "Little, Mary Ellen"]     [790.92, 608.08]  [3705693, 3705692]                                                                    [7396295, 9264256]           ["Stanley, Tracy", "Cook, Karen(swap names)"]      [127.48, 208.26]
12106             2589187    369000             2             6        6        5       NP       NP                 N             0.00             0.00                               NaN       13937            28       11761            S     11761          10070 2019-09-04 00:00:00-05:00          100222      PAIRS         MATCH_POINTS      8.00  Wednesday Afternoon    [418650, 418649]                                   [9067027, 9578900]                ["Farrell, Don", "Mast, Earl(swap names)"]     [608.07, 794.54]    [418664, 418663]                                                                    [2735873, 5326567]          ["Orndorff, Tom", "Malone, Barry(swap names)"]       [189.3, 222.22]
12642             2726377    388158             1             3        3        3       NP       NP                 N             0.00             0.00                               NaN       14662            12       12352            M     12352          10587 2019-09-09 00:00:00-05:00          100222      PAIRS         MATCH_POINTS      6.00     Monday Afternoon    [440772, 440771]                                   [5901936, 9067183]            ["Allen, Barbara", "Romack, Dave(swap names)"]     [225.62, 252.97]    [440784, 440783]                                                                    [3763137, 3763145]             ["Layton, Mike", "Layton, Dee(swap names)"]        [92.66, 92.66]
12810             2772890    394838             6             2        2        4       NP       NP                 N             0.00             0.00                               NaN       14914            28       12558            D     12558          10784 2019-09-10 00:00:00-05:00          100222      PAIRS         MATCH_POINTS      7.00      Tuesday Morning    [448302, 448301]                                   [5901936, 9067183]            ["Allen, Barbara", "Romack, Dave(swap names)"]     [225.62, 252.97]    [448320, 448319]                                                                    [7396295, 9264256]           ["Stanley, Tracy", "Cook, Karen(swap names)"]       [110.32, 175.1]
17117             2992790    426339             4             7        7        4       NP       NP                 N             0.00             0.00                               NaN       16098            12       13516            B     13515          11650 2019-09-16 00:00:00-05:00          100222      PAIRS         MATCH_POINTS      7.00       Monday Evening    [483834, 483833]                                   [5788072, 6742009]          ["Daddario, Grace", "Nelson, Vance(swap names)"]     [593.96, 539.16]    [483841, 483842]                                                                    [3193640, 7371624]                  ["Koenigseder, Becky", "White, Larry"]    [4375.79, 1708.91]
17122             2992794    426340             1             4        4        4     AVE-     AVE+      3 D        W             3.60             2.40                  -2          7.00       16098            13       13516            B     13515          11650 2019-09-16 00:00:00-05:00          100222      PAIRS         MATCH_POINTS      7.00       Monday Evening    [483827, 483828]                                   [5910625, 6662250]                        ["Hillaker, Hugh", "Cassidy, Pat"]  [16870.45, 8591.84]    [483841, 483842]                                                                    [3193640, 7371624]                  ["Koenigseder, Becky", "White, Larry"]    [4375.79, 1708.91]
17600             3009342    428629             5             4        4        8       NP       NP                 N             0.00             0.00                               NaN       16183            24       13585            D     13584          11711 2019-09-17 00:00:00-05:00          100222      PAIRS         MATCH_POINTS      7.50      Tuesday Morning    [486504, 486503]                                   [4680839, 9564861]            ["Pempsell, Linda", "Hill, Wilma(swap names)"]       [5.39, 303.73]    [486525, 486526]                                                                    [2236400, 3101673]                  ["Deering, Helen", "Bedford, Dorothy"]        [0.0, 2349.65]
22736             3161391    450594             3             1        1        9    -620F     620F      4 S        W             8.00             0.00                   =         10.00       17013             7       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511236, 511235]                                   [3136612, 3572056]          ["Castioni, Liz", "Anderson, Joyce(swap names)"]     [595.76, 717.35]    [511272, 511271]                                                                    [4556585, 6938051]        ["Jones, Kimmel", "Kornegay, Nancy(swap names)"]  [11927.14, 11339.74]
22747             3161386    450593             7             6        6        9     480F    -480F      4 S        N             1.00             7.00                  +2         12.00       17013             6       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511245, 511246]                                   [2821699, 6745555]                         ["Keller, Carol", "Prince, Rita"]    [5168.59, 1163.5]    [511272, 511271]                                                                    [4556585, 6938051]        ["Jones, Kimmel", "Kornegay, Nancy(swap names)"]  [11927.14, 11339.74]
22756             3161382    450593             3            10       10        8     430F    -430F     3 NT        N             6.00             2.00                  +1         10.00       17013             6       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511253, 511254]                                   [1480731, 8503796]                 ["Vanderwolk, Steve", "McConnell, Carol"]     [87.58, 2713.95]    [511269, 511270]                                                                    [2006774, 6398308]                    ["McGill, Richard", "Zachry, Joyce"]    [1527.49, 2065.76]
22769             3161396    450594             8             6        6        8     100F    -100F      4 S        W             1.50             6.50                  -1          9.00       17013             7       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511245, 511246]                                   [2821699, 6745555]                         ["Keller, Carol", "Prince, Rita"]    [5168.59, 1163.5]    [511269, 511270]                                                                    [2006774, 6398308]                    ["McGill, Richard", "Zachry, Joyce"]    [1527.49, 2065.76]
22781             3161392    450594             4            10       10        7     200F    -200F      4 S        W             0.00             8.00                  -2          8.00       17013             7       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511253, 511254]                                   [1480731, 8503796]                 ["Vanderwolk, Steve", "McConnell, Carol"]     [87.58, 2713.95]    [511267, 511268]                                                                    [5623456, 6884822]                ["Meyer Nolan, Betty Jane", "Berg, Dee"]     [580.76, 3488.06]
22804             3161387    450593             8             5        5        7     420F    -420F      4 S        N             7.50             0.50                   =         10.00       17013             6       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511243, 511244]                                   [6779778, 7979177]                           ["Ryan, Yvonne", "Owren, Mary"]      [205.3, 151.42]    [511267, 511268]                                                                    [5623456, 6884822]                ["Meyer Nolan, Betty Jane", "Berg, Dee"]     [580.76, 3488.06]
22819             3161383    450593             4             9        9        6     450F    -450F      5 S        N             4.50             3.50                   =         11.00       17013             6       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511251, 511252]                                   [5252679, 8125600]                ["Stanton, Mary Ellen", "Peterson, Nancy"]   [2098.86, 3010.15]    [511265, 511266]                                                                    [4458079, 9747095]                      ["Hacker, Rosalee", "Parker, Ann"]    [1366.08, 1919.15]
22826             3161397    450594             9             5        5        6    -170F     170F      2 S        W             5.50             2.50                  +2         10.00       17013             7       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511243, 511244]                                   [6779778, 7979177]                           ["Ryan, Yvonne", "Owren, Mary"]      [205.3, 151.42]    [511265, 511266]                                                                    [4458079, 9747095]                      ["Hacker, Rosalee", "Parker, Ann"]    [1366.08, 1919.15]
22849             3161384    450593             5             8        8        4     460F    -460F     3 NT        N             3.00             5.00                  +2         11.00       17013             6       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511250, 511249]                                   [4571134, 9797629]          ["Booth, Connie", "Easley, Corrine(swap names)"]     [793.85, 728.71]    [511262, 511261]                                                                    [7396295, 9264256]           ["Stanley, Tracy", "Cook, Karen(swap names)"]       [110.32, 175.1]
22868             3161389    450594             1             3        3        3    -170F     170F      2 S        W             5.50             2.50                  +2         10.00       17013             7       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511240, 511239]                                   [4397703, 8592179]         ["Pennington, Ann", "Fields, Gloria(swap names)"]     [201.55, 479.18]    [511259, 511260]                                                                    [5197848, 7431538]                        ["Hill, Dwight", "Doe, Susan S"]      [542.81, 952.16]
22901             3161394    450594             6             8        8        2      70F     -70F      1 C        S             3.00             5.00                   =          7.00       17013             7       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511250, 511249]                                   [4571134, 9797629]          ["Booth, Connie", "Easley, Corrine(swap names)"]     [793.85, 728.71]    [511257, 511258]                                                                    [4640004, 9236643]                       ["Smith, Larz", "Corbett, Wayne"]     [1022.59, 141.53]
22915             3161380    450593             1             2        2        2     450F    -450F      4 S        N             4.50             3.50                  +1         11.00       17013             6       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511238, 511237]                                   [4639952, 8783314]      ["Nelson, Helen", "Schemensky, Jeannie(swap names)"]    [1565.16, 671.79]    [511257, 511258]                                                                    [4640004, 9236643]                       ["Smith, Larz", "Corbett, Wayne"]     [1022.59, 141.53]
22921             3161385    450593             6             7        7        1     480F    -480F      4 S        N             1.00             7.00                  +2         12.00       17013             6       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511247, 511248]                                   [3132889, 7556020]                         ["Gann, Melody", "Tryon, Mickey"]    [7637.8, 2311.62]    [511256, 511255]                                                                    [5051622, 8696519]        ["Taylor, Paul", "Scrimale, Robert(swap names)"]    [1384.54, 1248.29]
22940             3161390    450594             2             2        2        1     100F    -100F      4 S        W             1.50             6.50                  -1          9.00       17013             7       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511238, 511237]                                   [4639952, 8783314]      ["Nelson, Helen", "Schemensky, Jeannie(swap names)"]    [1565.16, 671.79]    [511256, 511255]                                                                    [5051622, 8696519]        ["Taylor, Paul", "Scrimale, Robert(swap names)"]    [1384.54, 1248.29]
22946             3161395    450594             7             7        7       10    -110F     110F      2 S        W             4.00             4.00                   =          8.00       17013             7       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511247, 511248]                                   [3132889, 7556020]                         ["Gann, Melody", "Tryon, Mickey"]    [7637.8, 2311.62]    [511273, 511274]                                                                    [1692658, 9277900]                      ["Robbins, John", "Benjamin, Ben"]      [669.34, 256.96]
22954             3161381    450593             2             1        1       10     420F    -420F      4 S        N             7.50             0.50                   =         10.00       17013             6       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511236, 511235]                                   [3136612, 3572056]          ["Castioni, Liz", "Anderson, Joyce(swap names)"]     [595.76, 717.35]    [511273, 511274]                                                                    [1692658, 9277900]                      ["Robbins, John", "Benjamin, Ben"]      [669.34, 256.96]
22979             3161393    450594             5             9        9        5    -300F     300F      4 C        S             7.00             1.00                  -3          7.00       17013             7       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511251, 511252]                                   [5252679, 8125600]                ["Stanton, Mary Ellen", "Peterson, Nancy"]   [2098.86, 3010.15]    [511264, 511263]                                                                    [5739675, 5788072]       ["Segreti, Carol", "Daddario, Grace(swap names)"]      [590.45, 593.96]
...                   ...       ...           ...           ...      ...      ...      ...      ...      ...      ...              ...              ...          ...    ...           ...         ...           ...         ...          ...       ...            ...                       ...             ...        ...                  ...       ...                  ...                 ...                                                  ...                                                       ...                  ...                 ...                                                                                   ...                                                     ...                   ...
51516486         16206082   2290658            13             2        2        7     620F    -620F      4 H        S             2.75             9.25                   =         10.00       85923            28       70286            A     70280          56832 2020-01-09 00:00:00-06:00          276873      PAIRS         MATCH_POINTS     17.50   Thursday Afternoon  [2634491, 2634490]                                   [1988301, 7595883]                ["Johnson, Eva", "Dias, John(swap names)"]    [2149.18, 1068.4]  [2634536, 2634537]                                                                    [2670623, 6164188]                            ["Baesl, Tom", "Brown, Lee"]      [756.05, 382.11]

In [37]:
# takes 5s
df.drop(df[drop_scores].index,inplace=True)

In [38]:
# todo: why is declarer a category? Why does it contain non-NSEW? Need to change classifier in mlBridgeLib?
df['declarer'].value_counts()

N     2735157
E     2574929
W     2484411
S     2463727
EW         84
NS         66
           16
w           1
Name: declarer, dtype: int64

In [39]:
drop_declarers = ~df['declarer'].isin(list('NSEW')) # keep N,S,E,W. Drop EW, NS, w, ... < 200 cases.
df[drop_declarers]

          board_result_id  board_id  round_number  table_number  ns_pair  ew_pair ns_score ew_score contract declarer  ew_match_points  ns_match_points opening_lead result  tricks_taken  section_id  board_number  session_id section_name  event_id hand_record_id                 game_date  club_id_number event_type board_scoring_method  tb_count         club_session        player_id_ns                                     player_number_ns                                        player_name_ns         mp_total_ns        player_id_ew                                     player_number_ew                                          player_name_ew         mp_total_ew
4183213          22890328   3209267             3             2        2        9     -530      530                               7.00             0.00                               NaN      120313            12      101981            A    101981          78576 2020-02-18 00:00:00-06:00          118976      PAIRS         MATCH_POINTS      9.00      Tuesday Evening  [3729174, 3729173]                                   [7653670, 7826796]       ["Chroman, Zack", "Singhal, Mihir(swap names)"]        [5.37, 5.49]  [3729206, 3729205]                                   [7781032, 7959036]            ["Ornaf, Raphael", "Lau, Joyce(swap names)"]        [4.8, 11.87]
4183361          19219939   2701971             4             5        5        2     -500      500                               5.00             0.00                               NaN      101274            12       83744            A     83744          66559 2020-01-28 00:00:00-06:00          118976      PAIRS         MATCH_POINTS      6.00      Tuesday Evening  [3127125, 3127126]                                   [5762200, 5804957]                ["Etkind, Wendy", "Freidin, Jonathan"]     [33.22, 130.85]  [3127131, 3127132]  [3105059, tmp:0d66458e-3772-4498-9888-64041867aa00]                        ["Filosa, Ron", "Garg, Swapnil"]       [112.07, nan]
12417561          9873369   1403835             9             6        6        9        0        0     PASS       NS             5.00             3.00                               NaN       52663             5       43212            A     43206          34921 2019-11-19 00:00:00-06:00          159004      PAIRS         MATCH_POINTS     11.00    Tuesday Afternoon  [1601985, 1601986]                                   [5393922, 5697824]             ["Greenbaum, Carolyn", "Stenson, Robert"]    [119.99, 117.14]  [1602013, 1602014]                                   [7706170, 7710631]                  ["Deaton, Robert", "Deaton, Victoria"]        [9.24, 5.95]
17815727         14450842   2041683             7             3        3        8     -300      300      4 S       EW             6.00             0.00                  -3          7.00       76566            26       62540            C     62534          50612 2019-12-24 00:00:00-06:00          209080      PAIRS         MATCH_POINTS     32.00    Tuesday Afternoon  [2348099, 2348100]                                   [2599686, 7667663]                ["Spector, Sue", "Greenbaum, Stanley"]       [81.37, 8.34]  [2348131, 2348132]  [2601893, tmp:5f0f0099-7280-440a-837d-01262b95fc3d]                     ["Burwick, Andrea", "Burwick, Bob"]       [26.58, 16.0]
17935815         23838807   3339545             2             3        3        2     -600      600     3 NT       EW             4.00             0.00           C3      =          9.00      125219            22      106684            A    106684          81665 2020-02-24 00:00:00-06:00          209742      PAIRS         MATCH_POINTS      5.00     Monday Afternoon  [3885012, 3885013]  [8518882, tmp:16248994-9db6-4e07-8ed4-ad5f2ad44e68]                     ["Simonetti, Toni", "Lanyi, Ann"]       [141.29, nan]  [3885021, 3885020]                                   [2233517, 8616310]       ["Hayes, Gloria", "Trainer, Barbara(swap names)"]    [486.07, 302.43]
19432431         17510175   2469677             7             8        8        2     -110      110      3 D       EW             6.50            10.50           S4      =          9.00       92601            15       75474            C     75468          61103 2020-01-17 00:00:00-06:00          217489      PAIRS         MATCH_POINTS     18.00     Friday Afternoon  [2847785, 2847784]                                   [3248089, 3562263]          ["Wright, Gwen", "King, Sandra(swap names)"]    [438.57, 432.66]  [2847791, 2847790]                                   [2284065, 9502130]         ["Rothbard, Marty", "Zaczek, Leon(swap names)"]    [599.79, 946.37]
19926787          6775981    969372             1             1        1        1      140     -140      3 H       NS             1.50             3.50                   =          9.00       36466             1       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098320, 1098319]  [5100666, tmp:b41e9765-50c0-4e1b-aebd-235c67a3dfd3]         ["Ater, Dianne", "Dykins, Cindy(swap names)"]         [31.1, nan]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19926788          6775987    969373             1             1        1        1       50      -50      2 S       EW             3.50             1.50                  -1          7.00       36466             2       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098320, 1098319]  [5100666, tmp:b41e9765-50c0-4e1b-aebd-235c67a3dfd3]         ["Ater, Dianne", "Dykins, Cindy(swap names)"]         [31.1, nan]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19926789          6775993    969374             1             1        1        1      170     -170      3 S       NS             4.00             1.00                  +1         10.00       36466             3       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098320, 1098319]  [5100666, tmp:b41e9765-50c0-4e1b-aebd-235c67a3dfd3]         ["Ater, Dianne", "Dykins, Cindy(swap names)"]         [31.1, nan]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19926790          6775999    969375             1             1        1        1     -100      100     3 NT       NS             3.50             1.50                  -1          8.00       36466             4       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098320, 1098319]  [5100666, tmp:b41e9765-50c0-4e1b-aebd-235c67a3dfd3]         ["Ater, Dianne", "Dykins, Cindy(swap names)"]         [31.1, nan]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19926791          6776009    969376             4             4        4        1      150     -150      4 C       EW             2.00             3.00                  -3          7.00       36466             5       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098326, 1098325]                                   [2580659, 8058261]          ["Walker, Molly", "Walker, Jim(swap names)"]      [78.06, 17.53]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19926792          6776015    969377             4             4        4        1     -100      100    4 S x       NS             3.50             1.50                  -1          9.00       36466             6       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098326, 1098325]                                   [2580659, 8058261]          ["Walker, Molly", "Walker, Jim(swap names)"]      [78.06, 17.53]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19926793          6776021    969378             4             4        4        1      600     -600      5 C       NS             3.00             2.00                   =         11.00       36466             7       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098326, 1098325]                                   [2580659, 8058261]          ["Walker, Molly", "Walker, Jim(swap names)"]      [78.06, 17.53]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19926794          6776027    969379             4             4        4        1     -430      430     3 NT       EW             4.50             0.50                  +1         10.00       36466             8       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098326, 1098325]                                   [2580659, 8058261]          ["Walker, Molly", "Walker, Jim(swap names)"]      [78.06, 17.53]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19926795          6776057    969384             5             5        5        1     -100      100      5 S       NS             4.00             1.00                  -1         10.00       36466            13       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098327, 1098328]                                   [7360061, 7360088]                ["France, Roger", "France, Mary Beth"]    [625.91, 534.41]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19926796          6776063    969385             5             5        5        1       50      -50      4 H       EW             2.50             2.50                  -1          9.00       36466            14       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098327, 1098328]                                   [7360061, 7360088]                ["France, Roger", "France, Mary Beth"]    [625.91, 534.41]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19926797          6776069    969386             5             5        5        1     -200      200      3 H       NS             2.00             3.00                  -2          7.00       36466            15       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098327, 1098328]                                   [7360061, 7360088]                ["France, Roger", "France, Mary Beth"]    [625.91, 534.41]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19926798          6776075    969387             5             5        5        1      -50       50      3 H       NS             4.00             1.00                  -1          8.00       36466            16       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098327, 1098328]                                   [7360061, 7360088]                ["France, Roger", "France, Mary Beth"]    [625.91, 534.41]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19926799          6776078    969388             3             3        3        1     -520      520     3 NT       EW             2.00             3.00                  +4         13.00       36466            17       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098323, 1098324]                                   [9213988, 9312021]               ["Jones, RaeDonna", "Butler, Margaret"]    [788.09, 605.08]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19926800          6776084    969389             3             3        3        1      110     -110      3 D       NS             1.50             3.50                   =          9.00       36466            18       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098323, 1098324]                                   [9213988, 9312021]               ["Jones, RaeDonna", "Butler, Margaret"]    [788.09, 605.08]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19926801          6776090    969390             3             3        3        1     -620      620      4 H       EW             4.50             0.50                   =         10.00       36466            19       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098323, 1098324]                                   [9213988, 9312021]               ["Jones, RaeDonna", "Butler, Margaret"]    [788.09, 605.08]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19926802          6776096    969391             3             3        3        1     -200      200      3 H       EW             2.50             2.50                  +2         11.00       36466            20       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098323, 1098324]                                   [9213988, 9312021]               ["Jones, RaeDonna", "Butler, Margaret"]    [788.09, 605.08]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19926803          6776106    969392             6             6        6        1      120     -120     1 NT       NS             0.50             4.50                  +1          8.00       36466            21       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098329, 1098330]                                   [9373489, 9373497]                    ["Young, Bonnie", "Stwalley, Ray"]      [15.15, 19.14]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19926804          6776112    969393             6             6        6        1      100     -100      3 C       EW             3.00             2.00                  -1          8.00       36466            22       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098329, 1098330]                                   [9373489, 9373497]                    ["Young, Bonnie", "Stwalley, Ray"]      [15.15, 19.14]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19926805          6776118    969394             6             6        6        1      100     -100      3 S       EW             3.00             2.00                  -1          8.00       36466            23       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098329, 1098330]                                   [9373489, 9373497]                    ["Young, Bonnie", "Stwalley, Ray"]      [15.15, 19.14]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
...                   ...       ...           ...           ...      ...      ...      ...      ...      ...      ...              ...              ...          ...    ...           ...         ...           ...         ...          ...       ...            ...                       ...             ...        ...                  ...       ...                  ...                 ...                                                  ...                                                   ...                 ...                 ...                                                  ...                                                     ...                 ...
19926923          6776081    969388             5             6        6        2     -980      980      6 S       EW             4.00             1.00                   =         12.00       36466            17       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098329, 1098330]                                   [9373489, 9373497]                    ["Young, Bonnie", "Stwalley, Ray"]      [15.15, 19.14]  [1098334, 1098333]                                   [2670496, 7307322]        ["Golson, Tom", "Boatright, Harvey(swap names)"]       [57.76, 53.3]
19926924          6776087    969389             5             6        6        2      100     -100      3 H       EW             3.00             2.00                  -2          7.00       36466            18       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098329, 1098330]                                   [9373489, 9373497]                    ["Young, Bonnie", "Stwalley, Ray"]      [15.15, 19.14]  [1098334, 1098333]                                   [2670496, 7307322]        ["Golson, Tom", "Boatright, Harvey(swap names)"]       [57.76, 53.3]
19926925          6776093    969390             5             6        6        2     -110      110      2 H       EW             2.00             3.00                   =          8.00       36466            19       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098329, 1098330]                                   [9373489, 9373497]                    ["Young, Bonnie", "Stwalley, Ray"]      [15.15, 19.14]  [1098334, 1098333]                                   [2670496, 7307322]        ["Golson, Tom", "Boatright, Harvey(swap names)"]       [57.76, 53.3]

In [40]:
# takes 4s
df.drop(df[drop_declarers].index,inplace=True)

In [41]:
# tb_count isn't reliable indicatior of determining top board.
#drop_match_points = (df['ns_match_points']+df['ew_match_points']) != (df['tb_count']-1)
#df[drop_match_points]
#df.head(100)

In [42]:
# takes 2s
# drop rows where ns_match_points + ew_match_points are outliers.
# todo: revisit
sum_rounded = (df['ns_match_points']+df['ew_match_points']).round(1) # round(1) or round(2)?
sum_rounded_dict = sum_rounded.value_counts().to_dict()
#df['ns_ew_match_point_vc'] = sum_rounded.map(sum_rounded_dict)
drop_match_points = sum_rounded.eq(0) | sum_rounded.map(sum_rounded_dict).le(200)
print(len(df),sum(drop_match_points))
df[drop_match_points]

10258224 11368

          board_result_id  board_id  round_number  table_number  ns_pair  ew_pair ns_score ew_score contract declarer  ew_match_points  ns_match_points opening_lead result  tricks_taken  section_id  board_number  session_id section_name  event_id hand_record_id                 game_date  club_id_number event_type board_scoring_method  tb_count         club_session        player_id_ns                                     player_number_ns                                           player_name_ns         mp_total_ns        player_id_ew                                     player_number_ew                                      player_name_ew          mp_total_ew
116544           13935752   1967256             4             7        7        4     -140      140      3 H        E             0.50             5.00                   =          9.00       73744             7       59437            K     59431          48716 2019-12-18 00:00:00-06:00          100230      PAIRS         MATCH_POINTS      8.00  Wednesday Afternoon  [2263741, 2263742]                                   [6672183, 8676283]                         ["White, Opie", "Sandars, Bill"]    [297.68, 494.09]  [2263751, 2263752]                                   [5903300, 6312934]                   ["Ream, Bill", "Parmley, Shelba"]  [4596.49, 15238.52]
140777            3179757    453124            11             3        3        8      100      620      4 S        W            10.00            10.50                   =         10.00       17106            26       14400            A     14399          12399 2019-09-23 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     15.00     Monday Afternoon    [514145, 514146]                                   [2081016, 2124181]                    ["Kaufman, Beverly", "Colton, Susan"]  [2174.17, 1425.01]    [514185, 514186]                                   [4412788, 7605404]                ["Realini, Francis", "Hader, Aaron"]     [705.71, 675.77]
140841            3179751    453124             5             9        9        5      100     -100      4 S        W             0.00            10.50                  -1          9.00       17106            26       14400            A     14399          12399 2019-09-23 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     15.00     Monday Afternoon    [514157, 514158]                                   [5239060, 9899901]                      ["Scheiner, Harry", "Buma, Haruko"]    [252.37, 577.01]    [514179, 514180]                                   [5578833, 9077235]                ["Kanter, Carol", "Boltin, Roberta"]      [136.83, 61.03]
175533             789674    115289             5             9        9        5       50      450      5 S        W             4.50             7.00                   =         11.00        4369             2        3629            A      3629           3231 2019-06-10 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     12.00       Monday Morning    [127208, 127207]                                   [4444450, 8241597]          ["Field, Carol", "Grossman, Donna(swap names)"]  [3495.46, 1172.43]    [127224, 127223]                                   [8452881, 4472500]  ["Herbert, Madeleine", "Hough, Betty(swap names)"]   [1722.15, 1406.98]
188084            1049850    152631            12             8        8       12      630     -630     3 NT        S             1.14            10.00                  +1         10.00        5786             7        4861            A      4861           4228 2019-07-01 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     15.00     Monday Afternoon    [169378, 169377]                                   [4444450, 8241597]          ["Field, Carol", "Grossman, Donna(swap names)"]  [3495.46, 1172.43]    [169415, 169416]                                   [2938499, 9234535]                ["Lieberman, Lana", "Ross, Roberta"]     [109.72, 123.49]
188112            1049843    152631             5            15       15       11     -100      100     3 NT        S             9.32             1.50                  -1          8.00        5786             7        4861            A      4861           4228 2019-07-01 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     15.00     Monday Afternoon    [169391, 169392]                                   [3575926, 5427673]                        ["Abel, Bruce", "Lesser, Irving"]    [149.66, 994.18]    [169414, 169413]                                   [4808592, 1350439]  ["Boswell, Miyoko", "Bernstein, Ruth(swap names)"]   [6506.93, 2658.82]
188214            1049845    152631             7            13       13        7      600     -600     3 NT        S             3.32             7.50                   =          9.00        5786             7        4861            A      4861           4228 2019-07-01 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     15.00     Monday Afternoon    [169388, 169387]                                   [9817298, 1836498]           ["Bauer, Allan", "Ganin, Barbara(swap names)"]      [543.6, 606.5]    [169405, 169406]  [5329779, tmp:7cfe73e5-1c05-4335-9093-cdf9d8c2f479]              ["Braunstein, Allan", "Hamer, Norman"]        [76.22, 54.0]
188266            1049846    152631             8            12       12        5      630     -630     3 NT        S             1.14            10.00                  +1         10.00        5786             7        4861            A      4861           4228 2019-07-01 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     15.00     Monday Afternoon    [169386, 169385]                                   [1387626, 1766880]              ["Peters, Dan", "Gordon, Neil(swap names)"]   [1605.82, 1771.4]    [169402, 169401]                                   [3243877, 8892563]     ["Cannon, Martin", "Freel, Gerald(swap names)"]    [202.81, 1571.01]
188312            1049847    152631             9            11       11        3      180     -180     2 NT        S             4.41             6.00                  +2         10.00        5786             7        4861            A      4861           4228 2019-07-01 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     15.00     Monday Afternoon    [169384, 169383]                                   [5078555, 5078547]   ["Morris, Felice", "Schaumberger, Sylvia(swap names)"]    [662.42, 406.51]    [169398, 169397]                                   [8042357, 8540039]     ["Danziger, Renee", "Limaye, Arun(swap names)"]    [530.77, 5055.66]
188326            1049849    152631            11             9        9       14      120     -120     1 NT        S             7.14             3.50                  +1          8.00        5786             7        4861            A      4861           4228 2019-07-01 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     15.00     Monday Afternoon    [169380, 169379]                                   [9386025, 9386017]  ["Pomerantz, Sandy", "Bar-Nissim, Barbara(swap names)"]     [155.34, 153.6]    [169420, 169419]                                   [2114208, 1757318]    ["Ghosh, Subrata", "Kuharetz, John(swap names)"]    [2926.4, 4969.09]
188354            1049842    152631             4             1        1       13      630     -630     3 NT        S             1.14            10.00                  +1         10.00        5786             7        4861            A      4861           4228 2019-07-01 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     15.00     Monday Afternoon    [169364, 169363]                                   [3257975, 7967829]       ["Sundheimer, Steven", "Rimer, Myron(swap names)"]   [2052.82, 3417.9]    [169418, 169417]                                   [9077553, 9077561]       ["Elk, Rosalind", "Elk, Seymour(swap names)"]  [12411.25, 1059.65]
188390            1049840    152631             2             3        3        2     -100      100     3 NT        S             9.32             1.50                  -1          8.00        5786             7        4861            A      4861           4228 2019-07-01 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     15.00     Monday Afternoon    [169368, 169367]                                   [6396550, 6396569]    ["Calkins, Glenda", "Calkins, R Barkley(swap names)"]  [3126.92, 2517.34]    [169396, 169395]                                   [3084582, 3098699]     ["Yarkon, Beverly", "Danow, Susan(swap names)"]      [92.87, 107.52]
188394            1049848    152631            10            10       10        1      150     -150     1 NT        S             5.50             5.00                  +2          9.00        5786             7        4861            A      4861           4228 2019-07-01 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     15.00     Monday Afternoon    [169382, 169381]                                   [5407427, 5411963]          ["Berson, Elaine", "Leanza, Joann(swap names)"]      [50.98, 96.05]    [169394, 169393]                                   [2124181, 2081016]   ["Colton, Susan", "Kaufman, Beverly(swap names)"]   [1403.17, 2147.61]
188436            1049841    152631             3             2        2       15      120     -120     1 NT        S             7.14             3.50                  +1          8.00        5786             7        4861            A      4861           4228 2019-07-01 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     15.00     Monday Afternoon    [169365, 169366]                                   [2678314, 8900957]                   ["Lermer, Donald", "Schwartz, Jerome"]    [147.42, 177.96]    [169422, 169421]                                   [9899901, 5239060]     ["Buma, Haruko", "Scheiner, Harry(swap names)"]     [565.34, 239.68]
196206           15738389   2225661             2             2        2        1     -100      200      4 H        N             5.50             5.00                  -1          9.00       83486             5       68290            A     68284          55279 2020-01-07 00:00:00-06:00          100776      PAIRS         MATCH_POINTS      8.00    Tuesday Afternoon  [2557892, 2557893]                                   [1225510, 8350612]                   ["Sanandaji, Manda", "Luckey, Andrea"]   [667.36, 1548.37]  [2557906, 2557907]                                   [3624226, 9483128]                ["Singer, Martin", "Rodman, Gerald"]    [4949.24, 421.19]
202523           19493216   2740924             1             8        8        8      460     -460     3 NT        N             4.20             4.20                  +2         11.00      102752            22       85157            A     85157          67481 2020-01-30 00:00:00-06:00          100776      PAIRS         MATCH_POINTS      9.00   Thursday Afternoon  [3172383, 3172382]                                   [2005190, 5078547]     ["Beggs, Jonni", "Schaumberger, Sylvia(swap names)"]    [275.17, 422.63]  [3172401, 3172400]                                   [2644150, 2669293]     ["Levine, Martin", "Berkun, Allan(swap names)"]     [317.17, 192.98]
1181209          17845323   2512915             6             6        6        1      140     -140      2 S        N             2.00             5.50           CA     +1          9.00       94201            11       76977            D     76970          62102 2020-01-20 00:00:00-06:00          104034      PAIRS         MATCH_POINTS     17.00     Monday Afternoon  [2902116, 2902117]                                   [1726064, 3690806]              ["Kucheck, Riki", "Mullen-Barrett, Elaine"]     [152.96, 63.11]  [2902122, 2902123]                                   [3539083, 4097580]                ["Vogt, Jenny", "Greenwell, Mayako"]      [33.15, 334.73]
1181245          17845324   2512915             7             5        5        7      140     -170      3 S        N             0.00             5.50           D7     +1         10.00       94201            11       76977            D     76970          62102 2020-01-20 00:00:00-06:00          104034      PAIRS         MATCH_POINTS     17.00     Monday Afternoon  [2902114, 2902115]  [6896154, tmp:1333aa61-e5ed-4588-a6a7-f5cca594f416]                   ["Copeland, Alex", "Grahame, Lillian"]      [39.47, 436.0]  [2902134, 2902135]                                   [4981162, 5098874]              ["Gunther, Elaine", "Grantham, Kathy"]     [188.46, 435.27]
1181320          17845317   2512915             1             4        4        4      140     -140      2 S        N             2.00             5.50           HA     +1          9.00       94201            11       76977            D     76970          62102 2020-01-20 00:00:00-06:00          104034      PAIRS         MATCH_POINTS     17.00     Monday Afternoon  [2902112, 2902113]                                   [6896219, 7283970]                      ["Sheinwold, Marcy", "Worley, Ann"]    [130.71, 188.01]  [2902129, 2902128]                                   [1694421, 5780330]         ["Lam, CK", "Serafin, Marilyn(swap names)"]       [11.42, 23.82]
1181371          17845318   2512915             2             3        3        2      140     -140      2 S        N             2.00             5.50           D7     +1          9.00       94201            11       76977            D     76970          62102 2020-01-20 00:00:00-06:00          104034      PAIRS         MATCH_POINTS     17.00     Monday Afternoon  [2902111, 2902110]                                   [1077880, 2101033]          ["Fu, Tom Tsun-Sen", "Loh, Thomas(swap names)"]      [70.66, 434.7]  [2902124, 2902125]                                   [2637200, 8155771]                  ["Weisman, Ann", "Novack, JoAnne"]         [24.7, 5.02]
1189157          20116515   2826661             2             8        8        7      100     -100      6 S        W             0.07             6.83           HK     -1         11.00      105931            25       88189            D     88189          69450 2020-02-01 00:00:00-06:00          104034      PAIRS         MATCH_POINTS      9.50   Saturday Afternoon  [3274007, 3274006]                                   [2610124, 6501516]     ["Albright, Pamela Lee", "House, Reata(swap names)"]      [87.35, 690.7]  [3274022, 3274023]                                   [3110583, 4489764]               ["Norgaard, Janice", "Knowles, Mary"]     [384.07, 446.97]
1688662           5380663    770052             5             5        5        1     -620      620      5 C        W             0.00             0.00                  +1         12.00       29008            13       24348            B     24347          20630 2019-10-21 00:00:00-05:00          106765      PAIRS         MATCH_POINTS      5.50       Monday Evening    [870608, 870607]                                   [4102916, 5900840]            ["Moss, Linda", "Markunas, Rita(swap names)"]     [65.23, 157.92]    [870611, 870612]                                   [2160285, 2160293]                ["Crane, Kerrie", "Crane, Jonathan"]     [123.92, 131.69]
1688663           5380667    770053             5             5        5        1     -130      130      3 C        W             0.00             0.00                  +1         10.00       29008            14       24348            B     24347          20630 2019-10-21 00:00:00-05:00          106765      PAIRS         MATCH_POINTS      5.50       Monday Evening    [870608, 870607]                                   [4102916, 5900840]            ["Moss, Linda", "Markunas, Rita(swap names)"]     [65.23, 157.92]    [870611, 870612]                                   [2160285, 2160293]                ["Crane, Kerrie", "Crane, Jonathan"]     [123.92, 131.69]
1688664           5380671    770054             5             5        5        1     -300      300     1 NT        N             0.00             0.00                  -3          4.00       29008            15       24348            B     24347          20630 2019-10-21 00:00:00-05:00          106765      PAIRS         MATCH_POINTS      5.50       Monday Evening    [870608, 870607]                                   [4102916, 5900840]            ["Moss, Linda", "Markunas, Rita(swap names)"]     [65.23, 157.92]    [870611, 870612]                                   [2160285, 2160293]                ["Crane, Kerrie", "Crane, Jonathan"]     [123.92, 131.69]
1688665           5380675    770055             5             5        5        1      -50       50      4 S        N             0.00             0.00                  -1          9.00       29008            16       24348            B     24347          20630 2019-10-21 00:00:00-05:00          106765      PAIRS         MATCH_POINTS      5.50       Monday Evening    [870608, 870607]                                   [4102916, 5900840]            ["Moss, Linda", "Markunas, Rita(swap names)"]     [65.23, 157.92]    [870611, 870612]                                   [2160285, 2160293]                ["Crane, Kerrie", "Crane, Jonathan"]     [123.92, 131.69]
...                   ...       ...           ...           ...      ...      ...      ...      ...      ...      ...              ...              ...          ...    ...           ...         ...           ...         ...          ...       ...            ...                       ...             ...        ...                  ...       ...                  ...                 ...                                                  ...                                                      ...                 ...                 ...                                                  ...                                                 ...                  ...
51407148         10143826   1441443             2             2        2        1      -90       90     1 NT        W             0.50             0.50                   =          7.00       54072            24       44348            A     44342          35824 2019-11-20 00:00:00-06:00          276485      PAIRS         MATCH_POINTS      2.50    Wednesday Morning  [1646277, 1646278]  [9101047, tmp:58f1344a-4322-4223-9589-d8c37e5e875a]                    ["Baskin, Cynthia", "Baskin, Jeremy"]        [40.23, 4.0]  [1646282, 1646281]                                   [1230247, 4478827]        ["Wingo, Mary", "Zane, William(swap names)"]       [2.82, 3042.8]
51407149         10143813   1441436             3             1        1        2      450     -450      4 S        N             0.00             1.00                  +1         11.00       54072            17       44348            A     44342          35824 2019-11-20 00:00:00-06:00          276485      PAIRS         MATCH_POINTS      2.50    Wednesday Morning  [1646276, 1646275]  [2736098, tmp:ded7f3c3-c1ad-4c24-854c-5047b496a4b5]             ["Edmonds, James", "Meyer, Erv(swap names)"]     [363.33, 516.0]  [1646283, 1646284]                                   [4334310, 6248098]           ["Reilly, William", "Mooney, Jacquelinn"]        [54.89, 6.83]
51407150         10143815   1441437             3             1        1        2     -130      130      3 D        E             0.50             0.50                  +1         10.00       54072            18       44348            A     44342          35824 2019-11-20 00:00:00-06:00          276485      PAIRS         MATCH_POINTS      2.50    Wednesday Morning  [1646276, 1646275]  [2736098, tmp:ded7f3c3-c1ad-4c24-854c-5047b496a4b5]             ["Edmonds, James", "Meyer, Erv(swap names)"]     [363.33, 516.0]  [1646283, 1646284]                                   [4334310, 6248098]           ["Reilly, William", "Mooney, Jacquelinn"]        [54.89, 6.83]

In [43]:
# takes 4s
df.drop(df[drop_match_points].index,inplace=True)

In [44]:
assert df['ns_match_points'].notna().all()

In [45]:
# takes 3m30s
Club = df['club_id_number'].astype(str)
mae = [p[1][0] for p in df['club_session'].str.split(' ')] # Morning, Afternoon, Evening
Event = df['game_date'].dt.strftime('%y%m%d').astype(str)+mae
HandRecord = df['hand_record_id']
Board = df['board_number'].astype(str).str.zfill(2)
Key = Club+'_'+Event+'_'+Board
ClubDate = Club+'_'+Event
EventBoard = Event+'_'+Board
NSPair = df['section_name'].astype(str)+df['ns_pair'].astype(str).str.zfill(2)
EWPair = df['section_name'].astype(str)+df['ew_pair'].astype(str).str.zfill(2)
Pair = NSPair+'_'+EWPair
NNum = [p[0] for p in df['player_number_ns']]
NName = [p[0] for p in df['player_name_ns']]
SNum = [p[1] for p in df['player_number_ns']]
SName = [p[1] for p in df['player_name_ns']]
ENum = [p[0] for p in df['player_number_ew']]
EName = [p[0] for p in df['player_name_ew']]
WNum = [p[1] for p in df['player_number_ew']]
WName = [p[1] for p in df['player_name_ew']]
PairNS = ['_'.join(p) for p in df['player_number_ns']]
PairEW = ['_'.join(p) for p in df['player_number_ew']]
MP_NS = df['mp_total_ns']
MP_EW = df['mp_total_ew']
Score = df['ns_score']
Par = df['board_id'].map(pard)
MatchP = df['ns_match_points']
Pct = df['ns_match_points']/(df['ns_match_points']+df['ew_match_points']).round(1) # round(1) or round(2)?
contract = df['contract'].str.replace(' ','').str.upper().str.replace('NT','N') # remove spaces. force upper-case. replace NT with N.
contractdf = contract.str.extract(r'^(?P<BidLvl>\d)(?P<BidSuit>C|D|H|S|N)(?P<Dbl>X*)$')
BidLvl = contractdf['BidLvl']
BidSuit = contractdf['BidSuit']
Dbl = contractdf['Dbl']
NSEW = df['declarer']
Tricks = df['result'] # df['tricks_taken'] # -1, = +1, ...
EventBoardScore = EventBoard+'_'+Score

In [46]:
# attempting to free up some memory.
del df
import gc
gc.collect()

0

In [47]:
# takes 15s
Declarer = []
OnLead = []
Dummy = []
NotOnLead = []
for i,(d,n,e,s,w) in enumerate(zip(NSEW,NNum,ENum,SNum,WNum)):
    assert i == len(Declarer) and i == len(OnLead) and i == len(Dummy) and i == len(NotOnLead)
    if d == 'N':
        Declarer.append(n)
        OnLead.append(e)
        Dummy.append(s)
        NotOnLead.append(w)
    elif d == 'E':
        Declarer.append(e)
        OnLead.append(s)
        Dummy.append(w)
        NotOnLead.append(n)
    elif d == 'S':
        Declarer.append(s)
        OnLead.append(w)
        Dummy.append(n)
        NotOnLead.append(e)
    elif d == 'W':
        Declarer.append(w)
        OnLead.append(n)
        Dummy.append(e)
        NotOnLead.append(s)
    else: # d == nan
        Declarer.append(None)
        OnLead.append(None)
        Dummy.append(None)
        NotOnLead.append(None)
        #print(i,d,n,e,s,w)

In [48]:
# todo:
# cPairs, cFreq, cPct, cPairs299, cFreq299, cPct299, cKey?
# player table: NSEW-masterpoints, NSEW-power-rating, NSEW-rating, same for NS,EW pairs?

In [49]:
# takes 15s. 100s+1s/column?
df_dtypes = {
    'Key':"string",
    'ClubDate':"string",
    'EventBoard':"string",
    'HandRecord':"string", # UInt64?
    'Board':"string",
    'Pair':"string",
    'NNum':"string", # UInt8?
    'NName':"string",
    'SNum':"string", # UInt8?
    'SName':"string",
    'ENum':"string", # UInt8?
    'EName':"string",
    'WNum':"string", # UInt8?
    'WName':"string",
    'PairNS':"string",
    'PairEW':"string",
    'MP_NS':"object", # todo: do something else?
    'MP_EW':"object", # todo: do something else?
    'Score':"string",  # UInt8?
    'Par':"int16",
    'MatchP':"float32",
    'Pct':"float32",
    'NSPair':"string",
    'EWPair':"string",
    'BidLvl':"string", # UInt8, category?
    'BidSuit':"category",
    'Dbl':"category",
    'NSEW':"category",
    'Tricks':"string", # UInt8, category?
    'Declarer':"string", # UInt64?
    'OnLead':"string", # UInt64?
    'Dummy':"string", # UInt64?
    'NotOnLead':"string", # UInt64?
    'EventBoardScore':"string"
}

df_cols = {
    'Key':Key,
    'ClubDate':ClubDate,
    'EventBoard':EventBoard,
    'HandRecord':HandRecord,
    'Board':Board,
    'Pair':Pair,
    'NNum':NNum,
    'NName':NName,
    'SNum':SNum,
    'SName':SName,
    'ENum':ENum,
    'EName':EName,
    'WNum':WNum,
    'WName':WName,
    'PairNS':PairNS,
    'PairEW':PairEW,
    'MP_NS':MP_NS,
    'MP_EW':MP_EW,
    'Score':Score,
    'Par':Par,
    'MatchP':MatchP,
    'Pct':Pct,
    'NSPair':NSPair,
    'EWPair':EWPair,
    'BidLvl':BidLvl,
    'BidSuit':BidSuit,
    'Dbl':Dbl,
    'NSEW':NSEW,
    'Tricks':Tricks,
    'Declarer':Declarer,
    'OnLead':OnLead,
    'Dummy':Dummy,
    'NotOnLead':NotOnLead,
    'EventBoardScore':EventBoardScore
    }

assert set(df_cols.keys())-set(df_dtypes.keys()) == set()
df = pd.DataFrame(df_cols).astype(df_dtypes)
del df_cols
del df_dtypes

# alternative to df = pd.DataFrame(). Uses less memory?
#import pickle
#for k,v in df_cols.items():
#    tmp_file = acblPath.joinpath(k+'.tmp.pkl')
#    with open(tmp_file, 'wb') as f:
#        pickle.dump(v, f)

#with open(pickleFile, 'rb') as f:
#    optResultsDict = pickle.load(f)

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10246856 entries, 9294 to 52784548
Data columns (total 34 columns):
 #   Column           Dtype
---  ------           -----
 0   Key              string
 1   ClubDate         string
 2   EventBoard       string
 3   HandRecord       string
 4   Board            string
 5   Pair             string
 6   NNum             string
 7   NName            string
 8   SNum             string
 9   SName            string
 10  ENum             string
 11  EName            string
 12  WNum             string
 13  WName            string
 14  PairNS           string
 15  PairEW           string
 16  MP_NS            object
 17  MP_EW            object
 18  Score            string
 19  Par              int16
 20  MatchP           float32
 21  Pct              float32
 22  NSPair           string
 23  EWPair           string
 24  BidLvl           string
 25  BidSuit          category
 26  Dbl              category
 27  NSEW             category
 28  Tricks           string
 29  Declarer         string
 30  OnLead           string
 31  Dummy            string
 32  NotOnLead        string
 33  EventBoardScore  string
dtypes: category(3), float32(2), int16(1), object(2), string(26)
memory usage: 2.3+ GB

In [51]:
del Key
del ClubDate
del EventBoard
del HandRecord
del Board
del Pair
del NNum
del NName
del SNum
del SName
del ENum
del EName
del WNum
del WName
del PairNS
del PairEW
del MP_NS
del MP_EW
del Score
del Par
del MatchP
del Pct
del NSPair
del EWPair
del BidLvl
del BidSuit
del Dbl
del NSEW
del Tricks
del Declarer
del OnLead
del Dummy
del NotOnLead
del EventBoardScore
import gc
gc.collect()

0

In [52]:
# takes 1m
acbl_board_results_cleaned_filename = 'acbl-board-results-cleaned.pkl'
acbl_board_results_cleaned_file = acblPath.joinpath(acbl_board_results_cleaned_filename)
df.to_pickle(acbl_board_results_cleaned_file)

In [53]:
# attempting to free up some memory.
del df
import gc
gc.collect()

0

In [54]:
# takes 20s
acbl_board_results_cleaned_filename = 'acbl-board-results-cleaned.pkl'
acbl_board_results_cleaned_file = acblPath.joinpath(acbl_board_results_cleaned_filename)
df = pd.read_pickle(acbl_board_results_cleaned_file)
df

                        Key        ClubDate  EventBoard HandRecord Board     Pair     NNum                 NName     SNum                           SName     ENum                EName     WNum                            WName           PairNS           PairEW               MP_NS              MP_EW  Score  Par  MatchP  Pct NSPair EWPair BidLvl BidSuit Dbl NSEW Tricks Declarer   OnLead    Dummy NotOnLead   EventBoardScore
9294      100222_190821E_01  100222_190821E  190821E_01       8861    01  D02_D02  9264256         "Cook, Karen"  2961628        "Moore, Tom(swap names)"  7396295     "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  9264256_2961628  7396295_6497594   [170.09, 1815.45]  [104.69, 1832.54]   -100 -130    3.50 0.50    D02    D02      1       N        N     -2  9264256  7396295  2961628   6497594   190821E_01_-100
9295      100222_190821E_02  100222_190821E  190821E_02       8861    02  D02_D02  9264256         "Cook, Karen"  2961628        "Moore, Tom(swap names)"  7396295     "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  9264256_2961628  7396295_6497594   [170.09, 1815.45]  [104.69, 1832.54]    100 -450    5.00 0.71    D02    D02      4       D        W     -2  6497594  9264256  7396295   2961628    190821E_02_100
9296      100222_190821E_03  100222_190821E  190821E_03       8861    03  D02_D02  9264256         "Cook, Karen"  2961628        "Moore, Tom(swap names)"  7396295     "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  9264256_2961628  7396295_6497594   [170.09, 1815.45]  [104.69, 1832.54]   -100  110    1.00 0.14    D02    D02      6       D        S     -2  2961628  6497594  9264256   7396295   190821E_03_-100
9297      100222_190821E_04  100222_190821E  190821E_04       8861    04  D06_D02  5630401           "Long, Sam"  2670356                    "Dixon, Bob"  7396295     "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  5630401_2670356  7396295_6497594   [2580.01, 443.77]  [104.69, 1832.54]   -690  140    2.00 0.29    D06    D02      3       N        E     +3  7396295  2670356  6497594   5630401   190821E_04_-690
9298      100222_190821E_05  100222_190821E  190821E_05       8861    05  D06_D02  5630401           "Long, Sam"  2670356                    "Dixon, Bob"  7396295     "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  5630401_2670356  7396295_6497594   [2580.01, 443.77]  [104.69, 1832.54]    180  650    3.00 0.43    D06    D02      2       N        S     +2  2670356  6497594  5630401   7396295    190821E_05_180
9299      100222_190821E_06  100222_190821E  190821E_06       8861    06  D06_D02  5630401           "Long, Sam"  2670356                    "Dixon, Bob"  7396295     "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  5630401_2670356  7396295_6497594   [2580.01, 443.77]  [104.69, 1832.54]    460  200    6.50 0.93    D06    D02      3       N        N     +2  5630401  7396295  2670356   6497594    190821E_06_460
9300      100222_190821E_19  100222_190821E  190821E_19       8861    19  D05_D02  4458079     "Hacker, Rosalee"  4632036    "Burke, Charles(swap names)"  7396295     "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  4458079_4632036  7396295_6497594  [1336.91, 1957.22]  [104.69, 1832.54]    -50 -100    5.50 0.79    D05    D02      4       D        N     -1  4458079  7396295  4632036   6497594    190821E_19_-50
9301      100222_190821E_20  100222_190821E  190821E_20       8861    20  D05_D02  4458079     "Hacker, Rosalee"  4632036    "Burke, Charles(swap names)"  7396295     "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  4458079_4632036  7396295_6497594  [1336.91, 1957.22]  [104.69, 1832.54]    200  130    4.00 0.57    D05    D02      2       C        E     -2  7396295  4632036  6497594   4458079    190821E_20_200
9302      100222_190821E_21  100222_190821E  190821E_21       8861    21  D05_D02  4458079     "Hacker, Rosalee"  4632036    "Burke, Charles(swap names)"  7396295     "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  4458079_4632036  7396295_6497594  [1336.91, 1957.22]  [104.69, 1832.54]   -170 -120    4.00 0.57    D05    D02      3       H        W     +1  6497594  4458079  7396295   4632036   190821E_21_-170
9303      100222_190821E_07  100222_190821E  190821E_07       8861    07  D03_D02  2620499     "Walker, Mildred"  5378710    "Gilbreath, Sue(swap names)"  7396295     "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  2620499_5378710  7396295_6497594    [179.0, 1825.03]  [104.69, 1832.54]   -200  140    4.50 0.64    D03    D02      3       S        E     +2  7396295  5378710  6497594   2620499   190821E_07_-200
9304      100222_190821E_08  100222_190821E  190821E_08       8861    08  D03_D02  2620499     "Walker, Mildred"  5378710    "Gilbreath, Sue(swap names)"  7396295     "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  2620499_5378710  7396295_6497594    [179.0, 1825.03]  [104.69, 1832.54]   -150  660    1.50 0.21    D03    D02      4       D        W     +1  6497594  2620499  7396295   5378710   190821E_08_-150
9305      100222_190821E_09  100222_190821E  190821E_09       8861    09  D03_D02  2620499     "Walker, Mildred"  5378710    "Gilbreath, Sue(swap names)"  7396295     "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  2620499_5378710  7396295_6497594    [179.0, 1825.03]  [104.69, 1832.54]    130  140    4.50 0.64    D03    D02      3       D        N     +1  2620499  7396295  5378710   6497594    190821E_09_130
9306      100222_190821E_22  100222_190821E  190821E_22       8861    22  D01_D02  3224783        "Long, Ramona"  4534859    "Moore, Dorothy(swap names)"  7396295     "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  3224783_4534859  7396295_6497594    [368.5, 1501.34]  [104.69, 1832.54]   -110 -420    4.50 0.64    D01    D02      2       D        E     +1  7396295  4534859  6497594   3224783   190821E_22_-110
9307      100222_190821E_23  100222_190821E  190821E_23       8861    23  D01_D02  3224783        "Long, Ramona"  4534859    "Moore, Dorothy(swap names)"  7396295     "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  3224783_4534859  7396295_6497594    [368.5, 1501.34]  [104.69, 1832.54]    300  980    6.00 0.86    D01    D02      4       H        E     -3  7396295  4534859  6497594   3224783    190821E_23_300
9308      100222_190821E_24  100222_190821E  190821E_24       8861    24  D01_D02  3224783        "Long, Ramona"  4534859    "Moore, Dorothy(swap names)"  7396295     "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  3224783_4534859  7396295_6497594    [368.5, 1501.34]  [104.69, 1832.54]    480  980    5.00 0.71    D01    D02      4       S        N     +2  3224783  7396295  4534859   6497594    190821E_24_480
9309      100222_190821E_16  100222_190821E  190821E_16       8861    16  D08_D02  8247099  "McDonald, Jeanette"  4639987    "Hirsch, Margot(swap names)"  7396295     "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  8247099_4639987  7396295_6497594   [811.61, 3635.64]  [104.69, 1832.54]  -1440 -500    0.00 0.00    D08    D02      6       N        E      =  7396295  4639987  6497594   8247099  190821E_16_-1440
9310      100222_190821E_17  100222_190821E  190821E_17       8861    17  D08_D02  8247099  "McDonald, Jeanette"  4639987    "Hirsch, Margot(swap names)"  7396295     "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  8247099_4639987  7396295_6497594   [811.61, 3635.64]  [104.69, 1832.54]    430  430    6.00 0.86    D08    D02      3       N        S     +1  4639987  6497594  8247099   7396295    190821E_17_430
9311      100222_190821E_18  100222_190821E  190821E_18       8861    18  D08_D02  8247099  "McDonald, Jeanette"  4639987    "Hirsch, Margot(swap names)"  7396295     "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  8247099_4639987  7396295_6497594   [811.61, 3635.64]  [104.69, 1832.54]    680  420    6.00 0.86    D08    D02      4       S        N     +2  8247099  7396295  4639987   6497594    190821E_18_680
9312      100222_190821E_13  100222_190821E  190821E_13       8861    13  D04_D02  7950985     "Jaeger, Georgie"  2494566      "Clark, Melba(swap names)"  7396295     "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  7950985_2494566  7396295_6497594   [3039.24, 1239.3]  [104.69, 1832.54]   -130  980    2.00 0.29    D04    D02      2       C        W     +2  6497594  7950985  7396295   2494566   190821E_13_-130
9313      100222_190821E_14  100222_190821E  190821E_14       8861    14  D04_D02  7950985     "Jaeger, Georgie"  2494566      "Clark, Melba(swap names)"  7396295     "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  7950985_2494566  7396295_6497594   [3039.24, 1239.3]  [104.69, 1832.54]    550  420    7.00 1.00    D04    D02      5       C   X    N      =  7950985  7396295  2494566   6497594    190821E_14_550
9314      100222_190821E_15  100222_190821E  190821E_15       8861    15  D04_D02  7950985     "Jaeger, Georgie"  2494566      "Clark, Melba(swap names)"  7396295     "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  7950985_2494566  7396295_6497594   [3039.24, 1239.3]  [104.69, 1832.54]   -420  450    3.50 0.50    D04    D02      4       H        E      =  7396295  2494566  6497594   7950985   190821E_15_-420
9315      100222_190821E_10  100222_190821E  190821E_10       8861    10  D07_D02  9564861         "Hill, Wilma"  7958544  "Buchanan, Robert(swap names)"  7396295     "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  9564861_7958544  7396295_6497594   [294.15, 3371.16]  [104.69, 1832.54]   -630 -130    0.50 0.07    D07    D02      3       N        E     +1  7396295  7958544  6497594   9564861   190821E_10_-630
9316      100222_190821E_11  100222_190821E  190821E_11       8861    11  D07_D02  9564861         "Hill, Wilma"  7958544  "Buchanan, Robert(swap names)"  7396295     "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  9564861_7958544  7396295_6497594   [294.15, 3371.16]  [104.69, 1832.54]   -400  140    0.00 0.00    D07    D02      3       N        W      =  6497594  9564861  7396295   7958544   190821E_11_-400
9317      100222_190821E_12  100222_190821E  190821E_12       8861    12  D07_D02  9564861         "Hill, Wilma"  7958544  "Buchanan, Robert(swap names)"  7396295     "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  9564861_7958544  7396295_6497594   [294.15, 3371.16]  [104.69, 1832.54]     50  140    4.00 0.57    D07    D02      3       H        E     -1  7396295  7958544  6497594   9564861     190821E_12_50
9318      100222_190821E_04  100222_190821E  190821E_04       8861    04  D02_D01  9264256         "Cook, Karen"  2961628        "Moore, Tom(swap names)"  5756464       "Petry, Susan"  4512405        "Floyd, Judy(swap names)"  9264256_2961628  5756464_4512405   [170.09, 1815.45]  [129.48, 1287.43]   -690  140    2.00 0.29    D02    D01      3       N        E     +3  5756464  2961628  4512405   9264256   190821E_04_-690
...                     ...             ...         ...        ...   ...      ...      ...                   ...      ...                             ...      ...                  ...      ...                              ...              ...              ...                 ...                ...    ...  ...     ...  ...    ...    ...    ...     ...  ..  ...    ...      ...      ...      ...       ...               ...
52784524  905497_200222A_12  905497_200222A  200222A_12      81204    12  C02_C09  2662159  "Sonnenshein, Linda"  4778723                  "Durra, Joyce"  3920836  "Frinell, Patricia"  7395477      "Weidner, Noel(swap names)"  2662159_4778723  3920836_7395477     [64.24, 142.74]   [268.95, 111.84]    150  100    6.50 0.43    C02    C09      2       C        S     +3  4778723  7395477  2662159   3920836    200222A_12_150
52784525  905497_200222A_04  905497_200222A  200222A_04      81204    04  C06_C01  1437674       "Hermann, Bill"  9044949                  "Hermann, Pat"  7739168      "Thomas, Cindy"  9095454  "Sonnenshein, Mona(swap names)"  1437674_9044949  7739168_9095454       [8.13, 45.94]      [6.71, 23.89]   -140  990    6.50 0.43    C06    C01      3       H        W      =  9095454  1437674  7739168   9044949   200222A_04_-140
52784526  905497_200222A_05  905497_200222A  200222A_05      81204    05  C06_C01  1437674       "Hermann, Bill"  9044949                  "Hermann, Pat"  7739168      "Thomas, Cindy"  9095454  "Sonnenshein, Mona(swap names)"  1437674_9044949  7739168_9095454       [8.13, 45.94]      [6.71, 23.89]    200 -300    7.50 0.50    C06    C01      2       H        S     +3  9044949  9095454  1437674   7739168    200222A_05_200
52784527  905497_200222A_06  905497_200222A  200222A_06      81204    06  C06_C01  1437674       "Hermann, Bill"  9044949                  "Hermann, Pat"  7739168      "Thomas, Cindy"  9095454  "Sonnenshein, Mona(swap names)"  1437674_9044949  7739168_9095454       [8.13, 45.94]      [6.71, 23.89]    -50  420   11.50 0.77    C06    C01      3       N        S     -1  9044949  9095454  1437674   7739168    200222A_06_-50
52784528  905497_200222A_01  905497_200222A  200222A_01      81204    01  C01_C01  7441290    "Feingold, Sharon"  7441444                 "Mueller, Skip"  7739168      "Thomas, Cindy"  9095454  "Sonnenshein, Mona(swap names)"  7441290_7441444  7739168_9095454      [28.15, 25.73]      [6.71, 23.89]    150  990   15.00 1.00    C01    C01      2       C        W     -3  9095454  7441290  7739168   7441444    200222A_01_150
52784529  905497_200222A_02  905497_200222A  200222A_02      81204    02  C01_C01  7441290    "Feingold, Sharon"  7441444                 "Mueller, Skip"  7739168      "Thomas, Cindy"  9095454  "Sonnenshein, Mona(swap names)"  7441290_7441444  7739168_9095454      [28.15, 25.73]      [6.71, 23.89]    130 -630    9.50 0.63    C01    C01      3       C        N     +1  7441290  7739168  7441444   9095454    200222A_02_130
52784530  905497_200222A_03  905497_200222A  200222A_03      81204    03  C01_C01  7441290    "Feingold, Sharon"  7441444                 "Mueller, Skip"  7739168      "Thomas, Cindy"  9095454  "Sonnenshein, Mona(swap names)"  7441290_7441444  7739168_9095454      [28.15, 25.73]      [6.71, 23.89]    200 -600   14.50 0.97    C01    C01      2       N        W     -2  9095454  7441290  7739168   7441444    200222A_03_200
52784531  905497_200222A_19  905497_200222A  200222A_19      81204    19  C04_C01  7326548      "Winkler, Selby"  9082395                 "Duncan, Paula"  7739168      "Thomas, Cindy"  9095454  "Sonnenshein, Mona(swap names)"  7326548_9082395  7739168_9095454    [124.29, 203.37]      [6.71, 23.89]   -100  -80    7.50 0.50    C04    C01      4       D        N     -2  7326548  7739168  9082395   9095454   200222A_19_-100
52784532  905497_200222A_20  905497_200222A  200222A_20      81204    20  C04_C01  7326548      "Winkler, Selby"  9082395                 "Duncan, Paula"  7739168      "Thomas, Cindy"  9095454  "Sonnenshein, Mona(swap names)"  7326548_9082395  7739168_9095454    [124.29, 203.37]      [6.71, 23.89]    620  500   14.50 0.97    C04    C01      4       S        S      =  9082395  9095454  7326548   7739168    200222A_20_620
52784533  905497_200222A_21  905497_200222A  200222A_21      81204    21  C04_C01  7326548      "Winkler, Selby"  9082395                 "Duncan, Paula"  7739168      "Thomas, Cindy"  9095454  "Sonnenshein, Mona(swap names)"  7326548_9082395  7739168_9095454    [124.29, 203.37]      [6.71, 23.89]    180  600   10.00 0.67    C04    C01      2       N        S     +2  9082395  9095454  7326548   7739168    200222A_21_180
52784534  905497_200222A_13  905497_200222A  200222A_13      81204    13  C03_C01  1371185     "Astamendi, Judy"  1992244                     "Amini, BJ"  7739168      "Thomas, Cindy"  9095454  "Sonnenshein, Mona(swap names)"  1371185_1992244  7739168_9095454    [223.12, 100.27]      [6.71, 23.89]    110  140   12.50 0.83    C03    C01      2       H        N      =  1371185  7739168  1992244   9095454    200222A_13_110
52784535  905497_200222A_14  905497_200222A  200222A_14      81204    14  C03_C01  1371185     "Astamendi, Judy"  1992244                     "Amini, BJ"  7739168      "Thomas, Cindy"  9095454  "Sonnenshein, Mona(swap names)"  1371185_1992244  7739168_9095454    [223.12, 100.27]      [6.71, 23.89]    -50 -430    6.50 0.43    C03    C01      4       S        N     -1  1371185  7739168  1992244   9095454    200222A_14_-50
52784536  905497_200222A_15  905497_200222A  200222A_15      81204    15  C03_C01  1371185     "Astamendi, Judy"  1992244                     "Amini, BJ"  7739168      "Thomas, Cindy"  9095454  "Sonnenshein, Mona(swap names)"  1371185_1992244  7739168_9095454    [223.12, 100.27]      [6.71, 23.89]   -170  100   10.50 0.70    C03    C01      3       H        W     +1  9095454  1371185  7739168   1992244   200222A_15_-170
52784537  905497_200222A_16  905497_200222A  200222A_16      81204    16  C08_C01  2573113   "Showalter, Stuart"  5774942                 "Abrams, David"  7739168      "Thomas, Cindy"  9095454  "Sonnenshein, Mona(swap names)"  2573113_5774942  7739168_9095454      [115.32, 3.07]      [6.71, 23.89]    450  100   10.50 0.70    C08    C01      4       S        S     +1  5774942  9095454  2573113   7739168    200222A_16_450
52784538  905497_200222A_17  905497_200222A  200222A_17      81204    17  C08_C01  2573113   "Showalter, Stuart"  5774942                 "Abrams, David"  7739168      "Thomas, Cindy"  9095454  "Sonnenshein, Mona(swap names)"  2573113_5774942  7739168_9095454      [115.32, 3.07]      [6.71, 23.89]    100  100    1.00 0.07    C08    C01      3       S        E     -2  7739168  5774942  9095454   2573113    200222A_17_100
52784539  905497_200222A_18  905497_200222A  200222A_18      81204    18  C08_C01  2573113   "Showalter, Stuart"  5774942                 "Abrams, David"  7739168      "Thomas, Cindy"  9095454  "Sonnenshein, Mona(swap names)"  2573113_5774942  7739168_9095454      [115.32, 3.07]      [6.71, 23.89]   -140 -110    3.50 0.23    C08    C01      1       H        E     +2  7739168  5774942  9095454   2573113   200222A_18_-140
52784540  905497_200222A_10  905497_200222A  200222A_10      81204    10  C07_C01  1437739     "Robzyk, Phillip"  7116861              "Haine, J Stephen"  7739168      "Thomas, Cindy"  9095454  "Sonnenshein, Mona(swap names)"  1437739_7116861  7739168_9095454    [168.75, 311.56]      [6.71, 23.89]    200 -130    8.00 0.53    C07    C01      4       S        E     -2  7739168  7116861  9095454   1437739    200222A_10_200
52784541  905497_200222A_11  905497_200222A  200222A_11      81204    11  C07_C01  1437739     "Robzyk, Phillip"  7116861              "Haine, J Stephen"  7739168      "Thomas, Cindy"  9095454  "Sonnenshein, Mona(swap names)"  1437739_7116861  7739168_9095454    [168.75, 311.56]      [6.71, 23.89]     50  -90   12.50 0.83    C07    C01      1       N        W     -1  9095454  1437739  7739168   7116861     200222A_11_50
52784542  905497_200222A_12  905497_200222A  200222A_12      81204    12  C07_C01  1437739     "Robzyk, Phillip"  7116861              "Haine, J Stephen"  7739168      "Thomas, Cindy"  9095454  "Sonnenshein, Mona(swap names)"  1437739_7116861  7739168_9095454    [168.75, 311.56]      [6.71, 23.89]    660  100   14.00 0.93    C07    C01      3       N        S     +2  7116861  9095454  1437739   7739168    200222A_12_660
52784543  905497_200222A_25  905497_200222A  200222A_25      81204    25  C05_C01  2627647    "Reinbold, Joella"  5222125                 "Kaufman, Fred"  7739168      "Thomas, Cindy"  9095454  "Sonnenshein, Mona(swap names)"  2627647_5222125  7739168_9095454    [188.08, 171.05]      [6.71, 23.89]    450  660    9.50 0.63    C05    C01      4       H        N     +1  2627647  7739168  5222125   9095454    200222A_25_450

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10246856 entries, 9294 to 52784548
Data columns (total 34 columns):
 #   Column           Dtype
---  ------           -----
 0   Key              string
 1   ClubDate         string
 2   EventBoard       string
 3   HandRecord       string
 4   Board            string
 5   Pair             string
 6   NNum             string
 7   NName            string
 8   SNum             string
 9   SName            string
 10  ENum             string
 11  EName            string
 12  WNum             string
 13  WName            string
 14  PairNS           string
 15  PairEW           string
 16  MP_NS            object
 17  MP_EW            object
 18  Score            string
 19  Par              int16
 20  MatchP           float32
 21  Pct              float32
 22  NSPair           string
 23  EWPair           string
 24  BidLvl           string
 25  BidSuit          category
 26  Dbl              category
 27  NSEW             category
 28  Tricks           string
 29  Declarer         string
 30  OnLead           string
 31  Dummy            string
 32  NotOnLead        string
 33  EventBoardScore  string
dtypes: category(3), float32(2), int16(1), object(2), string(26)
memory usage: 2.3+ GB