In [1]:
# takes 10m
# warning: Requires LOTS of memory and pagefile space. I use 64GB of memory and 32GB+ pagefile.
# warning: Be sure all other apps and windows are closed. You've been warned!
# Data clean acbl board results and write df to file. 

# next steps:
# perform experiments on board results.

# previous steps:
# acbl-sql-to-board-results.ipynb

# todo:
# todo: why are there 24m board_ids not found. Why is that?
# change some dtypes from string to category. Most dytpe of category should be changed to ordered.

In [2]:
# requirements
# Requires LOTS of memory and pagefile space. I use 64GB of memory and 32GB+ pagefile.
# Be sure all other apps and windows are closed. You've been warned!
# If browser/system misbehaves, its probably due to lack of memory and/or pagefile space.
# Jupyter's output console may/may-not output a message about lack of memory/pagefile space.
# Instructions at: https://www.windowscentral.com/how-change-virtual-memory-size-windows-10

In [3]:
import pandas as pd
import pathlib
import mlBridgeLib

In [4]:
# override pandas display options
mlBridgeLib.pd_options_display()

In [5]:
rootPath = pathlib.Path('e:/bridge/data')
acblPath = rootPath.joinpath('acbl')

In [6]:
# takes 1m15s
board_results_file = acblPath.joinpath('acbl-board-results.pkl')
df = pd.read_pickle(board_results_file)
df

          board_result_id  board_id  round_number  table_number  ns_pair  ew_pair ns_score ew_score contract declarer  ew_match_points  ns_match_points opening_lead result  tricks_taken  section_id  board_number  session_id section_name  event_id hand_record_id                 game_date  club_id_number event_type board_scoring_method  tb_count         club_session          player_id_ns                                                                      player_number_ns                                    player_name_ns         mp_total_ns          player_id_ew                                                                      player_number_ew                                  player_name_ew         mp_total_ew
0                29145890   4065740          <NA>          <NA>        1        1     -140      140       2S        W             4.50             1.50          NaN   None           NaN      155573             1      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832775, 4832776]  [tmp:995300bb-6081-4285-a93a-9342d2e7bc1b, tmp:a659aa2e-1428-4ea4-87d3-581db1c2dfad]                        ["sunfeather", "jakspade"]          [nan, nan]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
1                29145897   4065741          <NA>          <NA>        1        1      650     -650       5H        N             2.50             3.50          NaN   None           NaN      155573             2      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832775, 4832776]  [tmp:995300bb-6081-4285-a93a-9342d2e7bc1b, tmp:a659aa2e-1428-4ea4-87d3-581db1c2dfad]                        ["sunfeather", "jakspade"]          [nan, nan]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
2                29145904   4065742          <NA>          <NA>        1        1      100     -100       3N        W             2.00             4.00          NaN   None           NaN      155573             3      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832775, 4832776]  [tmp:995300bb-6081-4285-a93a-9342d2e7bc1b, tmp:a659aa2e-1428-4ea4-87d3-581db1c2dfad]                        ["sunfeather", "jakspade"]          [nan, nan]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
3                29145956   4065749          <NA>          <NA>        4        1     -140      140       2H        W             3.50             2.50          NaN   None           NaN      155573            10      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832788, 4832787]  [tmp:05fb8b01-1366-4fc8-9bb4-13c7f6f012a7, tmp:abf67235-1e01-4f8e-a927-95be148ea12f]               ["valqtown", "whqtown(swap names)"]          [nan, nan]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
4                29145963   4065750          <NA>          <NA>        4        1      480     -480       4S        S             0.50             5.50          NaN   None           NaN      155573            11      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832788, 4832787]  [tmp:05fb8b01-1366-4fc8-9bb4-13c7f6f012a7, tmp:abf67235-1e01-4f8e-a927-95be148ea12f]               ["valqtown", "whqtown(swap names)"]          [nan, nan]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
5                29145970   4065751          <NA>          <NA>        4        1      -90       90       1N        E             1.00             5.00          NaN   None           NaN      155573            12      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832788, 4832787]  [tmp:05fb8b01-1366-4fc8-9bb4-13c7f6f012a7, tmp:abf67235-1e01-4f8e-a927-95be148ea12f]               ["valqtown", "whqtown(swap names)"]          [nan, nan]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
6                29146000   4065755          <NA>          <NA>        6        1     -620      620       4S        W             5.00             1.00          NaN   None           NaN      155573            16      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832795, 4832796]                                                                    [1015699, 6996043]                  ["Maureen Larson", "Ben Levine"]    [1078.3, 309.88]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
7                29146007   4065756          <NA>          <NA>        6        1     -150      150       2D        N             4.50             1.50          NaN   None           NaN      155573            17      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832795, 4832796]                                                                    [1015699, 6996043]                  ["Maureen Larson", "Ben Levine"]    [1078.3, 309.88]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
8                29146014   4065757          <NA>          <NA>        6        1      100     -100      5DX        W             0.00             6.00          NaN   None           NaN      155573            18      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832795, 4832796]                                                                    [1015699, 6996043]                  ["Maureen Larson", "Ben Levine"]    [1078.3, 309.88]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
9                29145978   4065752          <NA>          <NA>        5        1     -110      110       2S        W             3.50             2.50          NaN   None           NaN      155573            13      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832792, 4832791]                                                                    [5231051, 9311599]  ["Jeff Rowland", "Shirley Campbell(swap names)"]       [56.6, 128.2]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
10               29145985   4065753          <NA>          <NA>        5        1      -50       50       3S        S             3.00             3.00          NaN   None           NaN      155573            14      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832792, 4832791]                                                                    [5231051, 9311599]  ["Jeff Rowland", "Shirley Campbell(swap names)"]       [56.6, 128.2]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
11               29145992   4065754          <NA>          <NA>        5        1     -100      100       4H        S             3.50             2.50          NaN   None           NaN      155573            15      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832792, 4832791]                                                                    [5231051, 9311599]  ["Jeff Rowland", "Shirley Campbell(swap names)"]       [56.6, 128.2]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
12               29145912   4065743          <NA>          <NA>        2        1      660     -660       3N        N             0.00             6.00          NaN   None           NaN      155573             4      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832779, 4832780]                                                                    [4029062, 6694985]                     ["John Perry", "Julie Perry"]  [1161.82, 1034.52]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
13               29145919   4065744          <NA>          <NA>        2        1      170     -170       2S        S             0.00             6.00          NaN   None           NaN      155573             5      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832779, 4832780]                                                                    [4029062, 6694985]                     ["John Perry", "Julie Perry"]  [1161.82, 1034.52]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
14               29145926   4065745          <NA>          <NA>        2        1      140     -140       2H        N             2.50             2.50          NaN   None           NaN      155573             6      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832779, 4832780]                                                                    [4029062, 6694985]                     ["John Perry", "Julie Perry"]  [1161.82, 1034.52]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
15               29145934   4065746          <NA>          <NA>        3        1     -200      200       5C        S             6.00             0.00          NaN   None           NaN      155573             7      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832783, 4832784]                                                                    [2745771, 2745771]                    ["Sandy Pyatt", "Sandy Pyatt"]        [2.41, 2.41]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
16               29145941   4065747          <NA>          <NA>        3        1      170     -170       3H        N             1.50             4.50          NaN   None           NaN      155573             8      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832783, 4832784]                                                                    [2745771, 2745771]                    ["Sandy Pyatt", "Sandy Pyatt"]        [2.41, 2.41]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
17               29145948   4065748          <NA>          <NA>        3        1     -130      130       3D        E             6.00             0.00          NaN   None           NaN      155573             9      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832783, 4832784]                                                                    [2745771, 2745771]                    ["Sandy Pyatt", "Sandy Pyatt"]        [2.41, 2.41]    [4832778, 4832777]                                                                    [1872419, 1872427]    ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
18               29145911   4065743          <NA>          <NA>        1        7      620     -620       4H        S             1.00             5.00          NaN   None           NaN      155573             4      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832775, 4832776]  [tmp:995300bb-6081-4285-a93a-9342d2e7bc1b, tmp:a659aa2e-1428-4ea4-87d3-581db1c2dfad]                        ["sunfeather", "jakspade"]          [nan, nan]    [4832802, 4832801]  [tmp:45d2e796-3ff4-4227-a227-0263a650615c, tmp:72d12c14-20e3-4fa8-9e78-2808beeaf9f9]           ["dixie_j", "driverbrya(swap names)"]          [nan, nan]
19               29145918   4065744          <NA>          <NA>        1        7     -200      200       4H        N             5.00             1.00          NaN   None           NaN      155573             5      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832775, 4832776]  [tmp:995300bb-6081-4285-a93a-9342d2e7bc1b, tmp:a659aa2e-1428-4ea4-87d3-581db1c2dfad]                        ["sunfeather", "jakspade"]          [nan, nan]    [4832802, 4832801]  [tmp:45d2e796-3ff4-4227-a227-0263a650615c, tmp:72d12c14-20e3-4fa8-9e78-2808beeaf9f9]           ["dixie_j", "driverbrya(swap names)"]          [nan, nan]
20               29145925   4065745          <NA>          <NA>        1        7      400     -400       2S        W             0.00             5.00          NaN   None           NaN      155573             6      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832775, 4832776]  [tmp:995300bb-6081-4285-a93a-9342d2e7bc1b, tmp:a659aa2e-1428-4ea4-87d3-581db1c2dfad]                        ["sunfeather", "jakspade"]          [nan, nan]    [4832802, 4832801]  [tmp:45d2e796-3ff4-4227-a227-0263a650615c, tmp:72d12c14-20e3-4fa8-9e78-2808beeaf9f9]           ["dixie_j", "driverbrya(swap names)"]          [nan, nan]
21               29145977   4065752          <NA>          <NA>        4        7     -110      110       1S        W             3.50             2.50          NaN   None           NaN      155573            13      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832788, 4832787]  [tmp:05fb8b01-1366-4fc8-9bb4-13c7f6f012a7, tmp:abf67235-1e01-4f8e-a927-95be148ea12f]               ["valqtown", "whqtown(swap names)"]          [nan, nan]    [4832802, 4832801]  [tmp:45d2e796-3ff4-4227-a227-0263a650615c, tmp:72d12c14-20e3-4fa8-9e78-2808beeaf9f9]           ["dixie_j", "driverbrya(swap names)"]          [nan, nan]
22               29145984   4065753          <NA>          <NA>        4        7     -100      100       1D        N             6.00             0.00          NaN   None           NaN      155573            14      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832788, 4832787]  [tmp:05fb8b01-1366-4fc8-9bb4-13c7f6f012a7, tmp:abf67235-1e01-4f8e-a927-95be148ea12f]               ["valqtown", "whqtown(swap names)"]          [nan, nan]    [4832802, 4832801]  [tmp:45d2e796-3ff4-4227-a227-0263a650615c, tmp:72d12c14-20e3-4fa8-9e78-2808beeaf9f9]           ["dixie_j", "driverbrya(swap names)"]          [nan, nan]
23               29145991   4065754          <NA>          <NA>        4        7      620     -620       4H        S             0.50             5.50          NaN   None           NaN      155573            15      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832788, 4832787]  [tmp:05fb8b01-1366-4fc8-9bb4-13c7f6f012a7, tmp:abf67235-1e01-4f8e-a927-95be148ea12f]               ["valqtown", "whqtown(swap names)"]          [nan, nan]    [4832802, 4832801]  [tmp:45d2e796-3ff4-4227-a227-0263a650615c, tmp:72d12c14-20e3-4fa8-9e78-2808beeaf9f9]           ["dixie_j", "driverbrya(swap names)"]          [nan, nan]
24               29145999   4065755          <NA>          <NA>        5        7     -140      140       2S        W             1.00             5.00          NaN   None           NaN      155573            16      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00    Wednesday Evening    [4832792, 4832791]                                                                    [5231051, 9311599]  ["Jeff Rowland", "Shirley Campbell(swap names)"]       [56.6, 128.2]    [4832802, 4832801]  [tmp:45d2e796-3ff4-4227-a227-0263a650615c, tmp:72d12c14-20e3-4fa8-9e78-2808beeaf9f9]           ["dixie_j", "driverbrya(swap names)"]          [nan, nan]
...                   ...       ...           ...           ...      ...      ...      ...      ...      ...      ...              ...              ...          ...    ...           ...         ...           ...         ...          ...       ...            ...                       ...             ...        ...                  ...       ...                  ...                   ...                                                                                   ...                                               ...                 ...                   ...                                                                                   ...                                             ...                 ...

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50983522 entries, 0 to 50983521
Data columns (total 35 columns):
 #   Column                Dtype
---  ------                -----
 0   board_result_id       UInt64
 1   board_id              UInt64
 2   round_number          UInt8
 3   table_number          UInt8
 4   ns_pair               UInt8
 5   ew_pair               UInt8
 6   ns_score              object
 7   ew_score              object
 8   contract              category
 9   declarer              category
 10  ew_match_points       float32
 11  ns_match_points       float32
 12  opening_lead          category
 13  result                object
 14  tricks_taken          float32
 15  section_id            UInt64
 16  board_number          UInt8
 17  session_id            UInt64
 18  section_name          category
 19  event_id              UInt64
 20  hand_record_id        object
 21  game_date             datetime64[ns, US/Central]
 22  club_id_number        UInt64
 23  event_type            category
 24  board_scoring_method  category
 25  tb_count              float32
 26  club_session          category
 27  player_id_ns          object
 28  player_number_ns      object
 29  player_name_ns        object
 30  mp_total_ns           object
 31  player_id_ew          object
 32  player_number_ew      object
 33  player_name_ew        object
 34  mp_total_ew           object
dtypes: UInt64(6), UInt8(5), category(7), datetime64[ns, US/Central](1), float32(4), object(12)
memory usage: 9.5+ GB

In [8]:
# takes 20s
# drop rows where important columns are nulls.
columns_which_must_not_have_nulls = ['contract','declarer','ew_match_points','ns_match_points']
isnulldf = df.isnull()
columns_containing_nulls = isnulldf.columns[isnulldf.any()]
columns_containing_nulls = columns_containing_nulls.intersection(columns_which_must_not_have_nulls) # intersection of null columns and disallowed columns
rows_containing_nulls = df[isnulldf[columns_containing_nulls].any(axis='columns')].index
only_nulls_df = df.loc[rows_containing_nulls][columns_containing_nulls]
only_nulls_df

         contract declarer  ew_match_points  ns_match_points
33           PASS      NaN             1.00             5.00
53            A==      NaN             3.00             3.00
69           PASS      NaN             5.00             1.00
315          PASS      NaN             1.00             7.00
356           A==      NaN             4.00             4.00
457          PASS      NaN             2.50             5.50
526          PASS      NaN             2.50             5.50
534          PASS      NaN             7.00             1.00
542          PASS      NaN             7.00             1.00
564           A-=      NaN             4.00             3.20
668           A==      NaN             4.00             4.00
974           A==      NaN             4.00             4.00
1039         PASS      NaN             4.00             4.00
1062           4C        N              NaN              NaN
1063           4S        E              NaN              NaN
1064           1N        N              NaN              NaN
1065           3C        N              NaN              NaN
1066           3N        N              NaN              NaN
1067           2S        N              NaN              NaN
1068         PASS      NaN              NaN              NaN
1069           5C        E              NaN              NaN
1070           4H        N              NaN              NaN
1071           4S        N              NaN              NaN
1072           5D        S              NaN              NaN
1073           2N        E              NaN              NaN
...           ...      ...              ...              ...
50983473      NaN      NaN             1.50             1.50
50983474      NaN      NaN             0.00             3.00
50983475      NaN      NaN             2.50             0.50
50983476      NaN      NaN             2.50             0.50
50983477      NaN      NaN             0.50             2.50
50983478      NaN      NaN             2.00             1.00
50983479      NaN      NaN             0.50             2.50
50983480      NaN      NaN             0.00             3.00
50983481      NaN      NaN             2.00             1.00
50983482      NaN      NaN             1.50             1.50
50983483      NaN      NaN             1.50             1.50
50983484      NaN      NaN             2.00             1.00
50983485      NaN      NaN             1.00             2.00
50983486      NaN      NaN             2.00             1.00
50983487      NaN      NaN             1.00             2.00
50983488      NaN      NaN             3.00             0.00
50983489      NaN      NaN             2.00             1.00
50983490      NaN      NaN             2.00             1.00
50983491      NaN      NaN             3.00             0.00
50983492      NaN      NaN             0.00             3.00
50983493      NaN      NaN             1.00             2.00
50983494      NaN      NaN             2.00             1.00
50983495      NaN      NaN             3.00             0.00
50983496      NaN      NaN             0.50             2.50
50983497      NaN      NaN             0.50             2.50

[3831214 rows x 4 columns]

In [9]:
# takes 20s
# drop rows containing nulls
df.drop(rows_containing_nulls,inplace=True)

In [10]:
# takes 10s
# todo: earlier in the pipeline, make HandRecord with None into NA so they will be filtered out by NA drop above.
# drop rows, currently 11M, containing non-numeric HandRecords. They're mostly SHUFFLE.
drop_handrecords = ~df['hand_record_id'].str.isnumeric()
df[drop_handrecords]

          board_result_id  board_id  round_number  table_number  ns_pair  ew_pair ns_score ew_score contract declarer  ew_match_points  ns_match_points opening_lead result  tricks_taken  section_id  board_number  session_id section_name  event_id hand_record_id                 game_date  club_id_number event_type board_scoring_method  tb_count       club_session        player_id_ns                                                                      player_number_ns                                    player_name_ns         mp_total_ns        player_id_ew                                                                      player_number_ew                                player_name_ew         mp_total_ew
0                29145890   4065740          <NA>          <NA>        1        1     -140      140       2S        W             4.50             1.50          NaN   None           NaN      155573             1      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832775, 4832776]  [tmp:995300bb-6081-4285-a93a-9342d2e7bc1b, tmp:a659aa2e-1428-4ea4-87d3-581db1c2dfad]                        ["sunfeather", "jakspade"]          [nan, nan]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
1                29145897   4065741          <NA>          <NA>        1        1      650     -650       5H        N             2.50             3.50          NaN   None           NaN      155573             2      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832775, 4832776]  [tmp:995300bb-6081-4285-a93a-9342d2e7bc1b, tmp:a659aa2e-1428-4ea4-87d3-581db1c2dfad]                        ["sunfeather", "jakspade"]          [nan, nan]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
2                29145904   4065742          <NA>          <NA>        1        1      100     -100       3N        W             2.00             4.00          NaN   None           NaN      155573             3      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832775, 4832776]  [tmp:995300bb-6081-4285-a93a-9342d2e7bc1b, tmp:a659aa2e-1428-4ea4-87d3-581db1c2dfad]                        ["sunfeather", "jakspade"]          [nan, nan]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
3                29145956   4065749          <NA>          <NA>        4        1     -140      140       2H        W             3.50             2.50          NaN   None           NaN      155573            10      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832788, 4832787]  [tmp:05fb8b01-1366-4fc8-9bb4-13c7f6f012a7, tmp:abf67235-1e01-4f8e-a927-95be148ea12f]               ["valqtown", "whqtown(swap names)"]          [nan, nan]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
4                29145963   4065750          <NA>          <NA>        4        1      480     -480       4S        S             0.50             5.50          NaN   None           NaN      155573            11      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832788, 4832787]  [tmp:05fb8b01-1366-4fc8-9bb4-13c7f6f012a7, tmp:abf67235-1e01-4f8e-a927-95be148ea12f]               ["valqtown", "whqtown(swap names)"]          [nan, nan]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
5                29145970   4065751          <NA>          <NA>        4        1      -90       90       1N        E             1.00             5.00          NaN   None           NaN      155573            12      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832788, 4832787]  [tmp:05fb8b01-1366-4fc8-9bb4-13c7f6f012a7, tmp:abf67235-1e01-4f8e-a927-95be148ea12f]               ["valqtown", "whqtown(swap names)"]          [nan, nan]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
6                29146000   4065755          <NA>          <NA>        6        1     -620      620       4S        W             5.00             1.00          NaN   None           NaN      155573            16      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832795, 4832796]                                                                    [1015699, 6996043]                  ["Maureen Larson", "Ben Levine"]    [1078.3, 309.88]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
7                29146007   4065756          <NA>          <NA>        6        1     -150      150       2D        N             4.50             1.50          NaN   None           NaN      155573            17      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832795, 4832796]                                                                    [1015699, 6996043]                  ["Maureen Larson", "Ben Levine"]    [1078.3, 309.88]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
8                29146014   4065757          <NA>          <NA>        6        1      100     -100      5DX        W             0.00             6.00          NaN   None           NaN      155573            18      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832795, 4832796]                                                                    [1015699, 6996043]                  ["Maureen Larson", "Ben Levine"]    [1078.3, 309.88]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
9                29145978   4065752          <NA>          <NA>        5        1     -110      110       2S        W             3.50             2.50          NaN   None           NaN      155573            13      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832792, 4832791]                                                                    [5231051, 9311599]  ["Jeff Rowland", "Shirley Campbell(swap names)"]       [56.6, 128.2]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
10               29145985   4065753          <NA>          <NA>        5        1      -50       50       3S        S             3.00             3.00          NaN   None           NaN      155573            14      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832792, 4832791]                                                                    [5231051, 9311599]  ["Jeff Rowland", "Shirley Campbell(swap names)"]       [56.6, 128.2]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
11               29145992   4065754          <NA>          <NA>        5        1     -100      100       4H        S             3.50             2.50          NaN   None           NaN      155573            15      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832792, 4832791]                                                                    [5231051, 9311599]  ["Jeff Rowland", "Shirley Campbell(swap names)"]       [56.6, 128.2]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
12               29145912   4065743          <NA>          <NA>        2        1      660     -660       3N        N             0.00             6.00          NaN   None           NaN      155573             4      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832779, 4832780]                                                                    [4029062, 6694985]                     ["John Perry", "Julie Perry"]  [1161.82, 1034.52]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
13               29145919   4065744          <NA>          <NA>        2        1      170     -170       2S        S             0.00             6.00          NaN   None           NaN      155573             5      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832779, 4832780]                                                                    [4029062, 6694985]                     ["John Perry", "Julie Perry"]  [1161.82, 1034.52]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
14               29145926   4065745          <NA>          <NA>        2        1      140     -140       2H        N             2.50             2.50          NaN   None           NaN      155573             6      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832779, 4832780]                                                                    [4029062, 6694985]                     ["John Perry", "Julie Perry"]  [1161.82, 1034.52]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
15               29145934   4065746          <NA>          <NA>        3        1     -200      200       5C        S             6.00             0.00          NaN   None           NaN      155573             7      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832783, 4832784]                                                                    [2745771, 2745771]                    ["Sandy Pyatt", "Sandy Pyatt"]        [2.41, 2.41]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
16               29145941   4065747          <NA>          <NA>        3        1      170     -170       3H        N             1.50             4.50          NaN   None           NaN      155573             8      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832783, 4832784]                                                                    [2745771, 2745771]                    ["Sandy Pyatt", "Sandy Pyatt"]        [2.41, 2.41]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
17               29145948   4065748          <NA>          <NA>        3        1     -130      130       3D        E             6.00             0.00          NaN   None           NaN      155573             9      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832783, 4832784]                                                                    [2745771, 2745771]                    ["Sandy Pyatt", "Sandy Pyatt"]        [2.41, 2.41]  [4832778, 4832777]                                                                    [1872419, 1872427]  ["Anne Kendall", "Robert Coole(swap names)"]  [1606.12, 1765.12]
18               29145911   4065743          <NA>          <NA>        1        7      620     -620       4H        S             1.00             5.00          NaN   None           NaN      155573             4      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832775, 4832776]  [tmp:995300bb-6081-4285-a93a-9342d2e7bc1b, tmp:a659aa2e-1428-4ea4-87d3-581db1c2dfad]                        ["sunfeather", "jakspade"]          [nan, nan]  [4832802, 4832801]  [tmp:45d2e796-3ff4-4227-a227-0263a650615c, tmp:72d12c14-20e3-4fa8-9e78-2808beeaf9f9]         ["dixie_j", "driverbrya(swap names)"]          [nan, nan]
19               29145918   4065744          <NA>          <NA>        1        7     -200      200       4H        N             5.00             1.00          NaN   None           NaN      155573             5      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832775, 4832776]  [tmp:995300bb-6081-4285-a93a-9342d2e7bc1b, tmp:a659aa2e-1428-4ea4-87d3-581db1c2dfad]                        ["sunfeather", "jakspade"]          [nan, nan]  [4832802, 4832801]  [tmp:45d2e796-3ff4-4227-a227-0263a650615c, tmp:72d12c14-20e3-4fa8-9e78-2808beeaf9f9]         ["dixie_j", "driverbrya(swap names)"]          [nan, nan]
20               29145925   4065745          <NA>          <NA>        1        7      400     -400       2S        W             0.00             5.00          NaN   None           NaN      155573             6      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832775, 4832776]  [tmp:995300bb-6081-4285-a93a-9342d2e7bc1b, tmp:a659aa2e-1428-4ea4-87d3-581db1c2dfad]                        ["sunfeather", "jakspade"]          [nan, nan]  [4832802, 4832801]  [tmp:45d2e796-3ff4-4227-a227-0263a650615c, tmp:72d12c14-20e3-4fa8-9e78-2808beeaf9f9]         ["dixie_j", "driverbrya(swap names)"]          [nan, nan]
21               29145977   4065752          <NA>          <NA>        4        7     -110      110       1S        W             3.50             2.50          NaN   None           NaN      155573            13      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832788, 4832787]  [tmp:05fb8b01-1366-4fc8-9bb4-13c7f6f012a7, tmp:abf67235-1e01-4f8e-a927-95be148ea12f]               ["valqtown", "whqtown(swap names)"]          [nan, nan]  [4832802, 4832801]  [tmp:45d2e796-3ff4-4227-a227-0263a650615c, tmp:72d12c14-20e3-4fa8-9e78-2808beeaf9f9]         ["dixie_j", "driverbrya(swap names)"]          [nan, nan]
22               29145984   4065753          <NA>          <NA>        4        7     -100      100       1D        N             6.00             0.00          NaN   None           NaN      155573            14      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832788, 4832787]  [tmp:05fb8b01-1366-4fc8-9bb4-13c7f6f012a7, tmp:abf67235-1e01-4f8e-a927-95be148ea12f]               ["valqtown", "whqtown(swap names)"]          [nan, nan]  [4832802, 4832801]  [tmp:45d2e796-3ff4-4227-a227-0263a650615c, tmp:72d12c14-20e3-4fa8-9e78-2808beeaf9f9]         ["dixie_j", "driverbrya(swap names)"]          [nan, nan]
23               29145991   4065754          <NA>          <NA>        4        7      620     -620       4H        S             0.50             5.50          NaN   None           NaN      155573            15      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832788, 4832787]  [tmp:05fb8b01-1366-4fc8-9bb4-13c7f6f012a7, tmp:abf67235-1e01-4f8e-a927-95be148ea12f]               ["valqtown", "whqtown(swap names)"]          [nan, nan]  [4832802, 4832801]  [tmp:45d2e796-3ff4-4227-a227-0263a650615c, tmp:72d12c14-20e3-4fa8-9e78-2808beeaf9f9]         ["dixie_j", "driverbrya(swap names)"]          [nan, nan]
24               29145999   4065755          <NA>          <NA>        5        7     -140      140       2S        W             1.00             5.00          NaN   None           NaN      155573            16      135492            A    135492           None 2020-05-06 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00  Wednesday Evening  [4832792, 4832791]                                                                    [5231051, 9311599]  ["Jeff Rowland", "Shirley Campbell(swap names)"]       [56.6, 128.2]  [4832802, 4832801]  [tmp:45d2e796-3ff4-4227-a227-0263a650615c, tmp:72d12c14-20e3-4fa8-9e78-2808beeaf9f9]         ["dixie_j", "driverbrya(swap names)"]          [nan, nan]
...                   ...       ...           ...           ...      ...      ...      ...      ...      ...      ...              ...              ...          ...    ...           ...         ...           ...         ...          ...       ...            ...                       ...             ...        ...                  ...       ...                ...                 ...                                                                                   ...                                               ...                 ...                 ...                                                                                   ...                                           ...                 ...
50983425         18003486   2534565             3             4        4        2    -1010     1010      6 S        E             6.00             0.00                  +1         13.00       95017            18       77730            A     77723        SHUFFLE 2020-01-18 00:00:00-06:00          905513      PAIRS         MATCH_POINTS      7.50   Saturday Morning  [2928198, 2928199]                                                                    [1367110, 3105105]            ["Viola III, Joseph", "Elghamry, Amr"]  [6046.95, 5116.12]  [2928208, 2928209]                                                                    [5564697, 9269347]          ["Osmundson, Avice", "Kumar, Kiran"]  [1960.84, 1487.48]

In [11]:
df['hand_record_id'][drop_handrecords].value_counts()

None       8427985
SHUFFLE    2715403
              1540
Name: hand_record_id, dtype: int64

In [12]:
df['board_number'][drop_handrecords].value_counts()

1     588727
2     586523
3     571212
4     562245
5     547646
6     542902
7     535368
8     534279
9     530700
10    530586
11    528346
17    525494
12    524373
18    522610
13    519057
14    518261
16    518254
15    517311
19    220362
20    219738
21    196104
22    147455
23    132121
24    131711
25     83524
26     80084
27     65795
28     45149
29     30315
30     30284
31     16689
32     16669
33     11475
34      4986
35      3807
36      3799
38       207
37       207
39       183
40        67
41        66
42        66
43        44
44        44
45        44
46        13
47        13
48        13
Name: board_number, dtype: Int64

In [13]:
# takes 22s
df.drop(df[drop_handrecords].index,inplace=True)

In [14]:
# takes 6s
assert df['hand_record_id'].str.isnumeric().all()
# already int - assert df['board_number'].str.isnumeric().all()
# already int - assert df['board_id'].str.isnumeric().all()

In [15]:
# takes 17s
acbl_hand_records_cleaned_file = acblPath.joinpath('acbl_hand_records_cleaned.pkl')
acbl_hrdf = pd.read_pickle(acbl_hand_records_cleaned_file)
acbl_hrdf

                     ref hand_record_id  event_id Board  EventBoard Dealer   Vul                                                   board_record_string                                                                                         Hands                                                                Par                                                                         DDmakes
0        (acbl, 2620401)          77908    100961    09  200217A_09      N   E_W  ST6HK32DJ2CAJ9874SQJ942H765DT874CQSA853HQDKQ963CK52SK7HAJT984DA5CT63  ((T6, K32, J2, AJ9874), (A853, Q, KQ963, K52), (K7, AJT984, A5, T63), (QJ942, 765, T874, Q))                                         (200, [(4, S, *, EW, -1)])        ((10, 4, 10, 4, 8), (2, 9, 3, 9, 2), (10, 4, 10, 4, 8), (2, 9, 3, 9, 2))
1        (acbl, 2620412)          77908    100961    20  200217A_20      W  Both  ST85HKJDJ43CKJ873SQ32HA643DK96CT94SAJ64HT98DT75CA52SK97HQ752DAQ82CQ6  ((T85, KJ, J43, KJ873), (AJ64, T98, T75, A52), (K97, Q752, AQ82, Q6), (Q32, A643, K96, T94))          (90, [(1, D, , NS, 1), (1, C, , NS, 1), (1, N, , NS, 0)])            ((8, 8, 7, 7, 7), (4, 5, 6, 6, 6), (8, 8, 7, 7, 7), (4, 5, 6, 6, 6))
2        (acbl, 2620411)          77908    100961    19  200217A_19      S   E_W  STH764DAQ92CQJ653SQJ763HKJTD65CAKTSK984H5DT8743C987SA52HAQ9832DKJC42  ((T, 764, AQ92, QJ653), (K984, 5, T8743, 987), (A52, AQ9832, KJ, 42), (QJ763, KJT, 65, AKT))                                           (140, [(3, H, , NS, 0)])            ((9, 7, 9, 4, 6), (4, 6, 3, 8, 6), (9, 7, 9, 5, 6), (4, 6, 3, 8, 6))
3        (acbl, 2620420)          77908    100961    28  200217A_28      W   N_S  STHQJ9632DJ9CJ932SKQH8DQT86542CT76SJ76HATDAK3CAKQ84SA985432HK754D7C5  ((T, QJ9632, J9, J932), (J76, AT, AK3, AKQ84), (A985432, K754, 7, 5), (KQ, 8, QT86542, T76))                                          (-460, [(5, N, , EW, 0)])    ((1, 0, 10, 8, 1), (11, 11, 3, 5, 11), (0, 0, 10, 8, 0), (11, 11, 3, 5, 11))
4        (acbl, 2620399)          77908    100961    07  200217A_07      S  Both  S2HQT762D92CAKT92SAKJ7HA8DKJ4C8643SQT854HK43DA765CQS963HJ95DQT83CJ75  ((2, QT762, 92, AKT92), (QT854, K43, A765, Q), (963, J95, QT83, J75), (AKJ7, A8, KJ4, 8643))                                         (-1430, [(6, S, , EW, 0)])        ((6, 2, 6, 1, 3), (7, 11, 6, 12, 8), (6, 2, 6, 1, 3), (7, 11, 6, 12, 8))
5        (acbl, 2620396)          77908    100961    04  200217A_04      W  Both  S84HAKJ83D4CQT743SA65HQ62DQ8732CK8SJ972HT5DAKJ96C95SKQT3H974DT5CAJ62  ((84, AKJ83, 4, QT743), (J972, T5, AKJ96, 95), (KQT3, 974, T5, AJ62), (A65, Q62, Q8732, K8))                                           (620, [(4, H, , NS, 0)])        ((10, 5, 10, 6, 6), (3, 8, 3, 6, 6), (10, 5, 10, 6, 6), (3, 8, 3, 6, 6))
6        (acbl, 2620410)          77908    100961    18  200217A_18      E   N_S  S872HJ8753DQ873CASAJ65HQ4DAKJ4C874S93HAK6D962CQT963SKQT4HT92DT5CKJ52  ((872, J8753, Q873, A), (93, AK6, 962, QT963), (KQT4, T92, T5, KJ52), (AJ65, Q4, AKJ4, 874))                                          (-120, [(1, N, , EW, 1)])            ((4, 4, 5, 5, 5), (9, 8, 7, 7, 8), (4, 5, 5, 5, 5), (9, 8, 7, 7, 8))
7        (acbl, 2620400)          77908    100961    08  200217A_08      W  None  S953H98642DJ9CKJ5SAJT6HAJ3DT2CAT96S742HKQ7DK764CQ43SKQ8HT5DAQ853C872  ((953, 98642, J9, KJ5), (742, KQ7, K764, Q43), (KQ8, T5, AQ853, 872), (AJT6, AJ3, T2, AT96))                                           (-140, [(1, S, , E, 2)])            ((4, 6, 6, 4, 5), (8, 7, 7, 9, 8), (4, 6, 6, 4, 5), (8, 7, 7, 8, 8))
8        (acbl, 2620397)          77908    100961    05  200217A_05      N   N_S  S98HAKT83D84CAQ82SQJHQJ65DT2CJ7653SAK752H72DAK96CKTST643H94DQJ753C94  ((98, AKT83, 84, AQ82), (AK752, 72, AK96, KT), (T643, 94, QJ753, 94), (QJ, QJ65, T2, J7653))                                          (-120, [(2, N, , EW, 0)])            ((5, 6, 7, 4, 5), (7, 7, 6, 8, 8), (5, 6, 7, 4, 5), (7, 7, 6, 8, 8))
9        (acbl, 2620398)          77908    100961    06  200217A_06      E   E_W  SA53HJT8DQ8743CQ9SKQJT87H954DJCA62S94HAQ62DAT965C54S62HK73DK2CKJT873  ((A53, JT8, Q8743, Q9), (94, AQ62, AT965, 54), (62, K73, K2, KJT873), (KQJT87, 954, J, A62))                                          (-140, [(2, S, , EW, 1)])            ((7, 6, 5, 4, 5), (5, 7, 8, 9, 5), (7, 6, 5, 4, 5), (5, 7, 8, 9, 5))
10       (acbl, 2620418)          77908    100961    26  200217A_26      E  Both  SA53HQ652DAKT4CJ3SQT6H9743DQ632CATSK98HAJT8D875C985SJ742HKDJ9CKQ7642  ((A53, Q652, AKT4, J3), (K98, AJT8, 875, 985), (J742, K, J9, KQ7642), (QT6, 9743, Q632, AT))                                           (140, [(1, S, , NS, 2)])            ((9, 7, 6, 9, 7), (3, 6, 6, 4, 5), (9, 7, 6, 9, 7), (3, 6, 6, 4, 5))
11       (acbl, 2620415)          77908    100961    23  200217A_23      S  Both  SA62H53DAJ93C8653SK983HAK94DT6CQT4SJT4HJ62DQ52CAJ72SQ75HQT87DK874CK9  ((A62, 53, AJ93, 8653), (JT4, J62, Q52, AJ72), (Q75, QT87, K874, K9), (K983, AK94, T6, QT4))                                             (90, [(2, D, , S, 0)])            ((5, 7, 6, 5, 6), (8, 5, 7, 7, 7), (6, 8, 6, 6, 6), (7, 5, 7, 7, 7))
12       (acbl, 2620414)          77908    100961    22  200217A_22      E   E_W  SA953HQTDAK652CQJSJ876HJ632D8CKT86SQHA9875DJ43CA974SKT42HK4DQT97C532  ((A953, QT, AK652, QJ), (Q, A9875, J43, A974), (KT42, K4, QT97, 532), (J876, J632, 8, KT86))  (-300, [(5, D, *, NS, -2), (4, S, *, NS, -2), (4, N, *, NS, -2)])          ((3, 9, 3, 8, 8), (9, 4, 10, 4, 5), (3, 9, 3, 8, 8), (9, 4, 10, 4, 5))
13       (acbl, 2620404)          77908    100961    12  200217A_12      W   N_S  SAJ63HJ8DAK2CQ765SK54H43DQJ97CAT32S87HK9765D84CKJ94SQT92HAQT2DT653C8  ((AJ63, J8, AK2, Q765), (87, K9765, 84, KJ94), (QT92, AQT2, T653, 8), (K54, 43, QJ97, AT32))                                           (650, [(4, S, , NS, 1)])        ((7, 10, 8, 11, 9), (6, 3, 5, 2, 4), (7, 10, 8, 11, 9), (6, 3, 5, 2, 4))
14       (acbl, 2620408)          77908    100961    16  200217A_16      W   E_W  SAKT9754H842D5CA2S63H763DA8742CQ76S2HAQJTDJ963CKT54SQJ8HK95DKQTCJ983  ((AKT9754, 842, 5, A2), (2, AQJT, J963, KT54), (QJ8, K95, KQT, J983), (63, 763, A8742, Q76))                                           (420, [(4, S, , NS, 0)])          ((7, 5, 7, 10, 9), (6, 8, 6, 2, 3), (7, 5, 7, 10, 9), (6, 8, 6, 2, 3))
15       (acbl, 2620393)          77908    100961    01  200217A_01      N  None  SAK73HQ93DT53CA32S2HA2DKQJ872CQJ64SQ5HKJ84D964CKT85SJT9864HT765DAC97  ((AK73, Q93, T53, A32), (Q5, KJ84, 964, KT85), (JT9864, T765, A, 97), (2, A2, KQJ872, QJ64))                                        (-100, [(4, S, *, NS, -1)])          ((4, 2, 6, 9, 8), (9, 10, 6, 4, 5), (4, 2, 6, 9, 8), (9, 10, 6, 4, 5))
16       (acbl, 2620413)          77908    100961    21  200217A_21      N   N_S  SJ3H642DAK83CAJ75SAQ4HKQJ8DJ54CKT8ST652H9DT962CQ964SK987HAT753DQ7C32  ((J3, 642, AK83, AJ75), (T652, 9, T962, Q964), (K987, AT753, Q7, 32), (AQ4, KQJ8, J54, KT8))                                         (100, [(2, N, *, EW, -1)])            ((5, 6, 7, 7, 6), (7, 7, 5, 6, 7), (6, 6, 8, 7, 6), (7, 7, 5, 6, 7))
17       (acbl, 2620402)          77908    100961    10  200217A_10      E  Both  SJ854HA87DKT7CK72S2HK963DAQ6CAJ653S973HQT54DJ532CT9SAKQT6HJ2D984CQ84  ((J854, A87, KT7, K72), (973, QT54, J532, T9), (AKQT6, J2, 984, Q84), (2, K963, AQ6, AJ653))                                          (-140, [(3, H, , EW, 0)])            ((5, 5, 4, 8, 8), (7, 7, 9, 5, 5), (5, 6, 4, 8, 8), (7, 7, 9, 5, 5))
18       (acbl, 2620407)          77908    100961    15  200217A_15      S   N_S  SKT5HQ73DAT96CQ62SAQ83HA96DK4CKT97S9762HKJ42DQ8CJ83SJ4HT85DJ7532CA54  ((KT5, Q73, AT96, Q62), (9762, KJ42, Q8, J83), (J4, T85, J7532, A54), (AQ83, A96, K4, KT97))                         (-110, [(2, S, , EW, 0), (2, H, , EW, 0)])            ((5, 7, 5, 5, 6), (8, 6, 8, 8, 7), (5, 7, 5, 5, 6), (8, 6, 8, 8, 7))
19       (acbl, 2620416)          77908    100961    24  200217A_24      W  None  SK732H95DAK54CQJ6SA54HKQ7DJ96CKT85SQ96HAJ432DQT72C4SJT8HT86D83CA9732  ((K732, 95, AK54, QJ6), (Q96, AJ432, QT72, 4), (JT8, T86, 83, A9732), (A54, KQ7, J96, KT85))                                          (-120, [(2, N, , EW, 0)])            ((7, 4, 4, 6, 4), (6, 8, 8, 7, 8), (7, 4, 4, 6, 4), (6, 8, 8, 7, 8))
20       (acbl, 2620403)          77908    100961    11  200217A_11      S  None  SK73HAK2DJ95CKT94S542HJT85D7432C83S6HQ963DKQT86CQJ7SAQJT98H74DACA652  ((K73, AK2, J95, KT94), (6, Q963, KQT86, QJ7), (AQJT98, 74, A, A652), (542, JT85, 7432, 83))                                           (990, [(6, N, , NS, 0)])      ((12, 6, 7, 12, 12), (1, 7, 5, 1, 1), (12, 6, 7, 12, 12), (1, 7, 5, 1, 1))
21       (acbl, 2620395)          77908    100961    03  200217A_03      S   E_W  SK75HK3DKQT852C52SJT63HAT2DJ64CKQTS98HJ9875DA7CA964SAQ42HQ64D93CJ873  ((K75, K3, KQT852, 52), (98, J9875, A7, A964), (AQ42, Q64, 93, J873), (JT63, AT2, J64, KQT))                                           (110, [(3, D, , NS, 0)])            ((5, 9, 4, 7, 5), (7, 4, 8, 6, 5), (5, 9, 4, 7, 5), (7, 4, 8, 6, 5))
22       (acbl, 2620419)          77908    100961    27  200217A_27      S  None  SKHAQ7653DKQ54CKQSJT97HJ42DJ63C653SQ32HKT8DT97CT842SA8654H9DA82CAJ97  ((K, AQ7653, KQ54, KQ), (Q32, KT8, T97, T842), (A8654, 9, A82, AJ97), (JT97, J42, J63, 653))                                          (1440, [(7, D, , NS, 0)])  ((11, 13, 11, 11, 11), (1, 0, 2, 2, 2), (11, 13, 11, 11, 11), (1, 0, 2, 2, 2))
23       (acbl, 2620406)          77908    100961    14  200217A_14      E  None  SQT93HJ73DJ87CQ53S872H5DAKQ92CJT74SA4HKQ864D543CAK9SKJ65HAT92DT6C862  ((QT93, J73, J87, Q53), (A4, KQ864, 543, AK9), (KJ65, AT92, T6, 862), (872, 5, AKQ92, JT74))                                          (-430, [(3, N, , EW, 1)])      ((1, 2, 4, 5, 2), (10, 11, 9, 7, 10), (1, 2, 4, 5, 2), (10, 11, 9, 7, 10))
24       (acbl, 2620409)          77908    100961    17  200217A_17      N  None  SQ6HJT852DA96CA87SA5HQ97DKJ82CKJ42SJ84H63DQT54CQT93SKT9732HAK4D73C65  ((Q6, JT852, A96, A87), (J84, 63, QT54, QT93), (KT9732, AK4, 73, 65), (A5, Q97, KJ82, KJ42))                                           (400, [(3, N, , NS, 0)])            ((5, 5, 9, 9, 9), (7, 7, 3, 3, 4), (5, 5, 9, 9, 9), (7, 7, 3, 3, 4))
...                  ...            ...       ...   ...         ...    ...   ...                                                                   ...                                                                                           ...                                                                ...                                                                             ...
2968258  (acbl, 1651709)          49239     60806    09  191220A_09      N   E_W  S65HQDK432CA98642SAJT2HAT93DT6CT73SK973HK87654DQ85CSQ84HJ2DAJ97CKQJ5  ((65, Q, K432, A98642), (K973, K87654, Q85, ), (Q84, J2, AJ97, KQJ5), (AJT2, AT93, T6, T73))                                        (-300, [(6, C, *, NS, -2)])      ((10, 7, 2, 1, 3), (3, 2, 11, 11, 3), (10, 7, 2, 1, 3), (3, 2, 11, 11, 3))
2968259  (acbl, 1651716)          49239     60806    16  191220A_16      W   E_W  SA853HK82DK53C983SKQT4H7D9762CQJT7SJ7HQJ4DAQJT8CA42S962HAT9653D4CK65  ((A853, K82, K53, 983), (J7, QJ4, AQJT8, A42), (962, AT9653, 4, K65), (KQT4, 7, 9762, QJT7))                                          (-130, [(3, D, , EW, 1)])          ((4, 3, 7, 5, 4), (9, 10, 6, 7, 7), (4, 3, 7, 5, 4), (9, 10, 6, 7, 7))
2968260  (acbl, 1651719)          49239     60806    19  191220A_19      S   E_W  SA9HA43DT54CKJ943SKJ865HJ7DAK63CQ7SQ32HQT98652D92CAST74HKDQJ87CT8652  ((A9, A43, T54, KJ943), (Q32, QT98652, 92, A), (T74, K, QJ87, T8652), (KJ865, J7, AK63, Q7))                                        (-100, [(4, C, *, NS, -1)])            ((9, 7, 3, 4, 6), (4, 6, 9, 8, 6), (9, 7, 3, 4, 6), (4, 6, 9, 8, 6))
2968261  (acbl, 1651722)          49239     60806    22  191220A_22      E   E_W  S763HA982D975CA52SQ92HKQJ4DAKJ2CKTSAT5HT7DT84CJ8743SKJ84H653DQ63CQ96  ((763, A982, 975, A52), (AT5, T7, T84, J8743), (KJ84, 653, Q63, Q96), (Q92, KQJ4, AKJ2, KT))                                          (-600, [(3, N, , EW, 0)])          ((3, 3, 4, 4, 4), (9, 10, 9, 8, 9), (3, 3, 4, 4, 4), (9, 10, 9, 8, 9))
2968262  (acbl, 1651725)          49239     60806    25  191220A_25      N   E_W  S7HKQ73DAJ654C532SJT862HA865DKCT98S54HT4D83CAKQJ764SAKQ93HJ92DQT972C  ((7, KQ73, AJ654, 532), (54, T4, 83, AKQJ764), (AKQ93, J92, QT972, ), (JT862, A865, K, T98))                                           (920, [(6, D, , NS, 0)])        ((4, 12, 10, 9, 5), (9, 1, 2, 4, 5), (4, 12, 10, 9, 5), (9, 1, 2, 4, 5))
2968263  (acbl, 1651732)          49239     60806    32  191220A_32      W   E_W  S9843HJ4DQ65CQT94SJ5HKT95D9872CJ63SAQT72H87DKTCAK82SK6HAQ632DAJ43C75  ((9843, J4, Q65, QT94), (AQT72, 87, KT, AK82), (K6, AQ632, AJ43, 75), (J5, KT95, 9872, J63))                                        (-100, [(3, H, *, NS, -1)])            ((5, 7, 8, 5, 6), (7, 6, 5, 8, 6), (5, 7, 8, 5, 6), (7, 6, 5, 8, 6))
2968264  (acbl, 1651735)          49239     60806    35  191220A_35      S   E_W  SAHT732DJ54CK7642SJ852HKDAQT96CAT5SKQ43HA8654DK87C3ST976HQJ9D32CQJ98  ((A, T732, J54, K7642), (KQ43, A8654, K87, 3), (T976, QJ9, 32, QJ98), (J852, K, AQT96, AT5))                                       (-1400, [(7, C, *, NS, -6)])        ((7, 1, 3, 1, 2), (6, 12, 9, 12, 9), (7, 1, 3, 1, 2), (6, 12, 9, 12, 9))
2968265  (acbl, 1651701)          49239     60806    01  191220A_01      N  None  SAQJ74HJ5DKJT2CQJSK9862HQ862DA9C75STHK943DQ853CK983S53HAT7D764CAT642  ((AQJ74, J5, KJT2, QJ), (T, K943, Q853, K983), (53, AT7, 764, AT642), (K9862, Q862, A9, 75))                                           (120, [(2, N, , NS, 0)])            ((9, 8, 6, 8, 8), (4, 5, 6, 4, 4), (9, 8, 6, 8, 8), (4, 5, 7, 5, 5))
2968266  (acbl, 1651708)          49239     60806    08  191220A_08      W  None  SAJT95HADJ5CQT654SK732HQT9DAQ72CJ3S86HK653DKT93CK82SQ4HJ8742D864CA97  ((AJT95, A, J5, QT654), (86, K653, KT93, K82), (Q4, J8742, 864, A97), (K732, QT9, AQ72, J3))                                           (140, [(3, S, , NS, 0)])          ((10, 4, 6, 9, 5), (3, 8, 7, 4, 5), (10, 4, 6, 9, 5), (3, 8, 7, 4, 5))
2968267  (acbl, 1651711)          49239     60806    11  191220A_11      S  None  S52H3DA643CAT9643SQT987HK64DQ95CQ7SJ4HT72DKT872CJ82SAK63HAQJ985DJCK5  ((52, 3, A643, AT9643), (J4, T72, KT872, J82), (AK63, AQJ985, J, K5), (QT987, K64, Q95, Q7))                                           (920, [(6, C, , NS, 0)])    ((12, 8, 10, 10, 10), (1, 5, 3, 3, 3), (12, 8, 10, 10, 10), (1, 5, 3, 3, 3))
2968268  (acbl, 1651714)          49239     60806    14  191220A_14      E  None  SA73H983DA94CAT52SJ5HA64DKQ752C876SK94HQJT75D8CKQ93SQT862HK2DJT63CJ4  ((A73, 983, A94, AT52), (K94, QJT75, 8, KQ93), (QT862, K2, JT63, J4), (J5, A64, KQ752, 876))                                          (-140, [(3, H, , EW, 0)])            ((5, 5, 4, 7, 5), (8, 7, 9, 5, 8), (4, 5, 4, 7, 5), (8, 7, 9, 5, 8))
2968269  (acbl, 1651717)          49239     60806    17  191220A_17      N  None  SA5HQ5DKQJT6CQ987ST874HAKT8DACJ543S9632H643D9753CK2SKQJHJ972D842CAT6  ((A5, Q5, KQJT6, Q987), (9632, 643, 9753, K2), (KQJ, J972, 842, AT6), (T874, AKT8, A, J543))                                           (400, [(3, N, , NS, 0)])            ((8, 9, 8, 7, 9), (4, 3, 5, 6, 4), (8, 9, 8, 7, 9), (4, 3, 5, 6, 4))
2968270  (acbl, 1651724)          49239     60806    24  191220A_24      W  None  S82H4DT73CKQJ7432SQJT9HQT6DAJ982CTSA543HK98DKQ65C86SK76HAJ7532D4CA95  ((82, 4, T73, KQJ7432), (A543, K98, KQ65, 86), (K76, AJ7532, 4, A95), (QJT9, QT6, AJ982, T))                                           (400, [(5, C, , NS, 0)])          ((11, 3, 7, 3, 7), (1, 8, 5, 8, 5), (11, 3, 7, 3, 7), (1, 8, 5, 8, 5))
2968271  (acbl, 1651727)          49239     60806    27  191220A_27      S  None  SKJT743HKDT862CAJS986HQ962DAJ9CT76S5HJT743D7543CK42SAQ2HA85DKQCQ9853  ((KJT743, K, T862, AJ), (5, JT743, 7543, K42), (AQ2, A85, KQ, Q9853), (986, Q962, AJ9, T76))                                           (980, [(6, S, , NS, 0)])      ((10, 8, 7, 12, 10), (2, 3, 6, 1, 2), (10, 8, 7, 12, 10), (2, 3, 6, 1, 2))
2968272  (acbl, 1651730)          49239     60806    30  191220A_30      E  None  S874HAJ5DQJ9843C4SKQ953HQT86DA62C7SAT62H42DK5CKQT65SJHK973DT7CAJ9832  ((874, AJ5, QJ9843, 4), (AT62, 42, K5, KQT65), (J, K973, T7, AJ9832), (KQ953, QT86, A62, 7))                                          (-140, [(3, S, , EW, 0)])            ((6, 8, 6, 3, 5), (6, 5, 6, 9, 8), (6, 8, 6, 4, 5), (6, 5, 6, 9, 8))
2968273  (acbl, 1651733)          49239     60806    33  191220A_33      N  None  ST85HJ92DQ7CQJT87SAK6HK75DKJ84CK32SQ97432H43DATCA96SJHAQT86D96532C54  ((T85, J92, Q7, QJT87), (Q97432, 43, AT, A96), (J, AQT86, 96532, 54), (AK6, K75, KJ84, K32))                                          (-990, [(6, N, , EW, 0)])        ((4, 2, 4, 1, 1), (9, 9, 7, 12, 12), (4, 2, 5, 1, 1), (9, 9, 7, 12, 12))
2968274  (acbl, 1651702)          49239     60806    02  191220A_02      E   N_S  SKQJ6HAKJ7DA872C7ST82H963DKT6CT954SA97543HTD4CAQJ63SHQ8542DQJ953CK82  ((KQJ6, AKJ7, A872, 7), (A97543, T, 4, AQJ63), (, Q8542, QJ953, K82), (T82, 963, KT6, T954))                                           (650, [(5, H, , NS, 0)])        ((6, 11, 11, 6, 8), (7, 2, 2, 7, 3), (6, 11, 11, 6, 8), (7, 2, 2, 7, 3))
2968275  (acbl, 1651705)          49239     60806    05  191220A_05      N   N_S  SJ8HT3DQT984CJT63SKT7HKQ5DKJCAK852S9532HA9862D72CQ4SAQ64HJ74DA653C97  ((J8, T3, QT984, JT63), (9532, A9862, 72, Q4), (AQ64, J74, A653, 97), (KT7, KQ5, KJ, AK852))                                          (-420, [(4, H, , EW, 0)])          ((3, 7, 2, 4, 3), (9, 6, 10, 9, 9), (3, 7, 2, 4, 3), (9, 6, 10, 9, 9))
2968276  (acbl, 1651712)          49239     60806    12  191220A_12      W   N_S  ST6HKT5DAQJT8CJ53S9432HA432D64CA96S5HQ9876DK932CT87SAKQJ87HJD75CKQ42  ((T6, KT5, AQJT8, J53), (5, Q9876, K932, T87), (AKQJ87, J, 75, KQ42), (9432, A432, 64, A96))                                           (620, [(4, S, , NS, 0)])         ((10, 9, 6, 10, 8), (3, 3, 7, 2, 3), (9, 9, 5, 10, 8), (3, 3, 7, 2, 3))
2968277  (acbl, 1651715)          49239     60806    15  191220A_15      S   N_S  SJ4H9875DJ752C862SAQ5HQT432DAK3CAJS98632HAKD84CQT93SKT7HJ6DQT96CK754  ((J4, 9875, J752, 862), (98632, AK, 84, QT93), (KT7, J6, QT96, K754), (AQ5, QT432, AK3, AJ))                                          (-990, [(6, N, , EW, 0)])    ((1, 4, 1, 1, 1), (12, 9, 11, 12, 12), (1, 4, 2, 1, 1), (12, 9, 11, 12, 12))
2968278  (acbl, 1651718)          49239     60806    18  191220A_18      E   N_S  SA5432H93D743C873SK87HQJT764DK98CJSJT9H852DAJTCA962SQ6HAKDQ652CKQT54  ((A5432, 93, 743, 873), (JT9, 852, AJT, A962), (Q6, AK, Q652, KQT54), (K87, QJT764, K98, J))                                          (-420, [(4, H, , EW, 0)])          ((7, 6, 3, 6, 5), (5, 6, 10, 7, 6), (7, 7, 3, 6, 5), (5, 6, 10, 7, 6))
2968279  (acbl, 1651721)          49239     60806    21  191220A_21      N   N_S  SJT9643HKJ2D54CQ5SAHA984DAQ973CT43S72HQT5DKJT8CAJ72SKQ85H763D62CK986  ((JT9643, KJ2, 54, Q5), (72, QT5, KJT8, AJ72), (KQ85, 763, 62, K986), (A, A984, AQ973, T43))                                          (-420, [(4, H, , EW, 0)])        ((4, 2, 2, 7, 3), (9, 11, 10, 6, 8), (4, 2, 2, 7, 3), (9, 11, 10, 6, 8))
2968280  (acbl, 1651728)          49239     60806    28  191220A_28      W   N_S  SKJ5HA97DK432CQ43SA763H4DT76CAKJ52SQT98H53DA98CT976S42HKQJT862DQJ5C8  ((KJ5, A97, K432, Q43), (QT98, 53, A98, T976), (42, KQJT862, QJ5, 8), (A763, 4, T76, AKJ52))                                         (300, [(4, S, *, EW, -2)])          ((5, 8, 10, 5, 8), (8, 4, 3, 8, 4), (5, 8, 10, 5, 8), (8, 4, 3, 8, 4))
2968281  (acbl, 1651731)          49239     60806    31  191220A_31      S   N_S  S3HQT764DKT74CK92S2HA92DQJ985CJT54SAKQ4HJ53DA32CA63SJT98765HK8D6CQ87  ((3, QT764, KT74, K92), (AKQ4, J53, A32, A63), (JT98765, K8, 6, Q87), (2, A92, QJ985, JT54))                                          (-120, [(1, N, , EW, 1)])            ((4, 4, 6, 6, 5), (9, 9, 7, 7, 8), (4, 4, 6, 6, 4), (8, 9, 7, 7, 8))

In [16]:
# takes 2s
assert acbl_hrdf['hand_record_id'].str.isnumeric().all()
assert acbl_hrdf['Board'].str.isnumeric().all()
assert all([type(t) is tuple and len(t) == 2 for t in acbl_hrdf['Par']])
assert all([type(t[0]) is int for t in acbl_hrdf['Par']])

In [17]:
acbl_hrdf[(acbl_hrdf['hand_record_id'] == '1') & (acbl_hrdf['Board'] == '01')]

               ref hand_record_id  event_id Board  EventBoard Dealer   Vul                                                   board_record_string                                                                                         Hands                        Par                                                                   DDmakes
1642353  (acbl, 1)              1         3    01  181001A_01      N  None  S94H765DAJ762CK94SA5HAKQT3DQ43CQ76SK72H942DT9CAT832SQJT863HJ8DK85CJ5  ((94, 765, AJ762, K94), (K72, 942, T9, AT832), (QJT863, J8, K85, J5), (A5, AKQT3, Q43, Q76))  (-420, [(4, H, , EW, 0)])  ((3, 6, 3, 6, 5), (10, 6, 10, 5, 8), (3, 6, 3, 6, 5), (10, 6, 10, 5, 8))

In [18]:
1518827 in acbl_hrdf.index

True

In [19]:
# takes 10s
# todo: 24m board_ids not found in hand records table. Why is that? SHUFFLE?
missing_board_ids = ~df['board_id'].isin(acbl_hrdf.index)
df[missing_board_ids]

          board_result_id  board_id  round_number  table_number  ns_pair  ew_pair ns_score ew_score contract declarer  ew_match_points  ns_match_points opening_lead result  tricks_taken  section_id  board_number  session_id section_name  event_id hand_record_id                 game_date  club_id_number event_type board_scoring_method  tb_count        club_session          player_id_ns    player_number_ns                                 player_name_ns         mp_total_ns          player_id_ew    player_number_ew                                      player_name_ew       mp_total_ew
2255             37205244   5024242          <NA>          <NA>        6        6      100     -100       3H        E             1.00             5.00          NaN   None           NaN      205576             1      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00   Wednesday Evening    [6520104, 6520105]  [1407953, 2536919]               ["Cheryl Smith", "Ruth Whitney"]       [8.01, 21.11]    [6520106, 6520107]  [7593422, 8880387]                       ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2256             37205251   5024243          <NA>          <NA>        6        6      140     -140       2H        S             2.00             4.00          NaN   None           NaN      205576             2      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00   Wednesday Evening    [6520104, 6520105]  [1407953, 2536919]               ["Cheryl Smith", "Ruth Whitney"]       [8.01, 21.11]    [6520106, 6520107]  [7593422, 8880387]                       ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2257             37205258   5024244          <NA>          <NA>        6        6     -150      150       3D        E             3.50             2.50          NaN   None           NaN      205576             3      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00   Wednesday Evening    [6520104, 6520105]  [1407953, 2536919]               ["Cheryl Smith", "Ruth Whitney"]       [8.01, 21.11]    [6520106, 6520107]  [7593422, 8880387]                       ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2258             37205303   5024251          <NA>          <NA>        2        6      130     -130       4C        N             2.00             4.00          NaN   None           NaN      205576            10      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00   Wednesday Evening    [6520088, 6520089]  [2168774, 7629435]          ["Kathy Luxemburger", "Sue Langevin"]         [8.51, 5.0]    [6520106, 6520107]  [7593422, 8880387]                       ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2259             37205310   5024252          <NA>          <NA>        2        6     -130      130       3C        E             1.50             4.50          NaN   None           NaN      205576            11      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00   Wednesday Evening    [6520088, 6520089]  [2168774, 7629435]          ["Kathy Luxemburger", "Sue Langevin"]         [8.51, 5.0]    [6520106, 6520107]  [7593422, 8880387]                       ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2260             37205317   5024253          <NA>          <NA>        2        6      680     -680       4H        N             2.50             2.50          NaN   None           NaN      205576            12      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00   Wednesday Evening    [6520088, 6520089]  [2168774, 7629435]          ["Kathy Luxemburger", "Sue Langevin"]         [8.51, 5.0]    [6520106, 6520107]  [7593422, 8880387]                       ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2261             37205281   5024248          <NA>          <NA>        1        6     -100      100       3N        S             2.00             4.00          NaN   None           NaN      205576             7      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00   Wednesday Evening    [6520084, 6520085]  [7846509, 9059474]             ["Vickie Roche", "Stan Marinoske"]        [7.1, 41.76]    [6520106, 6520107]  [7593422, 8880387]                       ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2262             37205288   5024249          <NA>          <NA>        1        6     -170      170       2S        E             4.50             1.50          NaN   None           NaN      205576             8      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00   Wednesday Evening    [6520084, 6520085]  [7846509, 9059474]             ["Vickie Roche", "Stan Marinoske"]        [7.1, 41.76]    [6520106, 6520107]  [7593422, 8880387]                       ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2263             37205295   5024250          <NA>          <NA>        1        6     -600      600       3N        E             1.00             5.00          NaN   None           NaN      205576             9      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00   Wednesday Evening    [6520084, 6520085]  [7846509, 9059474]             ["Vickie Roche", "Stan Marinoske"]        [7.1, 41.76]    [6520106, 6520107]  [7593422, 8880387]                       ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2264             37205325   5024254          <NA>          <NA>        3        6     -620      620       4S        W             3.00             3.00          NaN   None           NaN      205576            13      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00   Wednesday Evening    [6520092, 6520093]  [3449335, 6451748]                ["James Scarfe", "Kirk Rustad"]    [861.47, 637.28]    [6520106, 6520107]  [7593422, 8880387]                       ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2265             37205332   5024255          <NA>          <NA>        3        6      -50       50       2S        S             3.50             2.50          NaN   None           NaN      205576            14      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00   Wednesday Evening    [6520092, 6520093]  [3449335, 6451748]                ["James Scarfe", "Kirk Rustad"]    [861.47, 637.28]    [6520106, 6520107]  [7593422, 8880387]                       ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2266             37205339   5024256          <NA>          <NA>        3        6     -100      100       5D        S             4.00             2.00          NaN   None           NaN      205576            15      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00   Wednesday Evening    [6520092, 6520093]  [3449335, 6451748]                ["James Scarfe", "Kirk Rustad"]    [861.47, 637.28]    [6520106, 6520107]  [7593422, 8880387]                       ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2267             37205347   5024257          <NA>          <NA>        4        6      800     -800      3HX        W             0.00             6.00          NaN   None           NaN      205576            16      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00   Wednesday Evening    [6520097, 6520096]  [1015699, 8160996]  ["Maureen Larson", "Mike Landry(swap names)"]   [1084.76, 339.78]    [6520106, 6520107]  [7593422, 8880387]                       ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2268             37205354   5024258          <NA>          <NA>        4        6       50      -50       2S        E             2.00             4.00          NaN   None           NaN      205576            17      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00   Wednesday Evening    [6520097, 6520096]  [1015699, 8160996]  ["Maureen Larson", "Mike Landry(swap names)"]   [1084.76, 339.78]    [6520106, 6520107]  [7593422, 8880387]                       ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2269             37205361   5024259          <NA>          <NA>        4        6     -150      150       3C        E             2.00             4.00          NaN   None           NaN      205576            18      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00   Wednesday Evening    [6520097, 6520096]  [1015699, 8160996]  ["Maureen Larson", "Mike Landry(swap names)"]   [1084.76, 339.78]    [6520106, 6520107]  [7593422, 8880387]                       ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2270             37205266   5024245          <NA>          <NA>        7        6      100     -100       3H        W             6.00             0.00          NaN   None           NaN      205576             4      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00   Wednesday Evening    [6520108, 6520109]  [2324555, 9124993]            ["Lorraine Hoyt", "Noreen McGowan"]      [14.06, 34.31]    [6520106, 6520107]  [7593422, 8880387]                       ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2271             37205273   5024246          <NA>          <NA>        7        6      650     -650       4S        S             2.50             3.50          NaN   None           NaN      205576             5      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00   Wednesday Evening    [6520108, 6520109]  [2324555, 9124993]            ["Lorraine Hoyt", "Noreen McGowan"]      [14.06, 34.31]    [6520106, 6520107]  [7593422, 8880387]                       ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2272             37205280   5024247          <NA>          <NA>        7        6      460     -460       3N        S             2.00             4.00          NaN   None           NaN      205576             6      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00   Wednesday Evening    [6520108, 6520109]  [2324555, 9124993]            ["Lorraine Hoyt", "Noreen McGowan"]      [14.06, 34.31]    [6520106, 6520107]  [7593422, 8880387]                       ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2273             37205369   5024260          <NA>          <NA>        5        6     -620      620       4S        E             4.00             2.00          NaN   None           NaN      205576            19      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00   Wednesday Evening    [6520101, 6520100]  [4029062, 6694985]      ["John Perry", "Julie Perry(swap names)"]  [1170.85, 1043.55]    [6520106, 6520107]  [7593422, 8880387]                       ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2274             37205376   5024261          <NA>          <NA>        5        6      300     -300       3N        W             2.00             4.00          NaN   None           NaN      205576            20      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00   Wednesday Evening    [6520101, 6520100]  [4029062, 6694985]      ["John Perry", "Julie Perry(swap names)"]  [1170.85, 1043.55]    [6520106, 6520107]  [7593422, 8880387]                       ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2275             37205383   5024262          <NA>          <NA>        5        6      620     -620       4H        S             0.50             5.50          NaN   None           NaN      205576            21      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00   Wednesday Evening    [6520101, 6520100]  [4029062, 6694985]      ["John Perry", "Julie Perry(swap names)"]  [1170.85, 1043.55]    [6520106, 6520107]  [7593422, 8880387]                       ["Lynn Daffe", "Chic Callas"]  [118.02, 891.47]
2276             37205265   5024245          <NA>          <NA>        6        5      140     -140       2S        N             2.00             4.00          NaN   None           NaN      205576             4      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00   Wednesday Evening    [6520104, 6520105]  [1407953, 2536919]               ["Cheryl Smith", "Ruth Whitney"]       [8.01, 21.11]    [6520102, 6520103]  [3109100, 9311599]               ["Colleen Kelly", "Shirley Campbell"]  [428.84, 172.31]
2277             37205272   5024246          <NA>          <NA>        6        5      650     -650       4S        S             2.50             3.50          NaN   None           NaN      205576             5      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00   Wednesday Evening    [6520104, 6520105]  [1407953, 2536919]               ["Cheryl Smith", "Ruth Whitney"]       [8.01, 21.11]    [6520102, 6520103]  [3109100, 9311599]               ["Colleen Kelly", "Shirley Campbell"]  [428.84, 172.31]
2278             37205279   5024247          <NA>          <NA>        6        5      230     -230       3S        N             6.00             0.00          NaN   None           NaN      205576             6      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00   Wednesday Evening    [6520104, 6520105]  [1407953, 2536919]               ["Cheryl Smith", "Ruth Whitney"]       [8.01, 21.11]    [6520102, 6520103]  [3109100, 9311599]               ["Colleen Kelly", "Shirley Campbell"]  [428.84, 172.31]
2279             37205324   5024254          <NA>          <NA>        2        5     -620      620       4S        W             3.00             3.00          NaN   None           NaN      205576            13      180666            A    180666          96309 2020-08-19 00:00:00-05:00          100040      PAIRS         MATCH_POINTS      7.00   Wednesday Evening    [6520088, 6520089]  [2168774, 7629435]          ["Kathy Luxemburger", "Sue Langevin"]         [8.51, 5.0]    [6520102, 6520103]  [3109100, 9311599]               ["Colleen Kelly", "Shirley Campbell"]  [428.84, 172.31]
...                   ...       ...           ...           ...      ...      ...      ...      ...      ...      ...              ...              ...          ...    ...           ...         ...           ...         ...          ...       ...            ...                       ...             ...        ...                  ...       ...                 ...                   ...                 ...                                            ...                 ...                   ...                 ...                                                 ...               ...
50979535         23685996   3319649             2             2        2        1     -110      110      2 S        W            13.00             2.00                   =          8.00      124484             9      106009            C    106009          81204 2020-02-22 00:00:00-06:00          905497      PAIRS         MATCH_POINTS     17.00  Saturday Afternoon    [3860112, 3860113]  [2662159, 4778723]         ["Sonnenshein, Linda", "Durra, Joyce"]     [64.24, 142.74]    [3860129, 3860128]  [7739168, 9095454]  ["Thomas, Cindy", "Sonnenshein, Mona(swap names)"]     [6.71, 23.89]
50983498         57289070   7468320          <NA>          <NA>        3        7      140     -140       2S        N             1.00             2.00           C9     +1           NaN      330825             1      294636            A    294636         205971 2021-04-10 00:00:00-05:00          909994      PAIRS         MATCH_POINTS      4.00    Saturday Evening  [10656508, 10656509]  [5331978, 9106588]                 ["Yunhan Wu", "Shengding Sun"]    [179.49, 235.14]  [10656510, 10656511]  [7515324, 7684029]                     ["Hongmo Li", "Sriram Ganesan"]   [45.52, 120.54]
50983499         57289074   7468321          <NA>          <NA>        3        7      600     -600       5C        S             0.50             2.50           S7      =           NaN      330825             2      294636            A    294636         205971 2021-04-10 00:00:00-05:00          909994      PAIRS         MATCH_POINTS      4.00    Saturday Evening  [10656508, 10656509]  [5331978, 9106588]                 ["Yunhan Wu", "Shengding Sun"]    [179.49, 235.14]  [10656510, 10656511]  [7515324, 7684029]                     ["Hongmo Li", "Sriram Ganesan"]   [45.52, 120.54]
50983500         57289078   7468322          <NA>          <NA>        3        7     -660      660       3N        W             3.00             0.00           D8     +2           NaN      330825             3      294636            A    294636         205971 2021-04-10 00:00:00-05:00          909994      PAIRS         MATCH_POINTS      4.00    Saturday Evening  [10656508, 10656509]  [5331978, 9106588]                 ["Yunhan Wu", "Shengding Sun"]    [179.49, 235.14]  [10656510, 10656511]  [7515324, 7684029]                     ["Hongmo Li", "Sriram Ganesan"]   [45.52, 120.54]
50983501         57289092   7468326          <NA>          <NA>        1        7     -620      620       4H        E             2.50             0.50           SK      =           NaN      330825             7      294636            A    294636         205971 2021-04-10 00:00:00-05:00          909994      PAIRS         MATCH_POINTS      4.00    Saturday Evening  [10656500, 10656501]  [2992833, 7584393]            ["Charles Holmes", "Steven Creech"]      [86.88, 24.59]  [10656510, 10656511]  [7515324, 7684029]                     ["Hongmo Li", "Sriram Ganesan"]   [45.52, 120.54]
50983502         57289096   7468327          <NA>          <NA>        1        7      -50       50       2N        N             1.50             1.50           DA     -1           NaN      330825             8      294636            A    294636         205971 2021-04-10 00:00:00-05:00          909994      PAIRS         MATCH_POINTS      4.00    Saturday Evening  [10656500, 10656501]  [2992833, 7584393]            ["Charles Holmes", "Steven Creech"]      [86.88, 24.59]  [10656510, 10656511]  [7515324, 7684029]                     ["Hongmo Li", "Sriram Ganesan"]   [45.52, 120.54]
50983503         57289100   7468328          <NA>          <NA>        1        7     -680      680       4S        E             0.50             2.50           HJ     +2           NaN      330825             9      294636            A    294636         205971 2021-04-10 00:00:00-05:00          909994      PAIRS         MATCH_POINTS      4.00    Saturday Evening  [10656500, 10656501]  [2992833, 7584393]            ["Charles Holmes", "Steven Creech"]      [86.88, 24.59]  [10656510, 10656511]  [7515324, 7684029]                     ["Hongmo Li", "Sriram Ganesan"]   [45.52, 120.54]

In [20]:
#acbl_hrdf['board_number'] = acbl_hrdf['Board'].astype('int8')

In [21]:
#dfd = dict(zip(zip(df['hand_record_id'],df['board_number']),df.index))
#len(df),len(dfd),dfd

In [22]:
#hrd =  dict(zip(zip(acbl_hrdf['hand_record_id'],acbl_hrdf['board_number']),acbl_hrdf.index))
#len(acbl_hrdf),len(hrd),hrd

In [23]:
#drop_boards_d = [k for k,v in dfd.items() if k not in hrd]
#len(df),len(dfd),len(acbl_hrdf),len(hrd),len(drop_boards_d),drop_boards_d

In [24]:
# Using a df for isin() seems to hang system.
#drop_boards_isin = ~df[['hand_record_id','board_number']].isin(acbl_hrdf[['hand_record_id','board_number']])
#df[drop_boards_isin]

In [25]:
#df['hand_board'] = df['hand_record_id'].astype('string')+'_'+df['board_number'].astype('string')
#df

In [26]:
#acbl_hrdf['hand_board'] = acbl_hrdf['hand_record_id'].astype('string')+'_'+acbl_hrdf['Board'].astype('int8').astype('string')
#acbl_hrdf

In [27]:
#'96309_1' in acbl_hrdf['hand_board']

In [28]:
#drop_hand_boards = ~df['hand_board'].isin(acbl_hrdf['hand_board'])
#df[drop_hand_boards]

In [29]:
#len(missing_board_ids), len(drop_boards_d)#, set(missing_board_ids.index) - set(drop_boards_d.index)

In [30]:
#len(missing_board_ids), len(drop_hand_boards), set(missing_board_ids.index) - set(drop_hand_boards.index)

In [31]:
# takes 20s
df.drop(df[missing_board_ids].index,inplace=True)

In [32]:
# takes 3m
# create dict with key of board_id and value of par. Makes par retrival faster.
# todo: move this into create dicts?
# todo: must be a faster way?
pard = {b:p[0] for b,p in zip(df['board_id'],df['board_id'].map(lambda x: acbl_hrdf['Par'].loc[x]))}
pard

{324858: 110,
 324859: -300,
 324860: 420,
 324861: 140,
 324862: -140,
 324863: -110,
 324876: 140,
 324877: -620,
 324878: -1400,
 324864: -140,
 324865: -430,
 324866: 120,
 324879: 500,
 324880: -90,
 324881: 1400,
 324873: -300,
 324874: 600,
 324875: 140,
 324870: 2220,
 324871: -620,
 324872: -140,
 324867: 650,
 324868: 500,
 324869: -110,
 324882: -100,
 324883: -110,
 324884: -620,
 324885: -980,
 324902: -90,
 324903: -120,
 324904: -100,
 324905: 90,
 324906: 420,
 324907: 600,
 324908: -600,
 324909: 100,
 324890: 140,
 324891: 620,
 324892: 110,
 324893: 430,
 324886: -500,
 324887: 420,
 324888: 620,
 324889: 1520,
 324898: -100,
 324899: 800,
 324900: 800,
 324901: 980,
 324894: -140,
 324895: -420,
 324896: -140,
 324897: -120,
 326563: 140,
 326564: 430,
 326565: -460,
 326566: -100,
 326567: -400,
 326568: -110,
 326569: -450,
 326570: 450,
 326583: -140,
 326584: -660,
 326585: -120,
 326586: -620,
 326575: 1440,
 326576: -140,
 326577: -430,
 326578: 1370,
 326579: -420,
 326580: 500,
 326581: 130,
 326582: -140,
 326571: 620,
 326572: -140,
 326573: -400,
 326574: 500,
 362114: 100,
 362115: 450,
 362116: -400,
 362117: 1100,
 362134: 450,
 362135: -300,
 362136: 110,
 362137: -140,
 362126: 1430,
 362127: -600,
 362128: 650,
 362129: 140,
 362130: -140,
 362131: 650,
 362132: -140,
 362133: -500,
 362122: -110,
 362123: -140,
 362124: -130,
 362125: -600,
 362118: -420,
 362119: -200,
 362120: -420,
 362121: 2220,
 362138: 110,
 362139: -100,
 362140: -100,
 362141: -650,
 368973: -430,
 368974: 100,
 368975: -90,
 368976: 100,
 368993: -650,
 368994: 200,
 368995: 140,
 368996: -110,
 368981: -120,
 368982: 620,
 368983: 420,
 368984: 110,
 368985: 920,
 368986: 620,
 368987: 430,
 368988: -430,
 368997: 110,
 368998: 450,
 368999: -450,
 369000: -990,
 368989: 620,
 368990: -140,
 368991: 2140,
 368992: 630,
 369001: 650,
 369002: 980,
 369003: 460,
 369004: 630,
 368977: -1440,
 368978: -430,
 368979: -140,
 368980: 460,
 371268: 660,
 371269: 400,
 371270: 140,
 371271: 140,
 371272: -110,
 371273: -420,
 371277: -2220,
 371278: -660,
 371279: -620,
 371289: 990,
 371290: 420,
 371291: 450,
 371292: -660,
 371293: 140,
 371294: 140,
 371286: -1440,
 371287: -300,
 371288: -100,
 371283: -650,
 371284: 120,
 371285: -500,
 371274: 1430,
 371275: -140,
 371276: -110,
 371280: 1430,
 371281: 110,
 371282: 630,
 388147: 140,
 388148: -140,
 388149: 140,
 388150: 90,
 388151: -140,
 388152: -420,
 388153: 110,
 388154: -300,
 388159: -140,
 388160: 110,
 388161: -620,
 388162: 120,
 388163: -460,
 388164: 420,
 388165: -120,
 388166: 660,
 388155: -420,
 388156: -660,
 388157: 100,
 388158: -140,
 388167: -420,
 388168: -620,
 388169: -1700,
 388170: 600,
 394811: -1370,
 394812: -100,
 394813: -500,
 394814: 110,
 394823: -460,
 394824: -420,
 394825: -450,
 394826: 110,
 394835: -460,
 394836: 1370,
 394837: -130,
 394838: -110,
 394827: -140,
 394828: -140,
 394829: 630,
 394830: 1430,
 394815: 420,
 394816: -90,
 394817: -1400,
 394818: 140,
 394819: 140,
 394820: 800,
 394821: -300,
 394822: -450,
 394831: 130,
 394832: 100,
 394833: -130,
 394834: 500,
 402360: -100,
 402361: -430,
 402362: 140,
 402375: -450,
 402376: 600,
 402377: 650,
 402369: 650,
 402370: -130,
 402371: -430,
 402384: -1430,
 402385: 650,
 402386: 660,
 402378: -1370,
 402379: 90,
 402380: 650,
 402372: -420,
 402373: 620,
 402374: -130,
 402366: 110,
 402367: 140,
 402368: -110,
 402381: -140,
 402382: 600,
 402383: 140,
 402363: -120,
 402364: 140,
 402365: -400,
 410689: -450,
 410690: 980,
 410691: 120,
 410692: 990,
 410693: 420,
 410709: 1440,
 410710: 600,
 410711: 1370,
 410712: 660,
 410713: -630,
 410699: 630,
 410700: -400,
 410701: 140,
 410702: 600,
 410703: 2210,
 410704: 100,
 410705: 100,
 410706: 630,
 410707: -140,
 410708: -650,
 410714: 500,
 410715: 140,
 410716: -100,
 410717: -650,
 410718: 420,
 410694: 130,
 410695: 420,
 410696: -980,
 410697: -450,
 410698: -450,
 426328: 140,
 426329: -140,
 426330: 100,
 426331: 500,
 426340: 420,
 426341: 110,
 426342: -620,
 426343: -130,
 426348: 300,
 426349: -100,
 426350: -1510,
 426351: 100,
 426332: -130,
 426333: -1430,
 426334: 600,
 426335: 140,
 426352: -300,
 426353: -420,
 426354: -200,
 426355: -140,
 426344: -300,
 426345: -110,
 426346: -450,
 426347: 420,
 426336: 120,
 426337: 620,
 426338: 600,
 426339: 90,
 428606: -500,
 428607: -90,
 428608: 140,
 428609: 990,
 428610: -620,
 428611: 110,
 428627: -110,
 428628: -500,
 428629: 620,
 428618: -120,
 428619: 450,
 428620: 620,
 428624: 100,
 428625: 140,
 428626: 110,
 428615: -2210,
 428616: -140,
 428617: 500,
 428612: 980,
 428613: 420,
 428614: -450,
 428621: 90,
 428622: 140,
 428623: 430,
 449431: 420,
 449432: 450,
 449433: 980,
 449434: 400,
 449451: -90,
 449452: -620,
 449453: -90,
 449454: 500,
 449443: 600,
 449444: -130,
 449445: -460,
 449446: 600,
 449435: -420,
 449436: 100,
 449437: -430,
 449438: -450,
 449455: -1370,
 449456: 130,
 449457: 110,
 449458: -500,
 449447: -620,
 449448: 80,
 449449: -130,
 449450: -630,
 449439: 650,
 449440: 2210,
 449441: -450,
 449442: 120,
 450618: -460,
 450619: -120,
 450620: 420,
 450633: 600,
 450634: -120,
 450635: -650,
 450648: 450,
 450649: 980,
 450650: 450,
 450627: -90,
 450628: 300,
 450629: -430,
 450621: 430,
 450622: 420,
 450623: -420,
 450642: 1510,
 450643: 620,
 450644: 650,
 450636: -420,
 450637: -450,
 450638: -100,
 450639: 140,
 450640: -430,
 450641: -100,
 450645: 110,
 450646: 660,
 450647: -110,
 450624: -140,
 450625: 620,
 450626: -420,
 450630: 100,
 450631: -400,
 450632: 100,
 450588: -90,
 450589: -600,
 450590: 100,
 450597: 1520,
 450598: 140,
 450599: -600,
 450606: 600,
 450607: -500,
 450608: 140,
 450594: -420,
 450595: 600,
 450596: 600,
 450612: -110,
 450613: -120,
 450614: 430,
 450603: 600,
 450604: 650,
 450605: -500,
 450591: -400,
 450592: 430,
 450593: -140,
 450615: -600,
 450616: -400,
 450617: 100,
 450600: 2140,
 450601: 140,
 450602: 120,
 450609: 450,
 450610: 1510,
 450611: 1520,
 458556: 110,
 458557: 620,
 458558: 1430,
 458559: -110,
 458576: 990,
 458577: -1440,
 458578: -420,
 458579: 110,
 458572: 990,
 458573: 920,
 458574: 300,
 458575: 400,
 458580: 450,
 458581: 1700,
 458582: -140,
 458583: 500,
 458564: 110,
 458565: -650,
 458566: -140,
 458567: -500,
 458568: 90,
 458569: -1440,
 458570: -130,
 458571: -600,
 458560: 2220,
 458561: 660,
 458562: 600,
 458563: 450,
 460432: -130,
 460433: -400,
 460434: -110,
 460450: -100,
 460451: -140,
 460452: -130,
 460453: -1400,
 460454: 140,
 460455: 420,
 460444: 130,
 460445: 130,
 460446: 130,
 460438: -660,
 460439: -660,
 460440: -620,
 460447: 90,
 460448: -100,
 460449: 140,
 460441: 2220,
 460442: -130,
 460443: -110,
 460435: -130,
 460436: 110,
 460437: 650,
 473181: 600,
 473182: -920,
 473183: 140,
 473196: -600,
 473197: -300,
 473198: 450,
 473190: 2210,
 473191: -130,
 473192: -620,
 473184: -420,
 473185: -110,
 473186: 600,
 473199: -140,
 473200: 120,
 473201: 420,
 473193: 90,
 473194: -500,
 473195: 450,
 473187: 110,
 473188: -650,
 473189: 650,
 473202: 420,
 473203: -450,
 473204: -100,
 473205: -110,
 473206: -450,
 473207: -140,
 491610: 420,
 491611: 130,
 491612: 100,
 491613: -90,
 491622: 140,
 491623: -140,
 491624: 130,
 491625: 200,
 491634: -110,
 491635: -630,
 491636: 500,
 491637: 460,
 491626: 600,
 491627: -430,
 491628: -650,
 491629: 110,
 491618: -140,
 491619: 140,
 491620: 110,
 491621: -430,
 491630: -620,
 491631: 90,
 491632: -140,
 491633: -400,
 491614: -990,
 491615: 140,
 491616: 600,
 491617: -990,
 497799: 140,
 497800: 140,
 497801: -130,
 497805: -90,
 497806: 140,
 497807: -140,
 497808: -140,
 497809: 100,
 497810: -450,
 497802: 420,
 497803: -400,
 497804: -100,
 497814: 400,
 497815: 620,
 497816: 430,
 497817: -90,
 497818: -500,
 497819: 120,
 497811: -110,
 497812: 120,
 497813: -100,
 512029: 600,
 512030: -90,
 512031: 430,
 512050: 650,
 512051: 630,
 512052: -100,
 512044: -130,
 512045: -120,
 512046: -600,
 512053: -1510,
 512054: -1700,
 512055: -1370,
 512038: -400,
 512039: 110,
 512040: -420,
 512032: -450,
 512033: 100,
 512034: 600,
 512035: 450,
 512036: 500,
 512037: 600,
 512047: -100,
 512048: 620,
 512049: 400,
 512041: -980,
 512042: -130,
 512043: -500,
 533333: 450,
 533334: -100,
 533335: 130,
 533336: -450,
 533357: -630,
 533358: 140,
 533359: -110,
 533360: -120,
 533341: 140,
 533342: -130,
 533343: -130,
 533344: -140,
 533337: -990,
 533338: -400,
 533339: -400,
 533340: 130,
 533349: -420,
 533350: -140,
 533351: 2140,
 533352: -140,
 533345: -460,
 533346: 120,
 533347: 500,
 533348: 660,
 533353: 110,
 533354: 140,
 533355: -600,
 533356: -660,
 538413: 100,
 538414: -120,
 538415: 420,
 538431: 630,
 538432: 660,
 538433: 2220,
 538425: 400,
 538426: -400,
 538427: -600,
 538428: 110,
 538429: -500,
 538430: -110,
 538422: -500,
 538423: 140,
 538424: 140,
 538434: 620,
 538435: 110,
 538436: 140,
 538419: 110,
 538420: -120,
 538421: -100,
 538416: -660,
 538417: -400,
 538418: -110,
 538437: -140,
 538438: -140,
 538439: 140,
 538440: -660,
 538441: 420,
 538442: 420,
 590325: -420,
 590326: -920,
 590327: -420,
 590328: 620,
 590337: 630,
 590338: -620,
 590339: -620,
 590340: 650,
 590341: 630,
 590342: 140,
 590343: 110,
 590344: 110,
 590345: 110,
 590346: -500,
 590347: 920,
 590348: 140,
 590329: -130,
 590330: -140,
 590331: 2210,
 590332: -420,
 590349: -100,
 590350: 110,
 590351: -600,
 590352: -400,
 590333: 1400,
 590334: 620,
 590335: -620,
 590336: 110,
 590353: -460,
 590354: 90,
 590355: -980,
 590356: 140,
 565426: 420,
 565427: -300,
 565428: -630,
 565447: -620,
 565448: 130,
 565449: -620,
 565441: -430,
 565442: -400,
 565443: -120,
 565435: -140,
 565436: 90,
 565437: -450,
 565429: -140,
 565430: -660,
 565431: -650,
 565438: -120,
 565439: -430,
 565440: -140,
 565432: 450,
 565433: -120,
 565434: 100,
 565450: -660,
 565451: 630,
 565452: 140,
 565444: 1440,
 565445: 130,
 565446: 140,
 595653: -140,
 595654: -100,
 595655: -110,
 595656: -130,
 595673: -140,
 595674: 1370,
 595675: 110,
 595676: 620,
 595669: -630,
 595670: 650,
 595671: -500,
 595672: -600,
 595661: 620,
 595662: 450,
 595663: 130,
 595664: 110,
 595665: -980,
 595666: 100,
 595667: 650,
 595668: 420,
 595657: -140,
 595658: 650,
 595659: -650,
 595660: 620,
 613478: 420,
 613479: -1370,
 613480: 90,
 613481: -630,
 613494: -430,
 613495: 600,
 613496: -430,
 613497: 600,
 613506: 620,
 613507: 200,
 613508: 140,
 613509: 620,
 613486: -460,
 613487: -140,
 613488: 100,
 613489: -300,
 613502: -400,
 613503: -650,
 613504: 120,
 613505: -90,
 613482: 450,
 613483: 980,
 613484: 1510,
 613485: -100,
 613498: 120,
 613499: 100,
 613500: 130,
 613501: -140,
 613490: -420,
 613491: 100,
 613492: 110,
 613493: -100,
 703092: -110,
 703093: 420,
 703094: -300,
 703095: 110,
 703096: 400,
 703097: 420,
 703098: -140,
 703099: -140,
 703108: 430,
 703109: -450,
 703110: -110,
 703111: 630,
 703100: -500,
 703101: 420,
 703102: 100,
 703103: -420,
 703104: 980,
 703105: -130,
 703106: 130,
 703107: -450,
 703116: -140,
 703117: 100,
 703118: -430,
 703119: 600,
 703112: 2220,
 703113: 130,
 703114: 300,
 703115: -400,
 703362: -600,
 703363: 140,
 703364: -140,
 703365: 650,
 703366: 430,
 703367: 990,
 703368: 450,
 703369: -650,
 703378: -100,
 703379: -450,
 703380: 140,
 703381: -400,
 703370: 450,
 703371: -1400,
 703372: 980,
 703373: 460,
 703374: -300,
 703375: 400,
 703376: 130,
 703377: 100,
 703386: -400,
 703387: -1440,
 703388: -620,
 703389: 600,
 703382: 300,
 703383: -110,
 703384: -420,
 703385: 650,
 739983: 200,
 739984: -1400,
 739999: -140,
 740000: 130,
 739993: -140,
 739994: -140,
 739989: 420,
 739990: -450,
 739985: -450,
 739986: -130,
 740003: 650,
 740004: 110,
 739995: 110,
 739996: 650,
 739987: -140,
 739988: 100,
 740005: -420,
 740006: 620,
 739997: -140,
 739998: -450,
 740007: 130,
 740008: -650,
 739991: -420,
 739992: 100,
 740001: -400,
 740002: -200,
 741314: 450,
 741315: -140,
 741316: 420,
 741332: -990,
 741333: 500,
 741334: 100,
 741323: -400,
 741324: 130,
 741325: -400,
 741317: -120,
 741318: -450,
 741319: 920,
 741329: -1520,
 741330: 140,
 741331: -420,
 741326: -140,
 741327: -110,
 741328: 140,
 741320: 110,
 741321: 110,
 741322: -400,
 783133: -90,
 783134: -460,
 783135: 110,
 783136: 460,
 783145: -430,
 783146: -920,
 783147: -430,
 783148: -980,
 783137: -300,
 783138: 400,
 783139: 140,
 783140: 620,
 783157: -80,
 783158: 140,
 783159: -600,
 783160: -140,
 783149: 650,
 783150: -500,
 783151: -1430,
 783152: -600,
 783153: 620,
 783154: 2220,
 783155: -660,
 783156: 650,
 783141: -420,
 783142: 2140,
 783143: 1440,
 783144: -140,
 873858: -620,
 873859: 120,
 873860: -500,
 873861: 140,
 873878: -140,
 873879: -110,
 873880: 100,
 873881: -430,
 873870: 450,
 873871: -100,
 873872: 450,
 873873: -980,
 873862: -100,
 873863: 110,
 873864: 1520,
 873865: 120,
 873882: -980,
 873883: -400,
 873884: -420,
 873885: -120,
 873874: 90,
 873875: -300,
 873876: -420,
 873877: 420,
 873866: 460,
 873867: 450,
 873868: 400,
 873869: -630,
 906514: -430,
 906515: 650,
 906516: -450,
 906517: 110,
 906530: -100,
 906531: -80,
 906532: -100,
 906533: -100,
 906534: 430,
 906535: 450,
 906536: -1440,
 906537: 300,
 906526: 620,
 906527: -140,
 906528: 1440,
 906529: 130,
 906518: 140,
 906519: -140,
 906520: 100,
 906521: 120,
 906522: 620,
 906523: 120,
 906524: -620,
 906525: 500,
 959834: 110,
 959835: -140,
 959836: 110,
 959837: -110,
 959850: -300,
 959851: -300,
 959852: -100,
 959853: -140,
 959846: -620,
 959847: 430,
 959848: 140,
 959849: 460,
 959838: -600,
 959839: 110,
 959840: 600,
 959841: 650,
 959854: -100,
 959855: 100,
 959856: -100,
 959857: -430,
 959858: -90,
 959859: 650,
 959860: 140,
 959861: -430,
 959842: -110,
 959843: -140,
 959844: -1440,
 959845: -600,
 959862: 600,
 959863: 620,
 959864: 1370,
 959865: 140,
 1102611: 620,
 1102612: 140,
 1102613: 300,
 1102614: -460,
 1102619: 100,
 1102620: 400,
 1102621: 100,
 1102622: -430,
 1102631: 90,
 1102632: 500,
 1102633: 120,
 1102634: 2220,
 1102635: -110,
 1102636: -650,
 1102637: 140,
 1102638: -630,
 1102615: -140,
 1102616: 90,
 1102617: -420,
 1102618: -110,
 1102627: -140,
 1102628: 100,
 1102629: -110,
 1102630: -630,
 1102623: -430,
 1102624: -100,
 1102625: 800,
 1102626: 100,
 1247133: -110,
 1247134: 140,
 1247135: 140,
 1247136: -140,
 1247153: 110,
 1247154: 110,
 1247155: 140,
 1247156: -120,
 1247149: 450,
 1247150: -140,
 1247151: -430,
 1247152: 100,
 1247145: -400,
 1247146: 430,
 ...}

In [33]:
assert df['board_id'].isin(pard).all()

In [34]:
del acbl_hrdf

In [35]:
# takes 2s
df.loc[df['ns_score'] == 'PASS','ns_score'] = '0'
assert df['ns_score'].ne('PASS').all()
df.loc[df['ew_score'] == 'PASS','ew_score'] = '0'
assert df['ew_score'].ne('PASS').all()

In [36]:
# takes 5s
# drop non-numeric scores. Around 18,000.
drop_scores = ~df['ns_score'].map(lambda c: c[c[0] == '-':].isnumeric()) | ~df['ew_score'].map(lambda c: c[c[0] == '-':].isnumeric())
df[drop_scores]

          board_result_id  board_id  round_number  table_number  ns_pair  ew_pair ns_score ew_score contract declarer  ew_match_points  ns_match_points opening_lead result  tricks_taken  section_id  board_number  session_id section_name  event_id hand_record_id                 game_date  club_id_number event_type board_scoring_method  tb_count         club_session        player_id_ns    player_number_ns                                        player_name_ns          mp_total_ns        player_id_ew                                     player_number_ew                                          player_name_ew           mp_total_ew
11839             2589187    369000             2             6        6        5       NP       NP                 N             0.00             0.00                               NaN       13937            28       11761            S     11761          10070 2019-09-04 00:00:00-05:00          100222      PAIRS         MATCH_POINTS      8.00  Wednesday Afternoon    [418650, 418649]  [9067027, 9578900]            ["Farrell, Don", "Mast, Earl(swap names)"]     [608.07, 794.54]    [418664, 418663]                                   [2735873, 5326567]          ["Orndorff, Tom", "Malone, Barry(swap names)"]       [189.3, 222.22]
12375             2726377    388158             1             3        3        3       NP       NP                 N             0.00             0.00                               NaN       14662            12       12352            M     12352          10587 2019-09-09 00:00:00-05:00          100222      PAIRS         MATCH_POINTS      6.00     Monday Afternoon    [440772, 440771]  [5901936, 9067183]        ["Allen, Barbara", "Romack, Dave(swap names)"]     [225.62, 252.97]    [440784, 440783]                                   [3763137, 3763145]             ["Layton, Mike", "Layton, Dee(swap names)"]        [92.66, 92.66]
12543             2772890    394838             6             2        2        4       NP       NP                 N             0.00             0.00                               NaN       14914            28       12558            D     12558          10784 2019-09-10 00:00:00-05:00          100222      PAIRS         MATCH_POINTS      7.00      Tuesday Morning    [448302, 448301]  [5901936, 9067183]        ["Allen, Barbara", "Romack, Dave(swap names)"]     [225.62, 252.97]    [448320, 448319]                                   [7396295, 9264256]           ["Stanley, Tracy", "Cook, Karen(swap names)"]       [110.32, 175.1]
16850             2992790    426339             4             7        7        4       NP       NP                 N             0.00             0.00                               NaN       16098            12       13516            B     13515          11650 2019-09-16 00:00:00-05:00          100222      PAIRS         MATCH_POINTS      7.00       Monday Evening    [483834, 483833]  [5788072, 6742009]      ["Daddario, Grace", "Nelson, Vance(swap names)"]     [593.96, 539.16]    [483841, 483842]                                   [3193640, 7371624]                  ["Koenigseder, Becky", "White, Larry"]    [4375.79, 1708.91]
16855             2992794    426340             1             4        4        4     AVE-     AVE+      3 D        W             3.60             2.40                  -2          7.00       16098            13       13516            B     13515          11650 2019-09-16 00:00:00-05:00          100222      PAIRS         MATCH_POINTS      7.00       Monday Evening    [483827, 483828]  [5910625, 6662250]                    ["Hillaker, Hugh", "Cassidy, Pat"]  [16870.45, 8591.84]    [483841, 483842]                                   [3193640, 7371624]                  ["Koenigseder, Becky", "White, Larry"]    [4375.79, 1708.91]
17333             3009342    428629             5             4        4        8       NP       NP                 N             0.00             0.00                               NaN       16183            24       13585            D     13584          11711 2019-09-17 00:00:00-05:00          100222      PAIRS         MATCH_POINTS      7.50      Tuesday Morning    [486504, 486503]  [4680839, 9564861]        ["Pempsell, Linda", "Hill, Wilma(swap names)"]       [5.39, 303.73]    [486525, 486526]                                   [2236400, 3101673]                  ["Deering, Helen", "Bedford, Dorothy"]        [0.0, 2349.65]
22469             3161391    450594             3             1        1        9    -620F     620F      4 S        W             8.00             0.00                   =         10.00       17013             7       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511236, 511235]  [3136612, 3572056]      ["Castioni, Liz", "Anderson, Joyce(swap names)"]     [595.76, 717.35]    [511272, 511271]                                   [4556585, 6938051]        ["Jones, Kimmel", "Kornegay, Nancy(swap names)"]  [11927.14, 11339.74]
22480             3161386    450593             7             6        6        9     480F    -480F      4 S        N             1.00             7.00                  +2         12.00       17013             6       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511245, 511246]  [2821699, 6745555]                     ["Keller, Carol", "Prince, Rita"]    [5168.59, 1163.5]    [511272, 511271]                                   [4556585, 6938051]        ["Jones, Kimmel", "Kornegay, Nancy(swap names)"]  [11927.14, 11339.74]
22489             3161382    450593             3            10       10        8     430F    -430F     3 NT        N             6.00             2.00                  +1         10.00       17013             6       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511253, 511254]  [1480731, 8503796]             ["Vanderwolk, Steve", "McConnell, Carol"]     [87.58, 2713.95]    [511269, 511270]                                   [2006774, 6398308]                    ["McGill, Richard", "Zachry, Joyce"]    [1527.49, 2065.76]
22502             3161396    450594             8             6        6        8     100F    -100F      4 S        W             1.50             6.50                  -1          9.00       17013             7       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511245, 511246]  [2821699, 6745555]                     ["Keller, Carol", "Prince, Rita"]    [5168.59, 1163.5]    [511269, 511270]                                   [2006774, 6398308]                    ["McGill, Richard", "Zachry, Joyce"]    [1527.49, 2065.76]
22514             3161392    450594             4            10       10        7     200F    -200F      4 S        W             0.00             8.00                  -2          8.00       17013             7       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511253, 511254]  [1480731, 8503796]             ["Vanderwolk, Steve", "McConnell, Carol"]     [87.58, 2713.95]    [511267, 511268]                                   [5623456, 6884822]                ["Meyer Nolan, Betty Jane", "Berg, Dee"]     [580.76, 3488.06]
22537             3161387    450593             8             5        5        7     420F    -420F      4 S        N             7.50             0.50                   =         10.00       17013             6       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511243, 511244]  [6779778, 7979177]                       ["Ryan, Yvonne", "Owren, Mary"]      [205.3, 151.42]    [511267, 511268]                                   [5623456, 6884822]                ["Meyer Nolan, Betty Jane", "Berg, Dee"]     [580.76, 3488.06]
22552             3161383    450593             4             9        9        6     450F    -450F      5 S        N             4.50             3.50                   =         11.00       17013             6       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511251, 511252]  [5252679, 8125600]            ["Stanton, Mary Ellen", "Peterson, Nancy"]   [2098.86, 3010.15]    [511265, 511266]                                   [4458079, 9747095]                      ["Hacker, Rosalee", "Parker, Ann"]    [1366.08, 1919.15]
22559             3161397    450594             9             5        5        6    -170F     170F      2 S        W             5.50             2.50                  +2         10.00       17013             7       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511243, 511244]  [6779778, 7979177]                       ["Ryan, Yvonne", "Owren, Mary"]      [205.3, 151.42]    [511265, 511266]                                   [4458079, 9747095]                      ["Hacker, Rosalee", "Parker, Ann"]    [1366.08, 1919.15]
22582             3161384    450593             5             8        8        4     460F    -460F     3 NT        N             3.00             5.00                  +2         11.00       17013             6       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511250, 511249]  [4571134, 9797629]      ["Booth, Connie", "Easley, Corrine(swap names)"]     [793.85, 728.71]    [511262, 511261]                                   [7396295, 9264256]           ["Stanley, Tracy", "Cook, Karen(swap names)"]       [110.32, 175.1]
22601             3161389    450594             1             3        3        3    -170F     170F      2 S        W             5.50             2.50                  +2         10.00       17013             7       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511240, 511239]  [4397703, 8592179]     ["Pennington, Ann", "Fields, Gloria(swap names)"]     [201.55, 479.18]    [511259, 511260]                                   [5197848, 7431538]                        ["Hill, Dwight", "Doe, Susan S"]      [542.81, 952.16]
22634             3161394    450594             6             8        8        2      70F     -70F      1 C        S             3.00             5.00                   =          7.00       17013             7       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511250, 511249]  [4571134, 9797629]      ["Booth, Connie", "Easley, Corrine(swap names)"]     [793.85, 728.71]    [511257, 511258]                                   [4640004, 9236643]                       ["Smith, Larz", "Corbett, Wayne"]     [1022.59, 141.53]
22648             3161380    450593             1             2        2        2     450F    -450F      4 S        N             4.50             3.50                  +1         11.00       17013             6       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511238, 511237]  [4639952, 8783314]  ["Nelson, Helen", "Schemensky, Jeannie(swap names)"]    [1565.16, 671.79]    [511257, 511258]                                   [4640004, 9236643]                       ["Smith, Larz", "Corbett, Wayne"]     [1022.59, 141.53]
22654             3161385    450593             6             7        7        1     480F    -480F      4 S        N             1.00             7.00                  +2         12.00       17013             6       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511247, 511248]  [3132889, 7556020]                     ["Gann, Melody", "Tryon, Mickey"]    [7637.8, 2311.62]    [511256, 511255]                                   [5051622, 8696519]        ["Taylor, Paul", "Scrimale, Robert(swap names)"]    [1384.54, 1248.29]
22673             3161390    450594             2             2        2        1     100F    -100F      4 S        W             1.50             6.50                  -1          9.00       17013             7       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511238, 511237]  [4639952, 8783314]  ["Nelson, Helen", "Schemensky, Jeannie(swap names)"]    [1565.16, 671.79]    [511256, 511255]                                   [5051622, 8696519]        ["Taylor, Paul", "Scrimale, Robert(swap names)"]    [1384.54, 1248.29]
22679             3161395    450594             7             7        7       10    -110F     110F      2 S        W             4.00             4.00                   =          8.00       17013             7       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511247, 511248]  [3132889, 7556020]                     ["Gann, Melody", "Tryon, Mickey"]    [7637.8, 2311.62]    [511273, 511274]                                   [1692658, 9277900]                      ["Robbins, John", "Benjamin, Ben"]      [669.34, 256.96]
22687             3161381    450593             2             1        1       10     420F    -420F      4 S        N             7.50             0.50                   =         10.00       17013             6       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511236, 511235]  [3136612, 3572056]      ["Castioni, Liz", "Anderson, Joyce(swap names)"]     [595.76, 717.35]    [511273, 511274]                                   [1692658, 9277900]                      ["Robbins, John", "Benjamin, Ben"]      [669.34, 256.96]
22712             3161393    450594             5             9        9        5    -300F     300F      4 C        S             7.00             1.00                  -3          7.00       17013             7       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511251, 511252]  [5252679, 8125600]            ["Stanton, Mary Ellen", "Peterson, Nancy"]   [2098.86, 3010.15]    [511264, 511263]                                   [5739675, 5788072]       ["Segreti, Carol", "Daddario, Grace(swap names)"]      [590.45, 593.96]
22726             3161388    450593             9             4        4        5     480F    -480F      4 S        S             1.00             7.00                  +2         12.00       17013             6       14312            S     14311          12322 2019-09-21 00:00:00-05:00          100222      PAIRS         MATCH_POINTS     20.50   Saturday Afternoon    [511242, 511241]  [4639987, 9486739]      ["Hirsch, Margot", "Willson, James(swap names)"]   [3646.16, 1096.31]    [511264, 511263]                                   [5739675, 5788072]       ["Segreti, Carol", "Daddario, Grace(swap names)"]      [590.45, 593.96]
47829             4168187    595676             4             3        3        6       NP       NP                 N             0.00             0.00                               NaN       22446            24       18876            D     18875          16159 2019-10-08 00:00:00-05:00          100222      PAIRS         MATCH_POINTS      5.50      Tuesday Morning    [673672, 673671]  [1403222, 1653598]      ["Kamath, Nara", "Chadwell, Harold(swap names)"]       [77.46, 66.15]    [673688, 673687]                                   [4679083, 5326567]              ["Mince, Al", "Malone, Barry(swap names)"]      [426.61, 242.04]
...                   ...       ...           ...           ...      ...      ...      ...      ...      ...      ...              ...              ...          ...    ...           ...         ...           ...         ...          ...       ...            ...                       ...             ...        ...                  ...       ...                  ...                 ...                 ...                                                   ...                  ...                 ...                                                  ...                                                     ...                   ...
49766253         16206076   2290658             6             9        9        4     140F    -140F      2 H        S             6.00             6.00                  +1          9.00       85923            28       70286            A     70280          56832 2020-01-09 00:00:00-06:00          276873      PAIRS         MATCH_POINTS     17.50   Thursday Afternoon  [2634504, 2634505]  [7488920, 8110751]                   ["Scott, Shirley", "Krassy, Susan"]   [5739.72, 2916.18]  [2634531, 2634530]                                   [1308076, 3179672]         ["Grant, Donna", "Campbell, Karen(swap names)"]      [832.67, 339.43]
49766359         16206072   2290658             2            13       13       12      50F     -50F      5 D        E            11.69             0.31                  -1         10.00       85923            28       70286            A     70280          56832 2020-01-09 00:00:00-06:00          276873      PAIRS         MATCH_POINTS     17.50   Thursday Afternoon  [2634513, 2634512]  [9460055, 9615334]   ["Kaiser, Barbara", "Brown, Edith Joy(swap names)"]     [330.86, 301.81]  [2634546, 2634547]                                   [1176897, 8476500]                  ["Goldston, Dennis", "Bagley, Bonnie"]    [9589.73, 6466.32]
49766399         16206080   2290658            11             4        4       11     110F    -110F      3 D        N             9.25             2.75                   =          9.00       85923            28       70286            A     70280          56832 2020-01-09 00:00:00-06:00          276873      PAIRS         MATCH_POINTS     17.50   Thursday Afternoon  [2634494, 2634495]  [3951294, 9114866]                     ["Bateman, Sandy", "Nimz, Kathy"]      [312.23, 84.54]  [2634544, 2634545]                                   [4957938, 9634495]                       ["Luk, Joe", "Williams, E Roger"]     [8882.74, 212.81]
49766453         16206081   2290658            12             3        3        9     620F    -620F      4 H        S             2.75             9.25                   =         10.00       85923            28       70286            A     70280          56832 2020-01-09 00:00:00-06:00          276873      PAIRS         MATCH_POINTS     17.50   Thursday Afternoon  [2634492, 2634493]  [5962366, 7112769]                      ["Goings, Thomas", "Lorck, Rob"]   [3927.93, 3649.47]  [2634540, 2634541]                                   [7116748, 9033270]                  ["Wingeard, Robert", "Levine, Melvin"]    [5225.87, 5739.67]

In [37]:
# takes 5s
df.drop(df[drop_scores].index,inplace=True)

In [38]:
# todo: why is declarer a category? Why does it contain non-NSEW? Need to change classifier in mlBridgeLib?
df['declarer'].value_counts()

N     2397436
E     2262092
W     2181148
S     2168215
EW         83
NS         66
           15
w           1
Name: declarer, dtype: int64

In [39]:
drop_declarers = ~df['declarer'].isin(list('NSEW')) # keep N,S,E,W. Drop EW, NS, w, ... < 200 cases.
df[drop_declarers]

          board_result_id  board_id  round_number  table_number  ns_pair  ew_pair ns_score ew_score contract declarer  ew_match_points  ns_match_points opening_lead result  tricks_taken  section_id  board_number  session_id section_name  event_id hand_record_id                 game_date  club_id_number event_type board_scoring_method  tb_count         club_session        player_id_ns                                     player_number_ns                                        player_name_ns         mp_total_ns        player_id_ew                                     player_number_ew                                          player_name_ew         mp_total_ew
4046908          19219939   2701971             4             5        5        2     -500      500                               5.00             0.00                               NaN      101274            12       83744            A     83744          66559 2020-01-28 00:00:00-06:00          118976      PAIRS         MATCH_POINTS      6.00      Tuesday Evening  [3127125, 3127126]                                   [5762200, 5804957]                ["Etkind, Wendy", "Freidin, Jonathan"]     [33.22, 130.85]  [3127131, 3127132]  [3105059, tmp:0d66458e-3772-4498-9888-64041867aa00]                        ["Filosa, Ron", "Garg, Swapnil"]       [112.07, nan]
12016170          9873369   1403835             9             6        6        9        0        0     PASS       NS             5.00             3.00                               NaN       52663             5       43212            A     43206          34921 2019-11-19 00:00:00-06:00          159004      PAIRS         MATCH_POINTS     11.00    Tuesday Afternoon  [1601985, 1601986]                                   [5393922, 5697824]             ["Greenbaum, Carolyn", "Stenson, Robert"]    [119.99, 117.14]  [1602013, 1602014]                                   [7706170, 7710631]                  ["Deaton, Robert", "Deaton, Victoria"]        [9.24, 5.95]
17243904         14450842   2041683             7             3        3        8     -300      300      4 S       EW             6.00             0.00                  -3          7.00       76566            26       62540            C     62534          50612 2019-12-24 00:00:00-06:00          209080      PAIRS         MATCH_POINTS     32.00    Tuesday Afternoon  [2348099, 2348100]                                   [2599686, 7667663]                ["Spector, Sue", "Greenbaum, Stanley"]       [81.37, 8.34]  [2348131, 2348132]  [2601893, tmp:5f0f0099-7280-440a-837d-01262b95fc3d]                     ["Burwick, Andrea", "Burwick, Bob"]       [26.58, 16.0]
18810101         17510175   2469677             7             8        8        2     -110      110      3 D       EW             6.50            10.50           S4      =          9.00       92601            15       75474            C     75468          61103 2020-01-17 00:00:00-06:00          217489      PAIRS         MATCH_POINTS     18.00     Friday Afternoon  [2847785, 2847784]                                   [3248089, 3562263]          ["Wright, Gwen", "King, Sandra(swap names)"]    [438.57, 432.66]  [2847791, 2847790]                                   [2284065, 9502130]         ["Rothbard, Marty", "Zaczek, Leon(swap names)"]    [599.79, 946.37]
19294536          6775981    969372             1             1        1        1      140     -140      3 H       NS             1.50             3.50                   =          9.00       36466             1       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098320, 1098319]  [5100666, tmp:b41e9765-50c0-4e1b-aebd-235c67a3dfd3]         ["Ater, Dianne", "Dykins, Cindy(swap names)"]         [31.1, nan]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19294537          6775987    969373             1             1        1        1       50      -50      2 S       EW             3.50             1.50                  -1          7.00       36466             2       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098320, 1098319]  [5100666, tmp:b41e9765-50c0-4e1b-aebd-235c67a3dfd3]         ["Ater, Dianne", "Dykins, Cindy(swap names)"]         [31.1, nan]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19294538          6775993    969374             1             1        1        1      170     -170      3 S       NS             4.00             1.00                  +1         10.00       36466             3       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098320, 1098319]  [5100666, tmp:b41e9765-50c0-4e1b-aebd-235c67a3dfd3]         ["Ater, Dianne", "Dykins, Cindy(swap names)"]         [31.1, nan]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19294539          6775999    969375             1             1        1        1     -100      100     3 NT       NS             3.50             1.50                  -1          8.00       36466             4       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098320, 1098319]  [5100666, tmp:b41e9765-50c0-4e1b-aebd-235c67a3dfd3]         ["Ater, Dianne", "Dykins, Cindy(swap names)"]         [31.1, nan]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19294540          6776009    969376             4             4        4        1      150     -150      4 C       EW             2.00             3.00                  -3          7.00       36466             5       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098326, 1098325]                                   [2580659, 8058261]          ["Walker, Molly", "Walker, Jim(swap names)"]      [78.06, 17.53]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19294541          6776015    969377             4             4        4        1     -100      100    4 S x       NS             3.50             1.50                  -1          9.00       36466             6       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098326, 1098325]                                   [2580659, 8058261]          ["Walker, Molly", "Walker, Jim(swap names)"]      [78.06, 17.53]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19294542          6776021    969378             4             4        4        1      600     -600      5 C       NS             3.00             2.00                   =         11.00       36466             7       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098326, 1098325]                                   [2580659, 8058261]          ["Walker, Molly", "Walker, Jim(swap names)"]      [78.06, 17.53]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19294543          6776027    969379             4             4        4        1     -430      430     3 NT       EW             4.50             0.50                  +1         10.00       36466             8       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098326, 1098325]                                   [2580659, 8058261]          ["Walker, Molly", "Walker, Jim(swap names)"]      [78.06, 17.53]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19294544          6776057    969384             5             5        5        1     -100      100      5 S       NS             4.00             1.00                  -1         10.00       36466            13       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098327, 1098328]                                   [7360061, 7360088]                ["France, Roger", "France, Mary Beth"]    [625.91, 534.41]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19294545          6776063    969385             5             5        5        1       50      -50      4 H       EW             2.50             2.50                  -1          9.00       36466            14       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098327, 1098328]                                   [7360061, 7360088]                ["France, Roger", "France, Mary Beth"]    [625.91, 534.41]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19294546          6776069    969386             5             5        5        1     -200      200      3 H       NS             2.00             3.00                  -2          7.00       36466            15       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098327, 1098328]                                   [7360061, 7360088]                ["France, Roger", "France, Mary Beth"]    [625.91, 534.41]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19294547          6776075    969387             5             5        5        1      -50       50      3 H       NS             4.00             1.00                  -1          8.00       36466            16       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098327, 1098328]                                   [7360061, 7360088]                ["France, Roger", "France, Mary Beth"]    [625.91, 534.41]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19294548          6776078    969388             3             3        3        1     -520      520     3 NT       EW             2.00             3.00                  +4         13.00       36466            17       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098323, 1098324]                                   [9213988, 9312021]               ["Jones, RaeDonna", "Butler, Margaret"]    [788.09, 605.08]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19294549          6776084    969389             3             3        3        1      110     -110      3 D       NS             1.50             3.50                   =          9.00       36466            18       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098323, 1098324]                                   [9213988, 9312021]               ["Jones, RaeDonna", "Butler, Margaret"]    [788.09, 605.08]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19294550          6776090    969390             3             3        3        1     -620      620      4 H       EW             4.50             0.50                   =         10.00       36466            19       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098323, 1098324]                                   [9213988, 9312021]               ["Jones, RaeDonna", "Butler, Margaret"]    [788.09, 605.08]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19294551          6776096    969391             3             3        3        1     -200      200      3 H       EW             2.50             2.50                  +2         11.00       36466            20       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098323, 1098324]                                   [9213988, 9312021]               ["Jones, RaeDonna", "Butler, Margaret"]    [788.09, 605.08]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19294552          6776106    969392             6             6        6        1      120     -120     1 NT       NS             0.50             4.50                  +1          8.00       36466            21       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098329, 1098330]                                   [9373489, 9373497]                    ["Young, Bonnie", "Stwalley, Ray"]      [15.15, 19.14]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19294553          6776112    969393             6             6        6        1      100     -100      3 C       EW             3.00             2.00                  -1          8.00       36466            22       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098329, 1098330]                                   [9373489, 9373497]                    ["Young, Bonnie", "Stwalley, Ray"]      [15.15, 19.14]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19294554          6776118    969394             6             6        6        1      100     -100      3 S       EW             3.00             2.00                  -1          8.00       36466            23       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098329, 1098330]                                   [9373489, 9373497]                    ["Young, Bonnie", "Stwalley, Ray"]      [15.15, 19.14]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19294555          6776124    969395             6             6        6        1       50      -50     2 NT       EW             1.00             4.00                  -1          7.00       36466            24       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098329, 1098330]                                   [9373489, 9373497]                    ["Young, Bonnie", "Stwalley, Ray"]      [15.15, 19.14]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
19294556          6776030    969380             2             2        2        1     -720      720     3 NT       EW             5.00             0.00                  +4         13.00       36466             9       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098321, 1098322]                                   [2670968, 5720435]                        ["Kuker, Dave", "Kuker, Jani"]      [140.8, 68.32]  [1098331, 1098332]                                   [8414505, 8523665]                     ["Plumb, Steve", "Blitstein, Mike"]  [1087.78, 1132.23]
...                   ...       ...           ...           ...      ...      ...      ...      ...      ...      ...              ...              ...          ...    ...           ...         ...           ...         ...          ...       ...            ...                       ...             ...        ...                  ...       ...                  ...                 ...                                                  ...                                                   ...                 ...                 ...                                                  ...                                                     ...                 ...
19294672          6776081    969388             5             6        6        2     -980      980      6 S       EW             4.00             1.00                   =         12.00       36466            17       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098329, 1098330]                                   [9373489, 9373497]                    ["Young, Bonnie", "Stwalley, Ray"]      [15.15, 19.14]  [1098334, 1098333]                                   [2670496, 7307322]        ["Golson, Tom", "Boatright, Harvey(swap names)"]       [57.76, 53.3]
19294673          6776087    969389             5             6        6        2      100     -100      3 H       EW             3.00             2.00                  -2          7.00       36466            18       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098329, 1098330]                                   [9373489, 9373497]                    ["Young, Bonnie", "Stwalley, Ray"]      [15.15, 19.14]  [1098334, 1098333]                                   [2670496, 7307322]        ["Golson, Tom", "Boatright, Harvey(swap names)"]       [57.76, 53.3]
19294674          6776093    969390             5             6        6        2     -110      110      2 H       EW             2.00             3.00                   =          8.00       36466            19       30412            A     30408          25096 2019-10-30 00:00:00-05:00          219097      PAIRS         MATCH_POINTS      6.00  Wednesday Afternoon  [1098329, 1098330]                                   [9373489, 9373497]                    ["Young, Bonnie", "Stwalley, Ray"]      [15.15, 19.14]  [1098334, 1098333]                                   [2670496, 7307322]        ["Golson, Tom", "Boatright, Harvey(swap names)"]       [57.76, 53.3]

In [40]:
# takes 4s
df.drop(df[drop_declarers].index,inplace=True)

In [41]:
# tb_count isn't reliable indicatior of determining top board.
#drop_match_points = (df['ns_match_points']+df['ew_match_points']) != (df['tb_count']-1)
#df[drop_match_points]
#df.head(100)

In [42]:
# takes 2s
# drop rows where ns_match_points + ew_match_points are outliers.
# todo: revisit
sum_rounded = (df['ns_match_points']+df['ew_match_points']).round(1) # round(1) or round(2)?
sum_rounded_dict = sum_rounded.value_counts().to_dict()
#df['ns_ew_match_point_vc'] = sum_rounded.map(sum_rounded_dict)
drop_match_points = sum_rounded.eq(0) | sum_rounded.map(sum_rounded_dict).le(200)
print(len(df),sum(drop_match_points))
df[drop_match_points]

9008891 10421

          board_result_id  board_id  round_number  table_number  ns_pair  ew_pair ns_score ew_score contract declarer  ew_match_points  ns_match_points opening_lead result  tricks_taken  section_id  board_number  session_id section_name  event_id hand_record_id                 game_date  club_id_number event_type board_scoring_method  tb_count         club_session        player_id_ns                                     player_number_ns                                            player_name_ns         mp_total_ns        player_id_ew                                     player_number_ew                                      player_name_ew          mp_total_ew
113217           13935752   1967256             4             7        7        4     -140      140      3 H        E             0.50             5.00                   =          9.00       73744             7       59437            K     59431          48716 2019-12-18 00:00:00-06:00          100230      PAIRS         MATCH_POINTS      8.00  Wednesday Afternoon  [2263741, 2263742]                                   [6672183, 8676283]                          ["White, Opie", "Sandars, Bill"]    [297.68, 494.09]  [2263751, 2263752]                                   [5903300, 6312934]                   ["Ream, Bill", "Parmley, Shelba"]  [4596.49, 15238.52]
113293           13935749   1967256             1             2        2        2     -110      140      3 H        E             0.50             6.00                   =          9.00       73744             7       59437            K     59431          48716 2019-12-18 00:00:00-06:00          100230      PAIRS         MATCH_POINTS      8.00  Wednesday Afternoon  [2263731, 2263732]                                   [6877281, 7522231]                 ["Bennett, Stephen", "Talbot, La Quitta"]   [610.99, 6088.25]  [2263748, 2263747]                                   [6431437, 8021112]    ["Sutherland, Ann", "Pettit, Flora(swap names)"]   [1103.33, 2068.21]
137450            3179757    453124            11             3        3        8      100      620      4 S        W            10.00            10.50                   =         10.00       17106            26       14400            A     14399          12399 2019-09-23 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     15.00     Monday Afternoon    [514145, 514146]                                   [2081016, 2124181]                     ["Kaufman, Beverly", "Colton, Susan"]  [2174.17, 1425.01]    [514185, 514186]                                   [4412788, 7605404]                ["Realini, Francis", "Hader, Aaron"]     [705.71, 675.77]
137514            3179751    453124             5             9        9        5      100     -100      4 S        W             0.00            10.50                  -1          9.00       17106            26       14400            A     14399          12399 2019-09-23 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     15.00     Monday Afternoon    [514157, 514158]                                   [5239060, 9899901]                       ["Scheiner, Harry", "Buma, Haruko"]    [252.37, 577.01]    [514179, 514180]                                   [5578833, 9077235]                ["Kanter, Carol", "Boltin, Roberta"]      [136.83, 61.03]
169507             829986    121290             5             3        3       10     -100      100      2 C        N             4.00             2.50                  -2          6.00        4594            19        3346            A      3346           3393 2019-06-05 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     11.00  Wednesday Afternoon    [133746, 133745]                                   [5078547, 3189619]  ["Schaumberger, Sylvia", "Dorfman, Barbara(swap names)"]    [406.51, 755.62]    [133781, 133782]                                   [1414593, 5888816]       ["Panayotatos, Nikos", "Usharovich, Gregory"]      [129.54, 31.66]
169633             829989    121290             8            11       11        4     -100      100      3 C        N             4.00             2.50                  -2          7.00        4594            19        3346            A      3346           3393 2019-06-05 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     11.00  Wednesday Afternoon    [133762, 133761]  [8415714, tmp:dfc861e7-64ed-4531-a955-ea42500bf613]          ["Abel, Rosalind", "SHEPARD, Barry(swap names)"]      [1342.04, nan]    [133770, 133769]                                   [8892563, 3296687]        ["Freel, Gerald", "Sibi, Kathy(swap names)"]   [1571.01, 1075.64]
171999             789672    115289             3            11       11        9     -450      450      4 S        W             4.50             2.00                  +1         11.00        4369             2        3629            A      3629           3231 2019-06-10 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     12.00       Monday Morning    [127212, 127211]                                   [2644150, 3575926]             ["Levine, Martin", "Abel, Bruce(swap names)"]    [283.63, 149.66]    [127231, 127232]                                   [3243907, 8758611]                 ["Newmeyer, Ralph", "Wolf, Daniel"]      [701.9, 919.36]
172131             789675    115289             6             8        8        3     -450      450      4 H        E             4.50             2.00                  +1         11.00        4369             2        3629            A      3629           3231 2019-06-10 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     12.00       Monday Morning    [127205, 127206]                                   [5578833, 9077235]                      ["Kanter, Carol", "Boltin, Roberta"]     [132.39, 60.63]    [127220, 127219]                                   [3243877, 8892563]     ["Cannon, Martin", "Freel, Gerald(swap names)"]    [202.81, 1571.01]
172155             789671    115289             2            12       12       11     -450      450      4 S        W             4.50             2.00                  +1         11.00        4369             2        3629            A      3629           3231 2019-06-10 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     12.00       Monday Morning    [127214, 127213]                                   [5078725, 1751123]             ["Levy, Judy", "Wilson, Loretta(swap names)"]    [1115.85, 949.9]    [127236, 127235]                                   [6347258, 5835569]    ["Turer, Allene", "Tanzman, Lottie(swap names)"]     [353.81, 366.51]
172206             789674    115289             5             9        9        5       50      450      5 S        W             4.50             7.00                   =         11.00        4369             2        3629            A      3629           3231 2019-06-10 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     12.00       Monday Morning    [127208, 127207]                                   [4444450, 8241597]           ["Field, Carol", "Grossman, Donna(swap names)"]  [3495.46, 1172.43]    [127224, 127223]                                   [8452881, 4472500]  ["Herbert, Madeleine", "Hough, Betty(swap names)"]   [1722.15, 1406.98]
172242             789670    115289             1             1        1        1     -450      450      5 S        W             4.50             2.00                   =         11.00        4369             2        3629            A      3629           3231 2019-06-10 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     12.00       Monday Morning    [127191, 127192]                                   [2678314, 8900957]                    ["Lermer, Donald", "Schwartz, Jerome"]    [147.42, 177.96]    [127215, 127216]                                   [6857167, 1085476]                ["Bachman, Myra", "Schwartz, Irene"]    [2742.7, 2548.44]
172266             789676    115289             7             7        7       12     -450      450      4 S        W             4.50             2.00                  +1         11.00        4369             2        3629            A      3629           3231 2019-06-10 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     12.00       Monday Morning    [127204, 127203]                                   [2124181, 2081016]         ["Colton, Susan", "Kaufman, Beverly(swap names)"]  [1403.17, 2147.61]    [127238, 127237]                                   [1998587, 1998617]  ["Rosen, Faye", "Greenberg, Mitchell(swap names)"]     [633.97, 642.38]
182663            1049850    152631            12             8        8       12      630     -630     3 NT        S             1.14            10.00                  +1         10.00        5786             7        4861            A      4861           4228 2019-07-01 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     15.00     Monday Afternoon    [169378, 169377]                                   [4444450, 8241597]           ["Field, Carol", "Grossman, Donna(swap names)"]  [3495.46, 1172.43]    [169415, 169416]                                   [2938499, 9234535]                ["Lieberman, Lana", "Ross, Roberta"]     [109.72, 123.49]
182691            1049843    152631             5            15       15       11     -100      100     3 NT        S             9.32             1.50                  -1          8.00        5786             7        4861            A      4861           4228 2019-07-01 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     15.00     Monday Afternoon    [169391, 169392]                                   [3575926, 5427673]                         ["Abel, Bruce", "Lesser, Irving"]    [149.66, 994.18]    [169414, 169413]                                   [4808592, 1350439]  ["Boswell, Miyoko", "Bernstein, Ruth(swap names)"]   [6506.93, 2658.82]
182793            1049845    152631             7            13       13        7      600     -600     3 NT        S             3.32             7.50                   =          9.00        5786             7        4861            A      4861           4228 2019-07-01 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     15.00     Monday Afternoon    [169388, 169387]                                   [9817298, 1836498]            ["Bauer, Allan", "Ganin, Barbara(swap names)"]      [543.6, 606.5]    [169405, 169406]  [5329779, tmp:7cfe73e5-1c05-4335-9093-cdf9d8c2f479]              ["Braunstein, Allan", "Hamer, Norman"]        [76.22, 54.0]
182845            1049846    152631             8            12       12        5      630     -630     3 NT        S             1.14            10.00                  +1         10.00        5786             7        4861            A      4861           4228 2019-07-01 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     15.00     Monday Afternoon    [169386, 169385]                                   [1387626, 1766880]               ["Peters, Dan", "Gordon, Neil(swap names)"]   [1605.82, 1771.4]    [169402, 169401]                                   [3243877, 8892563]     ["Cannon, Martin", "Freel, Gerald(swap names)"]    [202.81, 1571.01]
182891            1049847    152631             9            11       11        3      180     -180     2 NT        S             4.41             6.00                  +2         10.00        5786             7        4861            A      4861           4228 2019-07-01 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     15.00     Monday Afternoon    [169384, 169383]                                   [5078555, 5078547]    ["Morris, Felice", "Schaumberger, Sylvia(swap names)"]    [662.42, 406.51]    [169398, 169397]                                   [8042357, 8540039]     ["Danziger, Renee", "Limaye, Arun(swap names)"]    [530.77, 5055.66]
182905            1049849    152631            11             9        9       14      120     -120     1 NT        S             7.14             3.50                  +1          8.00        5786             7        4861            A      4861           4228 2019-07-01 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     15.00     Monday Afternoon    [169380, 169379]                                   [9386025, 9386017]   ["Pomerantz, Sandy", "Bar-Nissim, Barbara(swap names)"]     [155.34, 153.6]    [169420, 169419]                                   [2114208, 1757318]    ["Ghosh, Subrata", "Kuharetz, John(swap names)"]    [2926.4, 4969.09]
182933            1049842    152631             4             1        1       13      630     -630     3 NT        S             1.14            10.00                  +1         10.00        5786             7        4861            A      4861           4228 2019-07-01 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     15.00     Monday Afternoon    [169364, 169363]                                   [3257975, 7967829]        ["Sundheimer, Steven", "Rimer, Myron(swap names)"]   [2052.82, 3417.9]    [169418, 169417]                                   [9077553, 9077561]       ["Elk, Rosalind", "Elk, Seymour(swap names)"]  [12411.25, 1059.65]
182969            1049840    152631             2             3        3        2     -100      100     3 NT        S             9.32             1.50                  -1          8.00        5786             7        4861            A      4861           4228 2019-07-01 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     15.00     Monday Afternoon    [169368, 169367]                                   [6396550, 6396569]     ["Calkins, Glenda", "Calkins, R Barkley(swap names)"]  [3126.92, 2517.34]    [169396, 169395]                                   [3084582, 3098699]     ["Yarkon, Beverly", "Danow, Susan(swap names)"]      [92.87, 107.52]
182973            1049848    152631            10            10       10        1      150     -150     1 NT        S             5.50             5.00                  +2          9.00        5786             7        4861            A      4861           4228 2019-07-01 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     15.00     Monday Afternoon    [169382, 169381]                                   [5407427, 5411963]           ["Berson, Elaine", "Leanza, Joann(swap names)"]      [50.98, 96.05]    [169394, 169393]                                   [2124181, 2081016]   ["Colton, Susan", "Kaufman, Beverly(swap names)"]   [1403.17, 2147.61]
183015            1049841    152631             3             2        2       15      120     -120     1 NT        S             7.14             3.50                  +1          8.00        5786             7        4861            A      4861           4228 2019-07-01 00:00:00-05:00          100776      PAIRS         MATCH_POINTS     15.00     Monday Afternoon    [169365, 169366]                                   [2678314, 8900957]                    ["Lermer, Donald", "Schwartz, Jerome"]    [147.42, 177.96]    [169422, 169421]                                   [9899901, 5239060]     ["Buma, Haruko", "Scheiner, Harry(swap names)"]     [565.34, 239.68]
190623           15738388   2225661             2             1        1        8     -100      100      4 H        N             1.50             5.00                  -1          9.00       83486             5       68290            A     68284          55279 2020-01-07 00:00:00-06:00          100776      PAIRS         MATCH_POINTS      8.00    Tuesday Afternoon  [2557891, 2557890]                                   [3296687, 7967829]               ["Sibi, Kathy", "Rimer, Myron(swap names)"]  [1185.02, 3540.09]  [2557921, 2557920]                                   [3545431, 9505792]      ["Frey, Jeanne", "Haspel, Elaine(swap names)"]      [76.24, 506.54]
190629           15738393   2225661             7             5        5        7     -200      200      4 H        N             5.50             1.00                  -2          8.00       83486             5       68290            A     68284          55279 2020-01-07 00:00:00-06:00          100776      PAIRS         MATCH_POINTS      8.00    Tuesday Afternoon  [2557898, 2557899]                                   [4808592, 6603165]                       ["Boswell, Miyoko", "Sonne, Sally"]  [6716.04, 1913.77]  [2557918, 2557919]                                   [5078725, 5095727]                 ["Levy, Judy", "Serratore, Carole"]    [1173.29, 711.39]
190668           15738390   2225661             3             8        8        6     -100      100      4 H        N             1.50             5.00                  -1          9.00       83486             5       68290            A     68284          55279 2020-01-07 00:00:00-06:00          100776      PAIRS         MATCH_POINTS      8.00    Tuesday Afternoon  [2557904, 2557905]                                   [2669293, 5427673]                       ["Berkun, Allan", "Lesser, Irving"]    [192.98, 996.12]  [2557917, 2557916]                                   [6780253, 8382875]     ["Marber, Marilyn", "Gough, Marie(swap names)"]     [170.88, 206.63]
...                   ...       ...           ...           ...      ...      ...      ...      ...      ...      ...              ...              ...          ...    ...           ...         ...           ...         ...          ...       ...            ...                       ...             ...        ...                  ...       ...                  ...                 ...                                                  ...                                                       ...                 ...                 ...                                                  ...                                                 ...                  ...
49660218         10143826   1441443             2             2        2        1      -90       90     1 NT        W             0.50             0.50                   =          7.00       54072            24       44348            A     44342          35824 2019-11-20 00:00:00-06:00          276485      PAIRS         MATCH_POINTS      2.50    Wednesday Morning  [1646277, 1646278]  [9101047, tmp:58f1344a-4322-4223-9589-d8c37e5e875a]                     ["Baskin, Cynthia", "Baskin, Jeremy"]        [40.23, 4.0]  [1646282, 1646281]                                   [1230247, 4478827]        ["Wingo, Mary", "Zane, William(swap names)"]       [2.82, 3042.8]
49660219         10143813   1441436             3             1        1        2      450     -450      4 S        N             0.00             1.00                  +1         11.00       54072            17       44348            A     44342          35824 2019-11-20 00:00:00-06:00          276485      PAIRS         MATCH_POINTS      2.50    Wednesday Morning  [1646276, 1646275]  [2736098, tmp:ded7f3c3-c1ad-4c24-854c-5047b496a4b5]              ["Edmonds, James", "Meyer, Erv(swap names)"]     [363.33, 516.0]  [1646283, 1646284]                                   [4334310, 6248098]           ["Reilly, William", "Mooney, Jacquelinn"]        [54.89, 6.83]
49660220         10143815   1441437             3             1        1        2     -130      130      3 D        E             0.50             0.50                  +1         10.00       54072            18       44348            A     44342          35824 2019-11-20 00:00:00-06:00          276485      PAIRS         MATCH_POINTS      2.50    Wednesday Morning  [1646276, 1646275]  [2736098, tmp:ded7f3c3-c1ad-4c24-854c-5047b496a4b5]              ["Edmonds, James", "Meyer, Erv(swap names)"]     [363.33, 516.0]  [1646283, 1646284]                                   [4334310, 6248098]           ["Reilly, William", "Mooney, Jacquelinn"]        [54.89, 6.83]

In [43]:
# takes 4s
df.drop(df[drop_match_points].index,inplace=True)

In [44]:
assert df['ns_match_points'].notna().all()

In [45]:
# takes 2m30s
Club = df['club_id_number'].astype(str)
mae = [p[1][0] for p in df['club_session'].str.split(' ')] # Morning, Afternoon, Evening
Event = df['game_date'].dt.strftime('%y%m%d').astype(str)+mae
HandRecord = df['hand_record_id']
Board = df['board_number'].astype(str).str.zfill(2)
Key = Club+'_'+Event+'_'+Board
ClubDate = Club+'_'+Event
EventBoard = Event+'_'+Board
NSPair = df['section_name'].astype(str)+df['ns_pair'].astype(str).str.zfill(2)
EWPair = df['section_name'].astype(str)+df['ew_pair'].astype(str).str.zfill(2)
Pair = NSPair+'_'+EWPair
NNum = [p[0] for p in df['player_number_ns']]
NName = [p[0] for p in df['player_name_ns']]
SNum = [p[1] for p in df['player_number_ns']]
SName = [p[1] for p in df['player_name_ns']]
ENum = [p[0] for p in df['player_number_ew']]
EName = [p[0] for p in df['player_name_ew']]
WNum = [p[1] for p in df['player_number_ew']]
WName = [p[1] for p in df['player_name_ew']]
PairNS = ['_'.join(p) for p in df['player_number_ns']]
PairEW = ['_'.join(p) for p in df['player_number_ew']]
MP_NS = df['mp_total_ns']
MP_EW = df['mp_total_ew']
Score = df['ns_score']
Par = df['board_id'].map(pard)
MatchP = df['ns_match_points']
Pct = df['ns_match_points']/(df['ns_match_points']+df['ew_match_points']).round(1) # round(1) or round(2)?
contract = df['contract'].str.replace(' ','').str.upper().str.replace('NT','N') # remove spaces. force upper-case. replace NT with N.
contractdf = contract.str.extract(r'^(?P<BidLvl>\d)(?P<BidSuit>C|D|H|S|N)(?P<Dbl>X*)$')
BidLvl = contractdf['BidLvl']
BidSuit = contractdf['BidSuit']
Dbl = contractdf['Dbl']
NSEW = df['declarer']
Tricks = df['result'] # df['tricks_taken'] # -1, = +1, ...
EventBoardScore = EventBoard+'_'+Score

In [46]:
# attempting to free up some memory.
del df
import gc
gc.collect()

0

In [47]:
# takes 10s
Declarer = []
OnLead = []
Dummy = []
NotOnLead = []
for i,(d,n,e,s,w) in enumerate(zip(NSEW,NNum,ENum,SNum,WNum)):
    assert i == len(Declarer) and i == len(OnLead) and i == len(Dummy) and i == len(NotOnLead)
    if d == 'N':
        Declarer.append(n)
        OnLead.append(e)
        Dummy.append(s)
        NotOnLead.append(w)
    elif d == 'E':
        Declarer.append(e)
        OnLead.append(s)
        Dummy.append(w)
        NotOnLead.append(n)
    elif d == 'S':
        Declarer.append(s)
        OnLead.append(w)
        Dummy.append(n)
        NotOnLead.append(e)
    elif d == 'W':
        Declarer.append(w)
        OnLead.append(n)
        Dummy.append(e)
        NotOnLead.append(s)
    else: # d == nan
        Declarer.append(None)
        OnLead.append(None)
        Dummy.append(None)
        NotOnLead.append(None)
        #print(i,d,n,e,s,w)

In [48]:
# todo:
# cPairs, cFreq, cPct, cPairs299, cFreq299, cPct299, cKey?
# player table: NSEW-masterpoints, NSEW-power-rating, NSEW-rating, same for NS,EW pairs?

In [49]:
# takes 15s. 100s+1s/column?
df_dtypes = {
    'Key':"string",
    'ClubDate':"string",
    'EventBoard':"string",
    'HandRecord':"string", # UInt64?
    'Board':"string",
    'Pair':"string",
    'NNum':"string", # UInt8?
    'NName':"string",
    'SNum':"string", # UInt8?
    'SName':"string",
    'ENum':"string", # UInt8?
    'EName':"string",
    'WNum':"string", # UInt8?
    'WName':"string",
    'PairNS':"string",
    'PairEW':"string",
    'MP_NS':"object", # todo: do something else?
    'MP_EW':"object", # todo: do something else?
    'Score':"string",  # UInt8?
    'Par':"int16",
    'MatchP':"float32",
    'Pct':"float32",
    'NSPair':"string",
    'EWPair':"string",
    'BidLvl':"string", # UInt8, category?
    'BidSuit':"category",
    'Dbl':"category",
    'NSEW':"category",
    'Tricks':"string", # UInt8, category?
    'Declarer':"string", # UInt64?
    'OnLead':"string", # UInt64?
    'Dummy':"string", # UInt64?
    'NotOnLead':"string", # UInt64?
    'EventBoardScore':"string"
}

df_cols = {
    'Key':Key,
    'ClubDate':ClubDate,
    'EventBoard':EventBoard,
    'HandRecord':HandRecord,
    'Board':Board,
    'Pair':Pair,
    'NNum':NNum,
    'NName':NName,
    'SNum':SNum,
    'SName':SName,
    'ENum':ENum,
    'EName':EName,
    'WNum':WNum,
    'WName':WName,
    'PairNS':PairNS,
    'PairEW':PairEW,
    'MP_NS':MP_NS,
    'MP_EW':MP_EW,
    'Score':Score,
    'Par':Par,
    'MatchP':MatchP,
    'Pct':Pct,
    'NSPair':NSPair,
    'EWPair':EWPair,
    'BidLvl':BidLvl,
    'BidSuit':BidSuit,
    'Dbl':Dbl,
    'NSEW':NSEW,
    'Tricks':Tricks,
    'Declarer':Declarer,
    'OnLead':OnLead,
    'Dummy':Dummy,
    'NotOnLead':NotOnLead,
    'EventBoardScore':EventBoardScore
    }

assert set(df_cols.keys())-set(df_dtypes.keys()) == set()
df = pd.DataFrame(df_cols).astype(df_dtypes)
del df_cols
del df_dtypes

# alternative to df = pd.DataFrame(). Uses less memory?
#import pickle
#for k,v in df_cols.items():
#    tmp_file = acblPath.joinpath(k+'.tmp.pkl')
#    with open(tmp_file, 'wb') as f:
#        pickle.dump(v, f)

#with open(pickleFile, 'rb') as f:
#    optResultsDict = pickle.load(f)

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8998470 entries, 9027 to 50975894
Data columns (total 34 columns):
 #   Column           Dtype
---  ------           -----
 0   Key              string
 1   ClubDate         string
 2   EventBoard       string
 3   HandRecord       string
 4   Board            string
 5   Pair             string
 6   NNum             string
 7   NName            string
 8   SNum             string
 9   SName            string
 10  ENum             string
 11  EName            string
 12  WNum             string
 13  WName            string
 14  PairNS           string
 15  PairEW           string
 16  MP_NS            object
 17  MP_EW            object
 18  Score            string
 19  Par              int16
 20  MatchP           float32
 21  Pct              float32
 22  NSPair           string
 23  EWPair           string
 24  BidLvl           string
 25  BidSuit          category
 26  Dbl              category
 27  NSEW             category
 28  Tricks           string
 29  Declarer         string
 30  OnLead           string
 31  Dummy            string
 32  NotOnLead        string
 33  EventBoardScore  string
dtypes: category(3), float32(2), int16(1), object(2), string(26)
memory usage: 2.1+ GB

In [51]:
del Key
del ClubDate
del EventBoard
del HandRecord
del Board
del Pair
del NNum
del NName
del SNum
del SName
del ENum
del EName
del WNum
del WName
del PairNS
del PairEW
del MP_NS
del MP_EW
del Score
del Par
del MatchP
del Pct
del NSPair
del EWPair
del BidLvl
del BidSuit
del Dbl
del NSEW
del Tricks
del Declarer
del OnLead
del Dummy
del NotOnLead
del EventBoardScore
import gc
gc.collect()

0

In [52]:
# takes 1m
board_results_file = acblPath.joinpath('acbl-board-results-cleaned.pkl')
df.to_pickle(board_results_file)

In [53]:
# attempting to free up some memory.
del df
import gc
gc.collect()

0

In [54]:
# takes 20s
df = pd.read_pickle(board_results_file)
df

                        Key        ClubDate  EventBoard HandRecord Board     Pair     NNum                 NName     SNum                             SName     ENum               EName     WNum                            WName           PairNS           PairEW               MP_NS               MP_EW  Score   Par  MatchP  Pct NSPair EWPair BidLvl BidSuit Dbl NSEW Tricks Declarer   OnLead    Dummy NotOnLead   EventBoardScore
9027      100222_190821E_01  100222_190821E  190821E_01       8861    01  D02_D02  9264256         "Cook, Karen"  2961628          "Moore, Tom(swap names)"  7396295    "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  9264256_2961628  7396295_6497594   [170.09, 1815.45]   [104.69, 1832.54]   -100   110    3.50 0.50    D02    D02      1       N        N     -2  9264256  7396295  2961628   6497594   190821E_01_-100
9028      100222_190821E_02  100222_190821E  190821E_02       8861    02  D02_D02  9264256         "Cook, Karen"  2961628          "Moore, Tom(swap names)"  7396295    "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  9264256_2961628  7396295_6497594   [170.09, 1815.45]   [104.69, 1832.54]    100  -300    5.00 0.71    D02    D02      4       D        W     -2  6497594  9264256  7396295   2961628    190821E_02_100
9029      100222_190821E_03  100222_190821E  190821E_03       8861    03  D02_D02  9264256         "Cook, Karen"  2961628          "Moore, Tom(swap names)"  7396295    "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  9264256_2961628  7396295_6497594   [170.09, 1815.45]   [104.69, 1832.54]   -100   420    1.00 0.14    D02    D02      6       D        S     -2  2961628  6497594  9264256   7396295   190821E_03_-100
9030      100222_190821E_04  100222_190821E  190821E_04       8861    04  D06_D02  5630401           "Long, Sam"  2670356                      "Dixon, Bob"  7396295    "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  5630401_2670356  7396295_6497594   [2580.01, 443.77]   [104.69, 1832.54]   -690   140    2.00 0.29    D06    D02      3       N        E     +3  7396295  2670356  6497594   5630401   190821E_04_-690
9031      100222_190821E_05  100222_190821E  190821E_05       8861    05  D06_D02  5630401           "Long, Sam"  2670356                      "Dixon, Bob"  7396295    "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  5630401_2670356  7396295_6497594   [2580.01, 443.77]   [104.69, 1832.54]    180  -140    3.00 0.43    D06    D02      2       N        S     +2  2670356  6497594  5630401   7396295    190821E_05_180
9032      100222_190821E_06  100222_190821E  190821E_06       8861    06  D06_D02  5630401           "Long, Sam"  2670356                      "Dixon, Bob"  7396295    "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  5630401_2670356  7396295_6497594   [2580.01, 443.77]   [104.69, 1832.54]    460  -110    6.50 0.93    D06    D02      3       N        N     +2  5630401  7396295  2670356   6497594    190821E_06_460
9033      100222_190821E_19  100222_190821E  190821E_19       8861    19  D05_D02  4458079     "Hacker, Rosalee"  4632036      "Burke, Charles(swap names)"  7396295    "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  4458079_4632036  7396295_6497594  [1336.91, 1957.22]   [104.69, 1832.54]    -50   140    5.50 0.79    D05    D02      4       D        N     -1  4458079  7396295  4632036   6497594    190821E_19_-50
9034      100222_190821E_20  100222_190821E  190821E_20       8861    20  D05_D02  4458079     "Hacker, Rosalee"  4632036      "Burke, Charles(swap names)"  7396295    "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  4458079_4632036  7396295_6497594  [1336.91, 1957.22]   [104.69, 1832.54]    200  -620    4.00 0.57    D05    D02      2       C        E     -2  7396295  4632036  6497594   4458079    190821E_20_200
9035      100222_190821E_21  100222_190821E  190821E_21       8861    21  D05_D02  4458079     "Hacker, Rosalee"  4632036      "Burke, Charles(swap names)"  7396295    "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  4458079_4632036  7396295_6497594  [1336.91, 1957.22]   [104.69, 1832.54]   -170 -1400    4.00 0.57    D05    D02      3       H        W     +1  6497594  4458079  7396295   4632036   190821E_21_-170
9036      100222_190821E_07  100222_190821E  190821E_07       8861    07  D03_D02  2620499     "Walker, Mildred"  5378710      "Gilbreath, Sue(swap names)"  7396295    "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  2620499_5378710  7396295_6497594    [179.0, 1825.03]   [104.69, 1832.54]   -200  -140    4.50 0.64    D03    D02      3       S        E     +2  7396295  5378710  6497594   2620499   190821E_07_-200
9037      100222_190821E_08  100222_190821E  190821E_08       8861    08  D03_D02  2620499     "Walker, Mildred"  5378710      "Gilbreath, Sue(swap names)"  7396295    "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  2620499_5378710  7396295_6497594    [179.0, 1825.03]   [104.69, 1832.54]   -150  -430    1.50 0.21    D03    D02      4       D        W     +1  6497594  2620499  7396295   5378710   190821E_08_-150
9038      100222_190821E_09  100222_190821E  190821E_09       8861    09  D03_D02  2620499     "Walker, Mildred"  5378710      "Gilbreath, Sue(swap names)"  7396295    "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  2620499_5378710  7396295_6497594    [179.0, 1825.03]   [104.69, 1832.54]    130   120    4.50 0.64    D03    D02      3       D        N     +1  2620499  7396295  5378710   6497594    190821E_09_130
9039      100222_190821E_22  100222_190821E  190821E_22       8861    22  D01_D02  3224783        "Long, Ramona"  4534859      "Moore, Dorothy(swap names)"  7396295    "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  3224783_4534859  7396295_6497594    [368.5, 1501.34]   [104.69, 1832.54]   -110   500    4.50 0.64    D01    D02      2       D        E     +1  7396295  4534859  6497594   3224783   190821E_22_-110
9040      100222_190821E_23  100222_190821E  190821E_23       8861    23  D01_D02  3224783        "Long, Ramona"  4534859      "Moore, Dorothy(swap names)"  7396295    "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  3224783_4534859  7396295_6497594    [368.5, 1501.34]   [104.69, 1832.54]    300   -90    6.00 0.86    D01    D02      4       H        E     -3  7396295  4534859  6497594   3224783    190821E_23_300
9041      100222_190821E_24  100222_190821E  190821E_24       8861    24  D01_D02  3224783        "Long, Ramona"  4534859      "Moore, Dorothy(swap names)"  7396295    "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  3224783_4534859  7396295_6497594    [368.5, 1501.34]   [104.69, 1832.54]    480  1400    5.00 0.71    D01    D02      4       S        N     +2  3224783  7396295  4534859   6497594    190821E_24_480
9042      100222_190821E_16  100222_190821E  190821E_16       8861    16  D08_D02  8247099  "McDonald, Jeanette"  4639987      "Hirsch, Margot(swap names)"  7396295    "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  8247099_4639987  7396295_6497594   [811.61, 3635.64]   [104.69, 1832.54]  -1440  -300    0.00 0.00    D08    D02      6       N        E      =  7396295  4639987  6497594   8247099  190821E_16_-1440
9043      100222_190821E_17  100222_190821E  190821E_17       8861    17  D08_D02  8247099  "McDonald, Jeanette"  4639987      "Hirsch, Margot(swap names)"  7396295    "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  8247099_4639987  7396295_6497594   [811.61, 3635.64]   [104.69, 1832.54]    430   600    6.00 0.86    D08    D02      3       N        S     +1  4639987  6497594  8247099   7396295    190821E_17_430
9044      100222_190821E_18  100222_190821E  190821E_18       8861    18  D08_D02  8247099  "McDonald, Jeanette"  4639987      "Hirsch, Margot(swap names)"  7396295    "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  8247099_4639987  7396295_6497594   [811.61, 3635.64]   [104.69, 1832.54]    680   140    6.00 0.86    D08    D02      4       S        N     +2  8247099  7396295  4639987   6497594    190821E_18_680
9045      100222_190821E_13  100222_190821E  190821E_13       8861    13  D04_D02  7950985     "Jaeger, Georgie"  2494566        "Clark, Melba(swap names)"  7396295    "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  7950985_2494566  7396295_6497594   [3039.24, 1239.3]   [104.69, 1832.54]   -130  2220    2.00 0.29    D04    D02      2       C        W     +2  6497594  7950985  7396295   2494566   190821E_13_-130
9046      100222_190821E_14  100222_190821E  190821E_14       8861    14  D04_D02  7950985     "Jaeger, Georgie"  2494566        "Clark, Melba(swap names)"  7396295    "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  7950985_2494566  7396295_6497594   [3039.24, 1239.3]   [104.69, 1832.54]    550  -620    7.00 1.00    D04    D02      5       C   X    N      =  7950985  7396295  2494566   6497594    190821E_14_550
9047      100222_190821E_15  100222_190821E  190821E_15       8861    15  D04_D02  7950985     "Jaeger, Georgie"  2494566        "Clark, Melba(swap names)"  7396295    "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  7950985_2494566  7396295_6497594   [3039.24, 1239.3]   [104.69, 1832.54]   -420  -140    3.50 0.50    D04    D02      4       H        E      =  7396295  2494566  6497594   7950985   190821E_15_-420
9048      100222_190821E_10  100222_190821E  190821E_10       8861    10  D07_D02  9564861         "Hill, Wilma"  7958544    "Buchanan, Robert(swap names)"  7396295    "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  9564861_7958544  7396295_6497594   [294.15, 3371.16]   [104.69, 1832.54]   -630   650    0.50 0.07    D07    D02      3       N        E     +1  7396295  7958544  6497594   9564861   190821E_10_-630
9049      100222_190821E_11  100222_190821E  190821E_11       8861    11  D07_D02  9564861         "Hill, Wilma"  7958544    "Buchanan, Robert(swap names)"  7396295    "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  9564861_7958544  7396295_6497594   [294.15, 3371.16]   [104.69, 1832.54]   -400   500    0.00 0.00    D07    D02      3       N        W      =  6497594  9564861  7396295   7958544   190821E_11_-400
9050      100222_190821E_12  100222_190821E  190821E_12       8861    12  D07_D02  9564861         "Hill, Wilma"  7958544    "Buchanan, Robert(swap names)"  7396295    "Stanley, Tracy"  6497594  "Langland, Richard(swap names)"  9564861_7958544  7396295_6497594   [294.15, 3371.16]   [104.69, 1832.54]     50  -110    4.00 0.57    D07    D02      3       H        E     -1  7396295  7958544  6497594   9564861     190821E_12_50
9051      100222_190821E_04  100222_190821E  190821E_04       8861    04  D02_D01  9264256         "Cook, Karen"  2961628          "Moore, Tom(swap names)"  5756464      "Petry, Susan"  4512405        "Floyd, Judy(swap names)"  9264256_2961628  5756464_4512405   [170.09, 1815.45]   [129.48, 1287.43]   -690   140    2.00 0.29    D02    D01      3       N        E     +3  5756464  2961628  4512405   9264256   190821E_04_-690
...                     ...             ...         ...        ...   ...      ...      ...                   ...      ...                               ...      ...                 ...      ...                              ...              ...              ...                 ...                 ...    ...   ...     ...  ...    ...    ...    ...     ...  ..  ...    ...      ...      ...      ...       ...               ...
50975870  905349_200119A_21  905349_200119A  200119A_21      69085    21  A05_A03  6684696         "Wood, Carol"  6709435     "Hughes, Beverly(swap names)"  1153145   "Diwell, Darrell"  1153242      "Diwell, Carol(swap names)"  6684696_6709435  1153145_1153242  [2078.03, 2441.91]   [1871.1, 2578.56]    150  -660    5.79 0.83    A05    A03      2       N        W     -3  1153242  6684696  1153145   6709435    200119A_21_150
50975871  905349_200119A_19  905349_200119A  200119A_19      69085    19  A09_A02  8362904      "Hoover, Kymber"  9086846  "Fujimoto, Reginald(swap names)"  2208334  "Garrison, Millie"  8484031                "Villalon, Caryn"  8362904_9086846  2208334_8484031    [1368.6, 706.14]  [3433.06, 3511.26]    120  -140    5.00 0.71    A09    A02      1       N        N     +1  8362904  2208334  9086846   8484031    200119A_19_120
50975872  905349_200119A_20  905349_200119A  200119A_20      69085    20  A09_A02  8362904      "Hoover, Kymber"  9086846  "Fujimoto, Reginald(swap names)"  2208334  "Garrison, Millie"  8484031                "Villalon, Caryn"  8362904_9086846  2208334_8484031    [1368.6, 706.14]  [3433.06, 3511.26]   -990  -140    0.00 0.00    A09    A02      4       H   X    W     +1  8484031  8362904  2208334   9086846   200119A_20_-990
50975873  905349_200119A_21  905349_200119A  200119A_21      69085    21  A09_A02  8362904      "Hoover, Kymber"  9086846  "Fujimoto, Reginald(swap names)"  2208334  "Garrison, Millie"  8484031                "Villalon, Caryn"  8362904_9086846  2208334_8484031    [1368.6, 706.14]  [3433.06, 3511.26]   -200  -660    0.64 0.09    A09    A02      3       H        S     -2  9086846  8484031  8362904   2208334   200119A_21_-200
50975874  905349_200119A_13  905349_200119A  200119A_13      69085    13  A08_A02  7426321        "Clarida, Rod"  7426348   "Clarida, Kathleen(swap names)"  2208334  "Garrison, Millie"  8484031                "Villalon, Caryn"  7426321_7426348  2208334_8484031        [12.8, 12.8]  [3433.06, 3511.26]   -120   600    4.64 0.66    A08    A02      2       N        E      =  2208334  7426348  8484031   7426321   200119A_13_-120
50975875  905349_200119A_14  905349_200119A  200119A_14      69085    14  A08_A02  7426321        "Clarida, Rod"  7426348   "Clarida, Kathleen(swap names)"  2208334  "Garrison, Millie"  8484031                "Villalon, Caryn"  7426321_7426348  2208334_8484031        [12.8, 12.8]  [3433.06, 3511.26]   -170  -140    0.07 0.01    A08    A02      3       C        E     +3  2208334  7426348  8484031   7426321   200119A_14_-170
50975876  905349_200119A_15  905349_200119A  200119A_15      69085    15  A08_A02  7426321        "Clarida, Rod"  7426348   "Clarida, Kathleen(swap names)"  2208334  "Garrison, Millie"  8484031                "Villalon, Caryn"  7426321_7426348  2208334_8484031        [12.8, 12.8]  [3433.06, 3511.26]   -420 -1440    0.07 0.01    A08    A02      5       C        W     +1  8484031  7426321  2208334   7426348   200119A_15_-420
50975877  905349_200119A_07  905349_200119A  200119A_07      69085    07  A07_A02  2123878       "Heberle, John"  5749522                      "Mina, Rami"  2208334  "Garrison, Millie"  8484031                "Villalon, Caryn"  2123878_5749522  2208334_8484031    [679.18, 1501.5]  [3433.06, 3511.26]   -300  -420    1.21 0.17    A07    A02      3       N        N     -3  2123878  2208334  5749522   8484031   200119A_07_-300
50975878  905349_200119A_08  905349_200119A  200119A_08      69085    08  A07_A02  2123878       "Heberle, John"  5749522                      "Mina, Rami"  2208334  "Garrison, Millie"  8484031                "Villalon, Caryn"  2123878_5749522  2208334_8484031    [679.18, 1501.5]  [3433.06, 3511.26]   -430  -140    2.36 0.34    A07    A02      3       N        E     +1  2208334  5749522  8484031   2123878   200119A_08_-430
50975879  905349_200119A_09  905349_200119A  200119A_09      69085    09  A07_A02  2123878       "Heberle, John"  5749522                      "Mina, Rami"  2208334  "Garrison, Millie"  8484031                "Villalon, Caryn"  2123878_5749522  2208334_8484031    [679.18, 1501.5]  [3433.06, 3511.26]    -50  -460    1.79 0.26    A07    A02      2       S        N     -1  2123878  2208334  5749522   8484031    200119A_09_-50
50975880  905349_200119A_16  905349_200119A  200119A_16      69085    16  A04_A02  1683942       "Fader, Milton"  4090756    "Swanson, Carolyn(swap names)"  2208334  "Garrison, Millie"  8484031                "Villalon, Caryn"  1683942_4090756  2208334_8484031  [1645.31, 1265.22]  [3433.06, 3511.26]    480  -500    1.21 0.17    A04    A02      4       S        N     +2  1683942  2208334  4090756   8484031    200119A_16_480
50975881  905349_200119A_17  905349_200119A  200119A_17      69085    17  A04_A02  1683942       "Fader, Milton"  4090756    "Swanson, Carolyn(swap names)"  2208334  "Garrison, Millie"  8484031                "Villalon, Caryn"  1683942_4090756  2208334_8484031  [1645.31, 1265.22]  [3433.06, 3511.26]    170   650    4.07 0.58    A04    A02      2       H        N     +2  1683942  2208334  4090756   8484031    200119A_17_170
50975882  905349_200119A_18  905349_200119A  200119A_18      69085    18  A04_A02  1683942       "Fader, Milton"  4090756    "Swanson, Carolyn(swap names)"  2208334  "Garrison, Millie"  8484031                "Villalon, Caryn"  1683942_4090756  2208334_8484031  [1645.31, 1265.22]  [3433.06, 3511.26]   -400   110    2.36 0.34    A04    A02      5       C        E      =  2208334  4090756  8484031   1683942   200119A_18_-400
50975883  905349_200119A_10  905349_200119A  200119A_10      69085    10  A03_A02  2289679          "Reddy, Pia"  7219938              "Boomgaarden, Arden"  2208334  "Garrison, Millie"  8484031                "Villalon, Caryn"  2289679_7219938  2208334_8484031     [15.94, 669.74]  [3433.06, 3511.26]    650  -130    0.64 0.09    A03    A02      4       S        N     +1  2289679  2208334  7219938   8484031    200119A_10_650
50975884  905349_200119A_11  905349_200119A  200119A_11      69085    11  A03_A02  2289679          "Reddy, Pia"  7219938              "Boomgaarden, Arden"  2208334  "Garrison, Millie"  8484031                "Villalon, Caryn"  2289679_7219938  2208334_8484031     [15.94, 669.74]  [3433.06, 3511.26]     50  -140    5.79 0.83    A03    A02      4       S        W     -1  8484031  2289679  2208334   7219938     200119A_11_50
50975885  905349_200119A_12  905349_200119A  200119A_12      69085    12  A03_A02  2289679          "Reddy, Pia"  7219938              "Boomgaarden, Arden"  2208334  "Garrison, Millie"  8484031                "Villalon, Caryn"  2289679_7219938  2208334_8484031     [15.94, 669.74]  [3433.06, 3511.26]   -120  -110    0.07 0.01    A03    A02      1       N        E     +1  2208334  7219938  8484031   2289679   200119A_12_-120
50975886  905349_200119A_01  905349_200119A  200119A_01      69085    01  A06_A02  2491877      "Janssen, Donna"  2491974     "Janssen, Marcel(swap names)"  2208334  "Garrison, Millie"  8484031                "Villalon, Caryn"  2491877_2491974  2208334_8484031    [367.21, 350.43]  [3433.06, 3511.26]    980  -990    6.93 0.99    A06    A02      6       S        S      =  2491974  8484031  2491877   2208334    200119A_01_980
50975887  905349_200119A_02  905349_200119A  200119A_02      69085    02  A06_A02  2491877      "Janssen, Donna"  2491974     "Janssen, Marcel(swap names)"  2208334  "Garrison, Millie"  8484031                "Villalon, Caryn"  2491877_2491974  2208334_8484031    [367.21, 350.43]  [3433.06, 3511.26]     50   110    3.50 0.50    A06    A02      3       H        E     -1  2208334  2491974  8484031   2491877     200119A_02_50
50975888  905349_200119A_03  905349_200119A  200119A_03      69085    03  A06_A02  2491877      "Janssen, Donna"  2491974     "Janssen, Marcel(swap names)"  2208334  "Garrison, Millie"  8484031                "Villalon, Caryn"  2491877_2491974  2208334_8484031    [367.21, 350.43]  [3433.06, 3511.26]   -150   140    0.64 0.09    A06    A02      3       H        S     -3  2491974  8484031  2491877   2208334   200119A_03_-150

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8998470 entries, 9027 to 50975894
Data columns (total 34 columns):
 #   Column           Dtype
---  ------           -----
 0   Key              string
 1   ClubDate         string
 2   EventBoard       string
 3   HandRecord       string
 4   Board            string
 5   Pair             string
 6   NNum             string
 7   NName            string
 8   SNum             string
 9   SName            string
 10  ENum             string
 11  EName            string
 12  WNum             string
 13  WName            string
 14  PairNS           string
 15  PairEW           string
 16  MP_NS            object
 17  MP_EW            object
 18  Score            string
 19  Par              int16
 20  MatchP           float32
 21  Pct              float32
 22  NSPair           string
 23  EWPair           string
 24  BidLvl           string
 25  BidSuit          category
 26  Dbl              category
 27  NSEW             category
 28  Tricks           string
 29  Declarer         string
 30  OnLead           string
 31  Dummy            string
 32  NotOnLead        string
 33  EventBoardScore  string
dtypes: category(3), float32(2), int16(1), object(2), string(26)
memory usage: 2.1+ GB